<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumoSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('insumos')->insert([
            // Materiales de Construcción
            [
                'insumo' => 'Cemento Portland 50kg',
                'id_categoria' => 1,
                'unidad' => 'bolsa',
                'stock_actual' => 250,
                'stock_minimo' => 100,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cal Hidratada 25kg',
                'id_categoria' => 1,
                'unidad' => 'bolsa',
                'stock_actual' => 80,
                'stock_minimo' => 50,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Arena Gruesa',
                'id_categoria' => 1,
                'unidad' => 'm³',
                'stock_actual' => 45,
                'stock_minimo' => 20,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Arena Fina',
                'id_categoria' => 1,
                'unidad' => 'm³',
                'stock_actual' => 30,
                'stock_minimo' => 15,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Piedra Partida 6-20',
                'id_categoria' => 1,
                'unidad' => 'm³',
                'stock_actual' => 60,
                'stock_minimo' => 25,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Ladrillo Común',
                'id_categoria' => 1,
                'unidad' => 'unidad',
                'stock_actual' => 15000,
                'stock_minimo' => 5000,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Ladrillo Hueco 8cm',
                'id_categoria' => 1,
                'unidad' => 'unidad',
                'stock_actual' => 8000,
                'stock_minimo' => 3000,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Hierro 8mm x 12m',
                'id_categoria' => 1,
                'unidad' => 'barra',
                'stock_actual' => 120,
                'stock_minimo' => 50,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Hierro 10mm x 12m',
                'id_categoria' => 1,
                'unidad' => 'barra',
                'stock_actual' => 90,
                'stock_minimo' => 40,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Alambre Negro kg',
                'id_categoria' => 1,
                'unidad' => 'kg',
                'stock_actual' => 150,
                'stock_minimo' => 80,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Herramientas
            [
                'insumo' => 'Pala Ancha',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 25,
                'stock_minimo' => 10,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pico',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 18,
                'stock_minimo' => 8,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Carretilla',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 12,
                'stock_minimo' => 6,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Balde Albañil 20L',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 30,
                'stock_minimo' => 15,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Nivel de Burbuja 60cm',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 8,
                'stock_minimo' => 5,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cuchara Albañil',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 20,
                'stock_minimo' => 10,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Martillo',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 15,
                'stock_minimo' => 8,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Materiales Eléctricos
            [
                'insumo' => 'Cable 2.5mm x 100m',
                'id_categoria' => 3,
                'unidad' => 'rollo',
                'stock_actual' => 12,
                'stock_minimo' => 5,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cable 4mm x 100m',
                'id_categoria' => 3,
                'unidad' => 'rollo',
                'stock_actual' => 8,
                'stock_minimo' => 3,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Caño PVC 5/8"',
                'id_categoria' => 3,
                'unidad' => 'barra',
                'stock_actual' => 150,
                'stock_minimo' => 60,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Llave Termica 10A',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 35,
                'stock_minimo' => 15,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Disyuntor 25A',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 20,
                'stock_minimo' => 10,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Toma Corriente 10A',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 80,
                'stock_minimo' => 40,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Llave de Luz Simple',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 100,
                'stock_minimo' => 50,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Plomería y Sanitarios
            [
                'insumo' => 'Caño PVC 110mm x 3m',
                'id_categoria' => 4,
                'unidad' => 'caño',
                'stock_actual' => 45,
                'stock_minimo' => 20,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Caño PVC 63mm x 3m',
                'id_categoria' => 4,
                'unidad' => 'caño',
                'stock_actual' => 60,
                'stock_minimo' => 25,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Codo 90° PVC 110mm',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 80,
                'stock_minimo' => 40,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Canilla Jardín 3/4"',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 25,
                'stock_minimo' => 12,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Manguera 1/2" x 50m',
                'id_categoria' => 4,
                'unidad' => 'rollo',
                'stock_actual' => 8,
                'stock_minimo' => 4,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Tanque Agua 1000L',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 5,
                'stock_minimo' => 2,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Pintura y Revestimientos
            [
                'insumo' => 'Pintura Látex Blanco 20L',
                'id_categoria' => 5,
                'unidad' => 'balde',
                'stock_actual' => 40,
                'stock_minimo' => 20,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pintura Látex Color 4L',
                'id_categoria' => 5,
                'unidad' => 'balde',
                'stock_actual' => 30,
                'stock_minimo' => 15,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Enduido Exterior 30kg',
                'id_categoria' => 5,
                'unidad' => 'bolsa',
                'stock_actual' => 60,
                'stock_minimo' => 30,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Aguarrás 5L',
                'id_categoria' => 5,
                'unidad' => 'bidón',
                'stock_actual' => 18,
                'stock_minimo' => 10,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Rodillo 23cm',
                'id_categoria' => 5,
                'unidad' => 'unidad',
                'stock_actual' => 50,
                'stock_minimo' => 25,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}