<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('insumos')->insert([
            // Materiales de Construcción (Categoría 1)
            [
                'insumo' => 'Cemento Portland x 50kg',
                'id_categoria' => 1,
                'unidad' => 'bolsa',
                'stock_actual' => 150,
                'stock_minimo' => 50,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Arena Fina x m3',
                'id_categoria' => 1,
                'unidad' => 'm3',
                'stock_actual' => 25,
                'stock_minimo' => 10,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Ladrillo Común',
                'id_categoria' => 1,
                'unidad' => 'unidad',
                'stock_actual' => 3000,
                'stock_minimo' => 1000,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cal Hidratada x 25kg',
                'id_categoria' => 1,
                'unidad' => 'bolsa',
                'stock_actual' => 80,
                'stock_minimo' => 30,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Piedra Partida x m3',
                'id_categoria' => 1,
                'unidad' => 'm3',
                'stock_actual' => 15,
                'stock_minimo' => 8,
                'id_deposito' => 3,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Herramientas Manuales (Categoría 2)
            [
                'insumo' => 'Pala Ancha',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 25,
                'stock_minimo' => 10,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pico',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 18,
                'stock_minimo' => 10,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Martillo Carpintero',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 12,
                'stock_minimo' => 8,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Destornillador Plano',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 8,
                'stock_minimo' => 15,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Llave Francesa 12"',
                'id_categoria' => 2,
                'unidad' => 'unidad',
                'stock_actual' => 6,
                'stock_minimo' => 10,
                'id_deposito' => 2,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Pinturas y Revestimientos (Categoría 3)
            [
                'insumo' => 'Pintura Látex Blanca x 20L',
                'id_categoria' => 3,
                'unidad' => 'balde',
                'stock_actual' => 45,
                'stock_minimo' => 20,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pintura Esmalte Sintético Blanco x 4L',
                'id_categoria' => 3,
                'unidad' => 'lata',
                'stock_actual' => 30,
                'stock_minimo' => 15,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Diluyente x 5L',
                'id_categoria' => 3,
                'unidad' => 'bidón',
                'stock_actual' => 20,
                'stock_minimo' => 10,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Rodillo para Pintar 23cm',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 15,
                'stock_minimo' => 20,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pincel 3"',
                'id_categoria' => 3,
                'unidad' => 'unidad',
                'stock_actual' => 25,
                'stock_minimo' => 30,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Electricidad (Categoría 4)
            [
                'insumo' => 'Cable TPR 3x2.5mm x metro',
                'id_categoria' => 4,
                'unidad' => 'metro',
                'stock_actual' => 200,
                'stock_minimo' => 100,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Enchufe 3 Patas 10A',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 35,
                'stock_minimo' => 25,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Llave Térmica 2x40A',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 12,
                'stock_minimo' => 8,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Tubo Fluorescente LED 18W',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 40,
                'stock_minimo' => 30,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cinta Aisladora',
                'id_categoria' => 4,
                'unidad' => 'unidad',
                'stock_actual' => 50,
                'stock_minimo' => 40,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Plomería (Categoría 5)
            [
                'insumo' => 'Caño PVC 110mm x 6m',
                'id_categoria' => 5,
                'unidad' => 'caño',
                'stock_actual' => 25,
                'stock_minimo' => 15,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Llave de Paso 1/2"',
                'id_categoria' => 5,
                'unidad' => 'unidad',
                'stock_actual' => 18,
                'stock_minimo' => 12,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Codo PVC 90° 110mm',
                'id_categoria' => 5,
                'unidad' => 'unidad',
                'stock_actual' => 40,
                'stock_minimo' => 30,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Canilla Cromada 1/2"',
                'id_categoria' => 5,
                'unidad' => 'unidad',
                'stock_actual' => 8,
                'stock_minimo' => 15,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pegamento PVC x 250ml',
                'id_categoria' => 5,
                'unidad' => 'pomo',
                'stock_actual' => 22,
                'stock_minimo' => 15,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Ferretería General (Categoría 6)
            [
                'insumo' => 'Tornillo Autoperforante 8x1"',
                'id_categoria' => 6,
                'unidad' => 'kg',
                'stock_actual' => 35,
                'stock_minimo' => 20,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Clavo 2.5"',
                'id_categoria' => 6,
                'unidad' => 'kg',
                'stock_actual' => 50,
                'stock_minimo' => 30,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Bulón 10x50mm',
                'id_categoria' => 6,
                'unidad' => 'unidad',
                'stock_actual' => 200,
                'stock_minimo' => 150,
                'id_deposito' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Arandela Plana 10mm',
                'id_categoria' => 6,
                'unidad' => 'unidad',
                'stock_actual' => 300,
                'stock_minimo' => 200,
                'id_deposito' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Tuerca Hexagonal 10mm',
                'id_categoria' => 6,
                'unidad' => 'unidad',
                'stock_actual' => 250,
                'stock_minimo' => 200,
                'id_deposito' => 7,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Seguridad e Higiene (Categoría 7)
            [
                'insumo' => 'Casco de Seguridad',
                'id_categoria' => 7,
                'unidad' => 'unidad',
                'stock_actual' => 15,
                'stock_minimo' => 25,
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Guantes de Seguridad',
                'id_categoria' => 7,
                'unidad' => 'par',
                'stock_actual' => 40,
                'stock_minimo' => 50,
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Antiparras de Seguridad',
                'id_categoria' => 7,
                'unidad' => 'unidad',
                'stock_actual' => 18,
                'stock_minimo' => 20,
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Barbijo N95',
                'id_categoria' => 7,
                'unidad' => 'unidad',
                'stock_actual' => 100,
                'stock_minimo' => 200,
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Botín de Seguridad',
                'id_categoria' => 7,
                'unidad' => 'par',
                'stock_actual' => 12,
                'stock_minimo' => 20,
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Limpieza y Mantenimiento (Categoría 8)
            [
                'insumo' => 'Lavandina x 5L',
                'id_categoria' => 8,
                'unidad' => 'bidón',
                'stock_actual' => 30,
                'stock_minimo' => 20,
                'id_deposito' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Detergente Líquido x 5L',
                'id_categoria' => 8,
                'unidad' => 'bidón',
                'stock_actual' => 25,
                'stock_minimo' => 15,
                'id_deposito' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Escoba Plástica',
                'id_categoria' => 8,
                'unidad' => 'unidad',
                'stock_actual' => 20,
                'stock_minimo' => 15,
                'id_deposito' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Trapo de Piso',
                'id_categoria' => 8,
                'unidad' => 'unidad',
                'stock_actual' => 35,
                'stock_minimo' => 30,
                'id_deposito' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Balde Plástico 20L',
                'id_categoria' => 8,
                'unidad' => 'unidad',
                'stock_actual' => 15,
                'stock_minimo' => 12,
                'id_deposito' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Jardinería (Categoría 9)
            [
                'insumo' => 'Semilla Césped x kg',
                'id_categoria' => 9,
                'unidad' => 'kg',
                'stock_actual' => 50,
                'stock_minimo' => 30,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Fertilizante Triple 15 x 50kg',
                'id_categoria' => 9,
                'unidad' => 'bolsa',
                'stock_actual' => 40,
                'stock_minimo' => 25,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Tierra Negra x m3',
                'id_categoria' => 9,
                'unidad' => 'm3',
                'stock_actual' => 15,
                'stock_minimo' => 10,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Maceta Plástica 30cm',
                'id_categoria' => 9,
                'unidad' => 'unidad',
                'stock_actual' => 60,
                'stock_minimo' => 40,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Manguera de Riego 1/2" x metro',
                'id_categoria' => 9,
                'unidad' => 'metro',
                'stock_actual' => 80,
                'stock_minimo' => 50,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Señalización Vial (Categoría 10)
            [
                'insumo' => 'Cono Vial 75cm',
                'id_categoria' => 10,
                'unidad' => 'unidad',
                'stock_actual' => 45,
                'stock_minimo' => 50,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Valla Contención 2m',
                'id_categoria' => 10,
                'unidad' => 'unidad',
                'stock_actual' => 30,
                'stock_minimo' => 40,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cinta Peligro x rollo',
                'id_categoria' => 10,
                'unidad' => 'rollo',
                'stock_actual' => 25,
                'stock_minimo' => 20,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Cartel Obra en Ejecución',
                'id_categoria' => 10,
                'unidad' => 'unidad',
                'stock_actual' => 8,
                'stock_minimo' => 15,
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'insumo' => 'Pintura Demarcación Vial x 20L',
                'id_categoria' => 10,
                'unidad' => 'balde',
                'stock_actual' => 20,
                'stock_minimo' => 15,
                'id_deposito' => 4,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}