<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumosSeeder extends Seeder
{
    /**
     * Resuelve el id de categoría a partir del nombre.
     * Si no existe, lanza una excepción para que lo notes antes de ejecutar en producción.
     */
    private function catId(array &$cache, string $nombre): int
    {
        $nombre = trim($nombre);
        if (!isset($cache[$nombre])) {
            $id = DB::table('categorias_insumos')
                ->whereRaw('TRIM(nombre) = ?', [$nombre])
                ->value('id');

            if (!$id) {
                throw new \RuntimeException("Categoría no encontrada: \"{$nombre}\". Creala en categorias_insumos antes de correr el seeder.");
            }
            $cache[$nombre] = $id;
        }
        return $cache[$nombre];
    }

    /** Convierte stock vacío / "-" a 0 */
    private function stock(mixed $v): int
    {
        if ($v === null || $v === '' || $v === '-') return 0;
        return (int) $v;
    }

    public function run(): void
    {
        // ----------------------------------------------------------------
        // ADVERTENCIA: esto borra y recrea todos los registros de insumos.
        // Deshabilitamos FK checks para poder truncar sin violar constraints.
        // ----------------------------------------------------------------
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('insumos')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        $catCache = [];
        $now = now();

        // Formato: [id, insumo, categoria_nombre, unidad, stock_actual, stock_minimo, id_deposito]
        $rows = [
            [1,   '1000x16 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 4,   6,   5],
            [2,   '1000x20 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 4,   6,   5],
            [3,   '12,16,5 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 11,  12,  5],
            [4,   '12,4,24 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 7,   6,   5],
            [5,   '12,4,28 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 2,   6,   5],
            [6,   '1300x24 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 1,   6,   5],
            [7,   '14,17,5 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 6,   6,   5],
            [8,   '1400x24 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 3,   6,   5],
            [9,   '16-4-28 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 0,   4,   5],
            [10,  '16-70-20 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 5,   4,   5],
            [11,  '16-9-30 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 4,   6,   5],
            [12,  '16,9,28 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 6,   6,   5],
            [13,  '17,5,25 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 16,  12,  5],
            [14,  '175-70-16 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 0,   8,   5],
            [15,  '175.70R14 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 0,   12,  5],
            [16,  'CUBIERTA 245-70-17,5',                             'CUBIERTAS',           'UNIDAD', 6,   4,   5],
            [17,  '18,4,34 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 4,   2,   5],
            [18,  '215-75-17.5 - CUBIERTAS',                          'CUBIERTAS',           'UNIDAD', 22,  18,  5],
            [19,  '19-5-24 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 6,   6,   5],
            [20,  '185.60R14 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 17,  12,  5],
            [21,  '215,80,r16 - CUBIERTAS',                           'CUBIERTAS',           'UNIDAD', 2,   6,   5],
            [22,  '215/65-16 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 0,   6,   5],
            [23,  '225-70-19.5 - CUBIERTAS',                          'CUBIERTAS',           'UNIDAD', 4,   6,   5],
            [24,  '225-75-15 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 1,   4,   5],
            [25,  '23-1-30 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 3,   4,   5],
            [26,  '23-5-25 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 0,   0,   5],
            [27,  '235-70-16 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 0,   8,   5],
            [28,  '235-75-15 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 5,   6,   5],
            [29,  '235/16 - CUBIERTAS',                               'CUBIERTAS',           'UNIDAD', 0,   6,   5],
            [30,  '245/70/16 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 2,   12,  5],
            [31,  '255-70-16 - CUBIERTAS',                            'CUBIERTAS',           'UNIDAD', 0,   3,   5],
            [32,  '650x16 - CUBIERTAS',                               'CUBIERTAS',           'UNIDAD', 0,   20,  5],
            [33,  '295,80,22,5 lisa - CUBIERTAS',                     'CUBIERTAS',           'UNIDAD', 18,  20,  5],
            [35,  '265-75-16 .- - CUBIERTAS',                         'CUBIERTAS',           'UNIDAD', 4,   20,  5],
            [36,  '275,80,22,5 c/taco - CUBIERTAS',                   'CUBIERTAS',           'UNIDAD', 0,   20,  5],
            [37,  '650x16 lisa - CUBIERTAS',                          'CUBIERTAS',           'UNIDAD', 0,   3,   5],
            [39,  '650x16 taco - CUBIERTAS',                          'CUBIERTAS',           'UNIDAD', 0,   3,   5],
            [40,  '700 X 16 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 1,   3,   5],
            [41,  '750 X 16 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 4,   3,   5],
            [42,  '750 X 18 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 2,   2,   5],
            [43,  '750 X 20 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 3,   2,   5],
            [44,  '900 x 20 - CUBIERTAS',                             'CUBIERTAS',           'UNIDAD', 0,   4,   5],
            [45,  '900/20 c/taco - CUBIERTAS',                        'CUBIERTAS',           'UNIDAD', 0,   6,   5],
            [46,  'CUBIERTA 205-65-15',                               'CUBIERTAS',           'UNIDAD', 0,   2,   5],
            [47,  'CUBIERTA 650 X 10',                                'CUBIERTAS',           'UNIDAD', 0,   4,   5],
            [48,  'CUBIERTA 12.5-80-18',                              'CUBIERTAS',           'UNIDAD', 8,   3,   5],
            [49,  'cubierta 1100 x 20',                               'CUBIERTAS',           'UNIDAD', 0,   4,   5],
            [50,  'CUBIERTA 14-9-24',                                 'CUBIERTAS',           'UNIDAD', 2,   12,  5],
            [52,  'CUBIERTA 205/ 65 -16.-',                           'CUBIERTAS',           'UNIDAD', 3,   4,   5],
            [53,  'CUBIERTAS 175-65-14',                              'CUBIERTAS',           'UNIDAD', 0,   4,   5],
            [54,  'cubiertas 185-65-15',                              'CUBIERTAS',           'UNIDAD', 6,   2,   5],
            [55,  'CUBIERTA 225-70-17',                               'CUBIERTAS',           'UNIDAD', 4,   4,   5],
            [56,  'CUBIERTA 195-70-15',                               'CUBIERTAS',           'UNIDAD', 2,   4,   5],
            [57,  'cubierta 4.10/3.50 k358',                          'CUBIERTAS',           'UNIDAD', 0,   10,  5],
            [58,  'CUBIERTA 215-70-17,5',                             'CUBIERTAS',           'UNIDAD', 1,   10,  5],
            [59,  'CUBIERTA 225-65-16',                               'CUBIERTAS',           'UNIDAD', 7,   2,   5],
            [60,  'CUBIERTA 10-16,5',                                 'CUBIERTAS',           'UNIDAD', 12,  4,   5],
            [61,  '18-4-38 - CUBIERTAS',                              'CUBIERTAS',           'UNIDAD', 0,   1,   5],
            [62,  'AEROSOLES BLANCO',                                 'PINTURA',             'UNIDAD', 40,  30,  3],
            [63,  'AEROSOLES NEGRO',                                  'PINTURA',             'UNIDAD', 22,  20,  3],
            [64,  'AGUARRAS X 200 LTS',                               'PINTURA',             'UNIDAD', 1,   20,  3],
            [65,  'ANTIOXIDO X 4 LTS',                                'PINTURA',             'UNIDAD', 85,  20,  3],
            [66,  'PINTURA ASFALTICA x 20 LTS',                       'PINTURA',             'UNIDAD', 0,   10,  3],
            [67,  'PINTURA ASFALTICA x 4 LTS',                        'PINTURA',             'UNIDAD', 0,   30,  3],
            [68,  'PINTURA ASFALTICA X10 LTS',                        'PINTURA',             'UNIDAD', 28,  30,  3],
            [69,  'BANDEJA PARA RODILLOS',                            'PINTURA',             'UNIDAD', 0,   2,   3],
            [70,  'CETOL X 10 LTS',                                   'PINTURA',             'UNIDAD', 0,   2,   3],
            [71,  'CETOL ROBLE X 4 LTS',                              'PINTURA',             'UNIDAD', 29,  2,   3],
            [72,  'ENDUIDO 30 KG',                                    'PINTURA',             'UNIDAD', 0,   2,   3],
            [73,  'ENDUIDO X 10 KG',                                  'PINTURA',             'UNIDAD', 0,   30,  3],
            [74,  'ENDUIDO X 4 KG',                                   'PINTURA',             'UNIDAD', 0,   10,  3],
            [75,  'ENDUIDO X 1 KG',                                   'PINTURA',             'UNIDAD', 0,   10,  3],
            [76,  'ADHESIVO X 1 KG',                                  'PINTURA',             'UNIDAD', 3,   1,   3],
            [77,  'COLA X 4LT',                                       'PINTURA',             'UNIDAD', 4,   1,   3],
            [78,  'ESMALTE CONVERTIDOR (HIERRO ANTIGUO) X 4LTS',      'PINTURA',             'UNIDAD', 39,  30,  3],
            [79,  'LIJAS X 120',                                      'PINTURA',             'UNIDAD', 0,   10,  3],
            [80,  'ESPATULAS DE CHAPA',                               'PINTURA',             'UNIDAD', 0,   10,  3],
            [81,  'LATEX AMARILLO X 20 LTS',                          'PINTURA',             'UNIDAD', 28,  10,  3],
            [82,  'FONDO BLANCO PARA MADERA X 4 LTS',                 'PINTURA',             'UNIDAD', 30,  10,  3],
            [83,  'LATEX AMARILLO X 10 LTS',                          'PINTURA',             'UNIDAD', 0,   10,  3],
            [84,  'LATEX AZUL TRAFUL x 10 LTS',                       'PINTURA',             'UNIDAD', 0,   10,  3],
            [85,  'LATEX AMARILLO X 4 LTS',                           'PINTURA',             'UNIDAD', 0,   10,  3],
            [86,  'LATEX AZUL TRAFUL x 20 LTS',                       'PINTURA',             'UNIDAD', 0,   50,  3],
            [87,  'LATEX AZUL x 10 LTS',                              'PINTURA',             'UNIDAD', 0,   10,  3],
            [88,  'LATEX AZUL TRAFUL x 4 LTS',                        'PINTURA',             'UNIDAD', 20,  50,  3],
            [89,  'LATEX AZUL x 20 LTS',                              'PINTURA',             'UNIDAD', 0,   30,  3],
            [90,  'LATEX BLANCO X 10 LTS',                            'PINTURA',             'UNIDAD', 39,  50,  3],
            [91,  'LATEX AZUL x 4 LTS',                               'PINTURA',             'UNIDAD', 0,   10,  3],
            [92,  'LATEX BLANCO X 20 LTS',                            'PINTURA',             'UNIDAD', 10,  10,  3],
            [93,  'LATEX GRIS CEMENTO X 10 LTS',                      'PINTURA',             'UNIDAD', 47,  20,  3],
            [94,  'LATEX BLANCO X 4 LTS',                             'PINTURA',             'UNIDAD', 31,  30,  3],
            [95,  'LATEX MARRON X 4 LTS',                             'PINTURA',             'UNIDAD', 0,   30,  3],
            [96,  'LATEX MARRON X 20 LTS',                            'PINTURA',             'UNIDAD', 0,   20,  3],
            [97,  'LATEX NEGRO X 10 LTS',                             'PINTURA',             'UNIDAD', 0,   10,  3],
            [98,  'SINTETICO NEGRO SATINADO X 4LT',                   'PINTURA',             'UNIDAD', 76,  10,  3],
            [99,  'LATEX GRIS CEMENTO X 20 LTS',                      'PINTURA',             'UNIDAD', 0,   10,  3],
            [100, 'LATEX GRIS CEMENTO X 4 LTS',                       'PINTURA',             'UNIDAD', 84,  20,  3],
            [101, 'LATEX NEGRO X 20 LTS',                             'PINTURA',             'UNIDAD', 0,   10,  3],
            [102, 'LATEX MARRON X 10 LTS',                            'PINTURA',             'UNIDAD', 0,   10,  3],
            [103, 'LATEX ROJO BERMELLON X 10 LTS',                    'PINTURA',             'UNIDAD', 0,   10,  3],
            [104, 'LATEX NEGRO X 4 LTS',                              'PINTURA',             'UNIDAD', 27,  10,  3],
            [105, 'LATEX ROJO BERMELLON X 20 LTS',                    'PINTURA',             'UNIDAD', 0,   10,  3],
            [106, 'LATEX VERDE FORESTA X 10 LTS',                     'PINTURA',             'UNIDAD', 0,   10,  3],
            [107, 'LATEX ROJO BERMELLON X 4 LTS',                     'PINTURA',             'UNIDAD', 43,  10,  3],
            [108, 'LATEX VERDE FORESTA X 20 LTS',                     'PINTURA',             'UNIDAD', 0,   10,  3],
            [109, 'LATEX VERDE SAFARI X 10 LTS',                      'PINTURA',             'UNIDAD', 0,   10,  3],
            [110, 'LATEX VERDE FORESTA X 4 LTS',                      'PINTURA',             'UNIDAD', 0,   10,  3],
            [111, 'LATEX VERDE SAFARI X 20 LTS',                      'PINTURA',             'UNIDAD', 0,   20,  3],
            [112, 'LATEX VERDE SAFARI X 4 LTS',                       'PINTURA',             'UNIDAD', 0,   20,  3],
            [113, 'LATEX VIOLETA X 10 LTS',                           'PINTURA',             'UNIDAD', 0,   50,  3],
            [114, 'LATEX VIOLETA X 20 LTS',                           'PINTURA',             'UNIDAD', 0,   50,  3],
            [115, 'RODILLO 8 CM',                                     'PINTURA',             'UNIDAD', 0,   30,  3],
            [116, 'SINTETICO AZUL TRAFUL X 10 LTS',                   'PINTURA',             'UNIDAD', 0,   30,  3],
            [117, 'PINCEL N 30',                                      'PINTURA',             'UNIDAD', 118, 30,  3],
            [118, 'PINCEL N 25',                                      'PINTURA',             'UNIDAD', 0,   30,  3],
            [119, 'SINTETICO LILA X 4 LT',                            'PINTURA',             'UNIDAD', 2,   1,   3],
            [120, 'SINTETICO AMARILLO VIAL X 20 LT',                  'PINTURA',             'UNIDAD', 50,  5,   3],
            [121, 'SINTETICO AMARILLO X 4 LTS',                       'PINTURA',             'UNIDAD', 32,  30,  3],
            [122, 'SINTETICO AMARILLO X 10 LTS',                      'PINTURA',             'UNIDAD', 2,   30,  3],
            [123, 'SINTETICO AZUL TRAFUL X 4 LTS',                    'PINTURA',             'UNIDAD', 0,   30,  3],
            [124, 'SINTETICO AZUL X 10 LTS',                          'PINTURA',             'UNIDAD', 0,   30,  3],
            [125, 'SINTETICO BEIGE X 10 LTS',                         'PINTURA',             'UNIDAD', 0,   30,  3],
            [126, 'SINTETICO AZUL X 4 LTS',                           'PINTURA',             'UNIDAD', 0,   30,  3],
            [127, 'SINTETICO BEIGE X 4 LTS',                          'PINTURA',             'UNIDAD', 1,   50,  3],
            [128, 'SINTETICO BERMELLON X 10 LTS',                     'PINTURA',             'UNIDAD', 0,   50,  3],
            [129, 'SINTETICO VIOLETA X 10 LTS',                       'PINTURA',             'UNIDAD', 0,   50,  3],
            [130, 'PINCEL N 10',                                      'PINTURA',             'UNIDAD', 15,  10,  3],
            [131, 'SINTETICO NEGRO SATINADO X 20 LT',                 'PINTURA',             'UNIDAD', 0,   50,  3],
            [132, 'SINTETICO NEGRO SATINADO X 10 LT',                 'PINTURA',             'UNIDAD', 0,   10,  3],
            [134, 'SINTETICO MARRON X 10 LTS',                        'PINTURA',             'UNIDAD', 0,   50,  3],
            [135, 'SINTETICO NEGRO BRILLANTE X  10 LT',               'PINTURA',             'UNIDAD', 0,   50,  3],
            [136, 'SINTETICO VIOLETA X 4 LTS',                        'PINTURA',             'UNIDAD', 0,   10,  3],
            [137, 'SINTETICO BERMELLON X 4 LTS',                      'PINTURA',             'UNIDAD', 24,  50,  3],
            [138, 'SINTETICO BLANCO BRILLANTE X 10 LTS',              'PINTURA',             'UNIDAD', 0,   10,  3],
            [139, 'SINTETICO BLANCO BRILLANTE X 20 LTS',              'PINTURA',             'UNIDAD', 1,   10,  3],
            [140, 'SINTETICO GRIS CEMENTO X 4 LTS',                   'PINTURA',             'UNIDAD', 0,   10,  3],
            [141, 'SINTETICO GRIS ESPECIAL X 10 LTS',                 'PINTURA',             'UNIDAD', 0,   10,  3],
            [142, 'SINTETICO BLANCO BRILLANTE X 4LTS',                'PINTURA',             'UNIDAD', 22,  10,  3],
            [143, 'SINTETICO CELESTE X 10 LTS',                       'PINTURA',             'UNIDAD', 0,   10,  3],
            [144, 'SINTETICO MARRON X 4 LTS',                         'PINTURA',             'UNIDAD', 8,   50,  3],
            [145, 'SINTETICO CELESTE X 4 LTS',                        'PINTURA',             'UNIDAD', 12,  10,  3],
            [146, 'SINTETICO GRIS CEMENTO X 10 LTS',                  'PINTURA',             'UNIDAD', 0,   10,  3],
            [147, 'SINTETICO NARANJA X 4 LTS',                        'PINTURA',             'UNIDAD', 35,  50,  3],
            [148, 'SINTETICO NARANJA X 10 LTS',                       'PINTURA',             'UNIDAD', 0,   30,  3],
            [149, 'PINCEL N 15',                                      'PINTURA',             'UNIDAD', 21,  50,  3],
            [150, 'SINTETICO GRIS ESPECIAL X 4 LTS',                  'PINTURA',             'UNIDAD', 0,   15,  3],
            [151, 'SINTETICO GRIS X 10 LTS',                          'PINTURA',             'UNIDAD', 0,   100, 3],
            [152, 'SINTETICO GRIS X 4LTS',                            'PINTURA',             'UNIDAD', 0,   15,  3],
            [153, 'SINTETICO VERDE INGLES X 4 LT',                    'PINTURA',             'UNIDAD', 38,  5,   3],
            [154, 'PINCEL N 20',                                      'PINTURA',             'UNIDAD', 96,  15,  3],
            [155, 'RODILLO 10 CM',                                    'PINTURA',             'UNIDAD', 0,   150, 3],
            [156, 'RODILLO 17 CM',                                    'PINTURA',             'UNIDAD', 0,   50,  3],
            [157, 'PISO DEPORTIVO DE ACRILICO X 20 LT',               'PINTURA',             'UNIDAD', 59,  10,  3],
            [158, 'PINTURA PISO GRIS DE 20 KG',                       'PINTURA',             'UNIDAD', 56,  15,  3],
            [159, 'RODILLO 22 CM',                                    'PINTURA',             'UNIDAD', 63,  15,  3],
            [160, 'PINTURA PISO VERDE DE 20KG',                       'PINTURA',             'UNIDAD', 14,  50,  3],
            [161, 'PINTURA PISO VERDE DE 10 KG',                      'PINTURA',             'UNIDAD', 0,   50,  3],
            [162, 'PAN DE BREA X 20 KG',                              'PINTURA',             'UNIDAD', 0,   50,  3],
            [163, 'PINCELETA',                                        'PINTURA',             'UNIDAD', 77,  20,  3],
            [164, 'PINCEL N 40',                                      'PINTURA',             'UNIDAD', 0,   100, 3],
            [165, 'RODILLO 5 CM',                                     'PINTURA',             'UNIDAD', 0,   50,  3],
            [166, 'PINTURA PISO GRIS DE 25KG',                        'PINTURA',             'UNIDAD', 0,   15,  3],
            [167, 'SINTETICO NEGRO BRILLANTE X 4 LT',                 'PINTURA',             'UNIDAD', 15,  50,  3],
            [168, 'SINTETICO VERDE CLARO X 4 LT',                     'PINTURA',             'UNIDAD', 33,  2,   3],
            [169, 'LIJAS X 60',                                       'PINTURA',             'UNIDAD', 0,   10,  3],
            [170, 'LIJAS X 100',                                      'PINTURA',             'UNIDAD', 0,   20,  3],
            [171, 'LIJAS X 120',                                      'PINTURA',             'UNIDAD', 46,  20,  3],
            [172, 'LIJAS X 80',                                       'PINTURA',             'UNIDAD', 0,   50,  3],
            [173, 'MEMBRANA EN PASTA X 20 LT',                        'PINTURA',             'UNIDAD', 4,   50,  3],
            [174, 'MEMBRANA LIQUIDA X 20 LT',                         'PINTURA',             'UNIDAD', 18,  5,   3],
            [175, 'LIJAS X 50',                                       'PINTURA',             'UNIDAD', 0,   30,  3],
            [176, 'LATEX VIOLETA X 4 LTS',                            'PINTURA',             'UNIDAD', 34,  2,   3],
            [177, 'SINTETICO NEGRO BRILLANTE X 20 LT',                'PINTURA',             'UNIDAD', 0,   2,   3],
            [178, 'LIJAS X 150',                                      'PINTURA',             'UNIDAD', 79,  3,   3],
            [179, 'LIJAS X 180',                                      'PINTURA',             'UNIDAD', 1,   20,  3],
            [180, 'LIJAS X 220',                                      'PINTURA',             'UNIDAD', 100, 20,  3],
            [181, 'LIJAS X 240',                                      'PINTURA',             'UNIDAD', 95,  20,  3],
            [182, 'LIJAS X 500',                                      'PINTURA',             'UNIDAD', 69,  20,  3],
            [183, 'LIJAS X 2500',                                     'PINTURA',             'UNIDAD', 100, 20,  3],
            [184, 'TINNER',                                           'PINTURA',             'LITROS', 420, 0,   3],
            [186, 'ACEITE 5W- 40',                                    'ACEITE',              'TAMBOR', 1,   3,   9],
            [187, 'ACEITE 5W -30 AC 3',                               'ACEITE',              'TAMBOR', 3,   3,   9],
            [188, 'ACEITE 10W-40',                                    'ACEITE',              'TAMBOR', 3,   10,  9],
            [189, 'ACEITE 15 W 40',                                   'ACEITE',              'TAMBOR', 2,   4,   9],
            [190, 'ACEITE 15W 40 DE 1000 LT',                         'ACEITE',              'TAMBOR', 2,   25,  9],
            [191, 'ACEITE 20 W 50',                                   'ACEITE',              'TAMBOR', 3,   5,   9],
            [192, 'ACEITE 80 W 90',                                   'ACEITE',              'TAMBOR', 1,   5,   9],
            [193, 'ACEITE ATF',                                       'ACEITE',              'TAMBOR', 3,   2,   9],
            [194, 'ACEITE ATF 295',                                   'ACEITE',              'TAMBOR', 2,   1,   9],
            [195, 'ACEITE H 68',                                      'ACEITE',              'TAMBOR', 35,  3,   9],
            [196, 'ACEITE H 32',                                      'ACEITE',              'TAMBOR', 1,   0,   9],
            [197, 'ACEITE H 46',                                      'ACEITE',              'TAMBOR', 1,   0,   9],
            [198, 'GRASA DE LITIO',                                   'ACEITE',              'TAMBOR', 2,   0,   9],
            [199, 'UREA',                                             'ACEITE',              'LITROS', 300, 0,   9],
            [200, 'ACEITE 2T PARA ECHO',                              'ACEITE',              'TAMBOR', 1,   0,   9],
            [201, 'BATERIA 12 X 45',                                  'BATERIAS',            'UNIDAD', 0,   0,   10],
            [202, 'BATERIA 12 X 65',                                  'BATERIAS',            'UNIDAD', 0,   0,   10],
            [203, 'BATERIA 12 X 50',                                  'BATERIAS',            'UNIDAD', 0,   0,   10],
            [204, 'BATERIA 12 X 75',                                  'BATERIAS',            'UNIDAD', 1,   0,   10],
            [205, 'BATERIA 12 X 90',                                  'BATERIAS',            'UNIDAD', 0,   0,   10],
            [206, 'BATERIA 12 X 110',                                 'BATERIAS',            'UNIDAD', 1,   0,   10],
            [207, 'BATERIA 12 X 180',                                 'BATERIAS',            'UNIDAD', 0,   0,   10],
            [208, 'BATERIA 12 X 200',                                 'BATERIAS',            'UNIDAD', 0,   0,   10],
            [209, 'ABRAZADERA DN 100 CLASE 3 - DE 1/2',               'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [210, 'ABRAZADERAS DE 100x1/2',                           'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [211, 'ABRAZADERAS DE 200x1/2',                           'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [212, 'ABRAZADERAS DE 250x1/2',                           'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [213, 'ABRAZADERAS DE 300x1/2',                           'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [214, 'ABRAZADERAS DE 350',                               'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [215, 'ABRAZADERAS DE 60x1/2',                            'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [216, 'ABRAZADERAS DE 75x1/2',                            'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [217, 'ABRAZADERAS DE150x1/2',                            'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [218, 'ABRAZADERAS PVC DE 75',                            'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [219, 'ABRAZADERA DE PVC 160 C/REDUCCION A 1/2',          'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [220, 'ABRAZADERA C/BULONES 0,75 x 1"',                   'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [221, 'ABRAZADERA C/BULONES 0,75 x 1/2',                  'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [222, 'ABRAZADERA C/BULONES 0,75 x 3/4',                  'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [223, 'ABRAZADERA C/BULONES 110 x 1"',                    'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [224, 'JUNTAMAS AC-C5-7-75',                              'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [225, 'ABRAZADERA C/BULONES 110 x 1/2',                   'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [226, 'ABRAZADERA DE HIERRO X 75',                        'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [227, 'ABRAZADERA C/BULONES 110 x 3/4',                   'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [228, 'ABRAZADERA DE HIERRO X 100',                       'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [229, 'ABRAZADERAS DN 75 CLASE 3 - DE 1/2',               'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [230, 'ABRAZADERA DN 100 CLASE 3 - DE 1/2',               'AGUA CORRIENTE',      'UNIDAD', 0,   30,  6],
            [231, 'ABRAZADERA DN 100 CLASE 3 - DE 3/4',               'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [232, 'ABRAZADERA ESTRIBO 150 X 3/4',                     'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [233, 'ABRAZADERA ESTRIBO 150 X 1/2',                     'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [234, 'ABRAZADERA DN 75 CLASE 3 - DE 3/4',                'AGUA CORRIENTE',      'UNIDAD', 0,   30,  6],
            [235, 'CAÑO 75  X 2.2 JUNTA ELASTICA CLASE 6',            'AGUA CORRIENTE',      'UNIDAD', 0,   2,   6],
            [236, 'ACCESORIO HEMBRA ROSCA ESPIGA 1/2',                'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [237, 'ACCESORIO MACHO ROSCA ESPIGA 1/2',                 'AGUA CORRIENTE',      'UNIDAD', 0,   2,   6],
            [238, 'CAÑO 75  X 3.6 JUNTA ELASTICA CLASE 10',           'AGUA CORRIENTE',      'UNIDAD', 0,   30,  13],
            [239, 'CAÑO 110 X 2.2 JUNTA ELASTICA CLASE 6',            'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [240, 'CAÑO POLIETILENO 3/4"',                            'AGUA CORRIENTE',      'UNIDAD', 0,   2,   13],
            [241, 'CAÑO 160 X 3.6 JUNTA ELASTICA CLASE 10',           'AGUA CORRIENTE',      'UNIDAD', 0,   2,   13],
            [242, 'CAÑO POLIETILENO 1 1/2"',                          'AGUA CORRIENTE',      'UNIDAD', 0,   2,   13],
            [243, 'CAÑO 160 X 2.2 JUNTA ELASTICA CLASE 6',            'AGUA CORRIENTE',      'UNIDAD', 0,   2,   13],
            [244, 'CAÑO 110 X 3.6 JUNTA ELASTICA CLASE 10',           'AGUA CORRIENTE',      'UNIDAD', 0,   5,   13],
            [245, 'CAÑO POLIETILENO 1"',                              'AGUA CORRIENTE',      'UNIDAD', 0,   5,   13],
            [246, 'CAÑO POLIETILENO 1/2"',                            'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [247, 'CONECTOR BLANCO NYLON CONO ESPIGA 3/4',             'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [248, 'CAÑO POLIETILENO 2"',                              'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [249, 'CAÑO VERDES P/POZO X 6MTRS',                       'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [250, 'CRUZ PVC DE 75X75 CL10',                           'AGUA CORRIENTE',      'UNIDAD', 0,   10,  13],
            [251, 'CONECTOR NEGRO ESPIGA C/CONO 1/2',                 'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [252, 'CONECTOR NEGRO ESPIGA C/CONO 3/4',                 'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [253, 'CURVA A 90 JTA .ELASTICA 090',                     'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [254, 'CURVA A 45 JTA .ELASTICA 110',                     'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [255, 'CURVA A 90 JTA .ELASTICA 075',                     'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [256, 'CURVA A 90 JTA .ELASTICA 110',                     'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [257, 'ESPIGA R/MACHO BRONCE 1/2"',                       'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [258, 'ESPIGA R/MACHO BRONCE 1"',                         'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [259, 'JUNTAMAS 500 A/C',                                 'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [260, 'FERULAS DE 19 (3/4)',                               'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [261, 'JUNTAMAS SM C/5-7 100 PVC',                        'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [262, 'JUNTAMAS SM C/5-7 075 PVC',                        'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [263, 'ESPIEGA CON ROSCA MACHO 1" PVC',                   'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [264, 'ESPIGA CON ROSCA HERMBRA 3/4 PVC',                 'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [265, 'JUNTAMAS C/5 075 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [266, 'ESPIGA CON ROSCA MACHO 3/4 PVC',                   'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [267, 'JUNTAMAS C/5 100 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [268, 'FERULAS DE 13 (1/2)',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [269, 'JUNTAMAS C/5 125 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [270, 'JUNTAMAS C/5 150 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [271, 'JUNTAMAS DE PLASTICO DN-100 CLASE 5-7',            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [272, 'JUNTAMAS PLASTICA AC 175 3-5',                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [273, 'JUNTAMAS DE 3/4 PVC',                              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [274, 'JUNTAMAS DE 1" PVC',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [275, 'JUANTAMAS PVC de 63',                              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [276, 'JUNTAMAS PLASTICA DN 100 CLASE 7-10',              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [277, 'JUNTAMAS DE PVC DE 90',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [278, 'JUNTAMAS DE PLASTICO DN-75 CLASE 5-7',             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [279, 'JUNTAMAS C/5 200 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [280, 'JUNTAMAS C/5 300 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [281, 'JUNTAMAS C/5 250 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [282, 'JUNTAMAS C/5-7 300 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [283, 'JUNTAMAS C/5-7 350 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [284, 'JUNTAMAS C/5 350 PVC',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [285, 'JUNTAMAS C/5-7 150 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [286, 'JUNTAMAS PLASTICA DN-150 CLASE 7-10',              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [287, 'JUNTAMAS C/5-7 060 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [288, 'JUNTAMAS C/5-7 250 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [289, 'JUNTAMAS DE 1/2 PVC',                              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [290, 'JUNTAMAS C/5 300 x PVC 075',                       'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [291, 'JUNTAMAS PVC EXTRA LARGA DE 75',                   'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [292, 'JUNTAMAS DE PLASTICO DN-100 CLASE 3',              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [293, 'JUNTAMAS C/5-7 125 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [294, 'JUNTAMAS C/5-7 200 PVC',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [295, 'JUNTAMAS SM C/5-7 060 PVC',                        'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [296, 'JUNTAMAS AC-C5-75',                                'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [297, 'JUNTAMAS AC-C5-100',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [298, 'JUNTAMAS P/PVC 160',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [299, 'JUNTAMAS AC-C5-125',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [300, 'JUNTAMAS PVC DE 200',                              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [301, 'JUNTAMAS PLASTICA 250',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [302, 'JUNTAMAS DE PVC 350 EXTRA LARGA',                  'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [303, 'JUNTAMAS SM C/5-7 150 PVC',                        'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [304, 'JUNTAMAS SM C/5-7 250 PVC',                        'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [305, 'JUNTAMAS PLASTICA P/PVC 140',                      'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [306, 'JUNTAMAS DE PVC 110',                              'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [307, 'JUNTAMAS AC-C5-200',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [308, 'JUNTAMAS AC-C5-300',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [309, 'JUNTAMAS AC-C5-250',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [310, 'JUNTAMAS PLASTICA DE 315 EXTRA LARGA',             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [311, 'JUNTAMAS AC-C5-150',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [312, 'ESPIGA R/MACHO BRONCE 3/4"',                       'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [313, 'JUANTAMAS PLASTICA DE 75 P/PVC',                   'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [314, 'JUNTAMAS AC-C5-350',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [315, 'JUNTAMAS AC-C5-7-100',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [316, 'JUNTAMAS AC-C5-7-125',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [317, 'JUNTAMAS AC-C5-7-150',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [318, 'JUNTAMAS AC-C5-7-200',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [319, 'JUNTAMAS AC-C5-7-250',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [320, 'JUNTAMAS AC-C5-7-300',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [321, 'JUNTAMAS AC-C5-7-350',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [322, 'JUNTAMAS AC-C5-7-450',                             'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [323, 'JUATAMAS MR 1/2 LARGO',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [324, 'JUNTAMAS MR 3/4 LARGO',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [325, 'JUNTAMAS -AC-C5-7-300 C/SALIDA',                   'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [326, 'JUNTAMAS H F 3/4',                                 'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [327, 'LLAVE ESFERICA DE 1/2',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [328, 'LLAVE ESFERICA DE 3/4',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [329, 'LLAVE C/ROSCA 3"',                                 'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [330, 'LLAVE MAESTRA DE BRONCE DE (1/2)',                  'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [331, 'LLAVE MAESTRA DE BRONCE DE (3/4)',                  'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [332, 'RAMAL TEE DIAMANTADO 140 PVC',                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [333, 'RAMAL TEE DIAMANTADO 160 PVC',                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [334, 'REDUCCION JTA.ELASTICA 160x110',                   'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [335, 'REDUCCION PVC DE 110X75',                          'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [336, 'REDUCCION PVC DE 110X75 CL10',                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [337, 'REDUCCION PVC DE 90x75',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [338, 'REDUCCIONES 140 x 110',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [339, 'REDUCCIONES 160 x 110',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [340, 'TAPA HEMBRA DE 75',                                'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [341, 'TAPA HEMBRA DE 110',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [342, 'TAPA HEMBRA DE 160',                               'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [343, 'TAPON DE 1/2',                                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [344, 'TAPON DE 3/4',                                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [345, 'TAPONES PVC DE 75 CL10',                           'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [346, 'TEE HF DE 75',                                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [347, 'TEE INYECTADA PVC DE 160x160',                     'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [348, 'TEE INYECTADA PVC DE 160x75',                      'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [349, 'TEE PVC DE 75X75 CL10',                            'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [350, 'TRANSICION PVC DE 110 x 110',                      'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [351, 'TRANSICION PVC DE 75',                             'AGUA CORRIENTE',      'UNIDAD', 0,   20,  6],
            [352, 'TUBO DE PVC DE 75 x 6 MTS',                        'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [353, 'VALVULA ESCLUSA PVC DE 160',                       'AGUA CORRIENTE',      'UNIDAD', 0,   10,  6],
            [354, 'VALVULA ESCLUSA PVC DE 75',                        'AGUA CORRIENTE',      'UNIDAD', 0,   0,   6],
            [355, 'CAÑO BLANCO 110 X 2MM X4M',                        'OBRAS SANITARIAS',    'UNIDAD', 0,   0,   7],
            [356, 'CAÑO BLANCO 110 X 3.2MM X6M',                      'OBRAS SANITARIAS',    'UNIDAD', 0,   0,   7],
            [357, 'CAÑO BLANCO DE 160',                               'OBRAS SANITARIAS',    'UNIDAD', 0,   5,   7],
            [358, 'CAÑO BLANCO DE 200',                               'OBRAS SANITARIAS',    'UNIDAD', 0,   5,   7],
            [359, 'ACOPLE RAPIDO DE ALUMINIO 3"',                     'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [360, 'ACOPLE RAPIDO DE PVC DE 3"',                       'OBRAS SANITARIAS',    'UNIDAD', 0,   5,   7],
            [361, 'ACOPLE RAPIDO DE PVC DE 4" C/SALIDA ESPIGA DE 3"', 'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [362, 'CUPLA DE REDUCCION 140 X110',                      'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [363, 'CUPLA DE REDUCCION 160 X110',                      'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [364, 'CUPLAS 110',                                       'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [365, 'CURVA DE 160 X 160',                               'OBRAS SANITARIAS',    'UNIDAD', 0,   30,  7],
            [366, 'CURVA DE 75',                                      'OBRAS SANITARIAS',    'UNIDAD', 0,   20,  7],
            [367, 'CURVA DE 90',                                      'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [368, 'CURVAS 45 X 110',                                  'OBRAS SANITARIAS',    'UNIDAD', 0,   10,  7],
            [369, 'REDUCCION 160-110',                                'OBRAS SANITARIAS',    'UNIDAD', 0,   3,   7],
            [370, 'ALAMBRE DE FARDO',                                 'MANTENIMIENTO',       'UNIDAD', 19,  3,   1],
            [371, 'ALAMBRE GALVANIZADO NUMERO 13',                    'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [372, 'ARRANCA MOTORES',                                  'MANTENIMIENTO',       'UNIDAD', 9,   5,   1],
            [373, 'BALDES DE ALBAÑIL',                                'MANTENIMIENTO',       'UNIDAD', 3,   30,  1],
            [374, 'BOLSA DE ESTOPA',                                  'MANTENIMIENTO',       'UNIDAD', 34,  30,  1],
            [375, 'Candado Nª 30',                                    'MANTENIMIENTO',       'UNIDAD', 0,   2,   1],
            [376, 'Candado Nª 40',                                    'MANTENIMIENTO',       'UNIDAD', 0,   2,   1],
            [377, 'Candado Nª 50',                                    'MANTENIMIENTO',       'UNIDAD', 0,   100, 1],
            [378, 'CARRETILLA DUROLL 70',                             'MANTENIMIENTO',       'UNIDAD', 20,  10,  1],
            [379, 'CANILLA PLASTICA DE 1/2',                          'MANTENIMIENTO',       'UNIDAD', 60,  100, 1],
            [380, 'CANILLA PLASTICA DE 3/4',                          'MANTENIMIENTO',       'UNIDAD', 21,  100, 1],
            [381, 'CHOCLAS',                                          'MANTENIMIENTO',       'UNIDAD', 18,  20,  1],
            [382, 'CIANO',                                            'MANTENIMIENTO',       'UNIDAD', 1,   2,   1],
            [383, 'CINTA AISLADORA',                                  'MANTENIMIENTO',       'UNIDAD', 97,  2,   1],
            [384, 'CINTA METRICA X 5MTS',                             'MANTENIMIENTO',       'UNIDAD', 9,   2,   1],
            [385, 'CINTA PAPEL 24mm',                                 'MANTENIMIENTO',       'UNIDAD', 114, 5,   1],
            [386, 'CINTA PAPEL 48mm',                                 'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [387, 'CLAVOS DE GANCHO',                                 'MANTENIMIENTO',       'UNIDAD', 15,  10,  1],
            [388, 'COLA ADHESIVA X 4KG',                              'MANTENIMIENTO',       'UNIDAD', 5,   1,   1],
            [389, 'COLA ADHESIVO X 1KG',                              'MANTENIMIENTO',       'UNIDAD', 3,   0,   1],
            [390, 'COLA ADHESIVO X 6KG',                              'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [391, 'CORTA FIERROS',                                    'MANTENIMIENTO',       'UNIDAD', 4,   0,   1],
            [392, 'CUCHARAS DE ALBAÑIL',                              'MANTENIMIENTO',       'UNIDAD', 5,   10,  1],
            [393, 'CUTTER',                                           'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [394, 'DESENGRASANTE X 5 LT',                             'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [395, 'DISCO CORTE 115"',                                 'MANTENIMIENTO',       'UNIDAD', 145, 50,  1],
            [396, 'DISCO CORTE 9"',                                   'MANTENIMIENTO',       'UNIDAD', 76,  30,  1],
            [397, 'DISCO DESBASTE 115"',                              'MANTENIMIENTO',       'UNIDAD', 4,   30,  1],
            [398, 'DISCO DESBASTE 9"',                                'MANTENIMIENTO',       'UNIDAD', 70,  30,  1],
            [399, 'DISCO WIDIA 115"',                                 'MANTENIMIENTO',       'UNIDAD', 24,  30,  1],
            [400, 'DISCO WIDIA 9"',                                   'MANTENIMIENTO',       'UNIDAD', 24,  30,  1],
            [401, 'DISCO FLAP',                                       'MANTENIMIENTO',       'UNIDAD', 460, 30,  1],
            [402, 'ESCALERA',                                         'MANTENIMIENTO',       'UNIDAD', 2,   10,  1],
            [403, 'ESCUADRA',                                         'MANTENIMIENTO',       'UNIDAD', 15,  0,   1],
            [404, 'FAJA LUMBAR',                                      'MANTENIMIENTO',       'UNIDAD', 3,   24,  1],
            [405, 'FASTIX ALTA TEMPERATURA',                          'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [406, 'FASTIX COMUN',                                     'MANTENIMIENTO',       'UNIDAD', 4,   2,   1],
            [407, 'FILTRO DE ALBAÑIL',                                'MANTENIMIENTO',       'UNIDAD', 3,   5,   1],
            [408, 'FRATACHO DE MADERA',                               'MANTENIMIENTO',       'UNIDAD', 28,  24,  1],
            [409, 'GRINFA',                                           'MANTENIMIENTO',       'UNIDAD', 0,   24,  1],
            [410, 'GUANTES ACEITERA',                                 'MANTENIMIENTO',       'UNIDAD', 20,  50,  1],
            [411, 'GUANTES DESCARNE',                                 'MANTENIMIENTO',       'UNIDAD', 20,  10,  1],
            [412, 'GUANTES DIELECTRICOS',                             'MANTENIMIENTO',       'UNIDAD', 147, 5,   1],
            [413, 'GUANTES MOTEADOS',                                 'MANTENIMIENTO',       'UNIDAD', 408, 5,   1],
            [414, 'GUANTES NITRILOTELA ( S.E )',                      'MANTENIMIENTO',       'UNIDAD', 0,   5,   1],
            [415, 'GUANTES OBRAS SANITARIAS LARGOS',                  'MANTENIMIENTO',       'UNIDAD', 32,  30,  1],
            [416, 'GUANTES OBRAS SANITARIAS CORTOS',                  'MANTENIMIENTO',       'UNIDAD', 18,  30,  1],
            [417, 'GUANTES VAQUETA',                                  'MANTENIMIENTO',       'UNIDAD', 67,  130, 1],
            [418, 'HOJAS SIERRA 18D',                                 'MANTENIMIENTO',       'UNIDAD', 19,  10,  1],
            [419, 'HORQUILLAS',                                       'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [420, 'LAPIZ CARPINTERO',                                 'MANTENIMIENTO',       'UNIDAD', 2,   0,   1],
            [421, 'LINTERNAS',                                        'MANTENIMIENTO',       'UNIDAD', 1,   1,   1],
            [422, 'LIQUIDO DE FRENO X 1L',                            'MANTENIMIENTO',       'UNIDAD', 37,  1,   1],
            [423, 'LIQUIDO DE FRENO X 200CM',                         'MANTENIMIENTO',       'UNIDAD', 7,   5,   1],
            [424, 'LLANAS DE PLASTICO',                               'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [425, 'LLAVE DE CAÑO',                                    'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [426, 'LOCTITE',                                          'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [427, 'LUBRIGOM X 20 LT',                                 'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [428, 'LUBRIGOM X 4LT',                                   'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [429, 'MACHETES',                                         'MANTENIMIENTO',       'UNIDAD', 7,   5,   1],
            [430, 'MANDRILES',                                        'MANTENIMIENTO',       'UNIDAD', 0,   5,   1],
            [431, 'MANGUERA DE 1',                                    'MANTENIMIENTO',       'METROS', 0,   500, 1],
            [432, 'MANGUERA DE 1 1/2',                                'MANTENIMIENTO',       'METROS', 0,   500, 1],
            [433, 'MANGUERA DE 1/2',                                  'MANTENIMIENTO',       'METROS', 1300,500, 1],
            [434, 'MANGUERA DE 3/4',                                  'MANTENIMIENTO',       'METROS', 1500,500, 1],
            [435, 'MARTILLO BOLITA',                                  'MANTENIMIENTO',       'UNIDAD', 7,   3,   1],
            [436, 'MARTILLO SACA CLAVOS',                             'MANTENIMIENTO',       'UNIDAD', 4,   3,   1],
            [437, 'MASILLA DE 10 KG',                                 'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [438, 'MAZA DE 1 KG',                                     'MANTENIMIENTO',       'UNIDAD', 6,   3,   1],
            [439, 'MAZA DE 1/2 KG',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [440, 'MAZA DE 10 KG',                                    'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [441, 'MAZA DE 2 KG',                                     'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [442, 'MECHAS 10 MM AR',                                  'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [443, 'MECHAS 10 MM W',                                   'MANTENIMIENTO',       'UNIDAD', 27,  3,   1],
            [444, 'MECHAS 10.5 MM AR',                                'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [445, 'MECHAS 11 MM AR',                                  'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [446, 'MECHAS 11.5 MM AR',                                'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [447, 'MECHAS 12 MM AR',                                  'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [448, 'MECHAS 12 MM W',                                   'MANTENIMIENTO',       'UNIDAD', 1,   3,   1],
            [449, 'MECHAS 12.5 MM AR',                                'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [450, 'MECHAS 3 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [451, 'MECHAS 3.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [452, 'MECHAS 4 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [453, 'MECHAS 4.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [454, 'MECHAS 5 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [455, 'MECHAS 5.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [456, 'MECHAS 6 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [457, 'MECHAS 6 MM W',                                    'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [458, 'MECHAS 6.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [459, 'MECHAS 7 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   3,   1],
            [460, 'MECHAS 7.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [461, 'MECHAS 8 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   0,   1],
            [462, 'MECHAS 8 MM W',                                    'MANTENIMIENTO',       'UNIDAD', 61,  10,  1],
            [463, 'MECHAS 8.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [464, 'MECHAS 9 MM AR',                                   'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [465, 'MECHAS 9.5 MM AR',                                 'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [466, 'Metro madera',                                     'MANTENIMIENTO',       'UNIDAD', 0,   5,   1],
            [467, 'NIVEL DE MANO',                                    'MANTENIMIENTO',       'UNIDAD', 18,  4,   1],
            [468, 'PALA ANCHA ESTAMPADA',                             'MANTENIMIENTO',       'UNIDAD', 1,   0,   1],
            [469, 'PALA ANCHA FORJADA',                               'MANTENIMIENTO',       'UNIDAD', 17,  0,   1],
            [470, 'PALA PUNTA ESTAMPADA',                             'MANTENIMIENTO',       'UNIDAD', 4,   3,   1],
            [471, 'PALA PUNTA FORJADA',                               'MANTENIMIENTO',       'UNIDAD', 1,   1,   1],
            [472, 'PALA PUNTA FORJADA MANGO HIERRO',                  'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [473, 'PICO',                                             'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [474, 'PINZAS',                                           'MANTENIMIENTO',       'UNIDAD', 1,   20,  1],
            [475, 'PIOLIN',                                           'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [476, 'PLOMADAS x 400 gr',                                'MANTENIMIENTO',       'UNIDAD', 11,  20,  1],
            [477, 'POXILINA',                                         'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [478, 'PRECINTO 150 MM X 3.6 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   50,  1],
            [479, 'PRECINTO 300 MM X 4.8 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [480, 'PRECINTO 350 MM X 7.6 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [481, 'PRECINTO 400 MM X 7.5 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   20,  1],
            [482, 'PRECINTO 400 MM X 7.6 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   2,   1],
            [483, 'PRECINTO 350 MM X 9.5 MM',                         'MANTENIMIENTO',       'UNIDAD', 0,   2,   1],
            [484, 'ROLLO CINTA DE PELIGRO',                           'MANTENIMIENTO',       'UNIDAD', 34,  5,   1],
            [485, 'ROLLO DE NYLON DE 1MTS  X 50 MTS',                 'MANTENIMIENTO',       'UNIDAD', 35,  1,   1],
            [486, 'ROLLO DE NYLON DE 2MTS X 50 MTS',                  'MANTENIMIENTO',       'UNIDAD', 10,  10,  1],
            [487, 'SELLA JUNTAS',                                     'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [488, 'SILICONA EN CARTUCHO',                             'MANTENIMIENTO',       'UNIDAD', 1,   10,  1],
            [489, 'SILICONA TRANSPARENTE POR 25 GR',                  'MANTENIMIENTO',       'UNIDAD', 25,  20,  1],
            [490, 'TANZA DE ALBAÑIL',                                 'MANTENIMIENTO',       'UNIDAD', 0,   30,  1],
            [491, 'TIJERA CORTA PERNO',                               'MANTENIMIENTO',       'UNIDAD', 0,   10,  1],
            [492, 'SILOC 8600',                                       'MANTENIMIENTO',       'UNIDAD', 41,  10,  1],
            [493, 'CUCHILLAS X 7 AGUJEROS',                           'REPUESTOS',           'UNIDAD', 0,   10,  1],
            [494, 'CUCHILLAS X 8 AGUJEROS',                           'REPUESTOS',           'UNIDAD', 0,   500, 1],
            [495, 'CUCHILLAS X 11 AGUJEROS',                          'REPUESTOS',           'UNIDAD', 0,   200, 1],
            [496, 'CUCHILLAS X 13 AGUJEROS',                          'REPUESTOS',           'UNIDAD', 0,   100, 1],
            [497, 'CUCHILLAS X 15 AGUJEROS',                          'REPUESTOS',           'UNIDAD', 0,   30,  1],
            [498, 'PERNOS P/UÑAS',                                    'REPUESTOS',           'UNIDAD', 0,   0,   1],
            [499, 'ADAPTADORES PARA LAMPARA',                         'SERVICIO ELECTRICO',  'UNIDAD', 180, 50,  12],
            [500, 'BASTIDOR RECTANCULAR',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   500, 12],
            [501, 'FICHAS HEMBRAS',                                   'SERVICIO ELECTRICO',  'UNIDAD', 0,   500, 12],
            [502, 'BOLTIAMPERIMETRO TRIFASICO',                       'SERVICIO ELECTRICO',  'UNIDAD', 0,   500, 12],
            [503, 'CABLE 1 X 1 MARRON',                               'SERVICIO ELECTRICO',  'METRO',  400, 100, 12],
            [504, 'CABLE 1 X 4 CELESTE',                              'SERVICIO ELECTRICO',  'METRO',  0,   500, 12],
            [505, 'CABLE 1 X 4 MARRON',                               'SERVICIO ELECTRICO',  'METRO',  600, 500, 12],
            [506, 'CABLE 1 X 6 MARRON',                               'SERVICIO ELECTRICO',  'METRO',  680, 500, 12],
            [507, 'CABLE 1 X 6 ROJO',                                 'SERVICIO ELECTRICO',  'METRO',  680, 500, 12],
            [508, 'CABLE 1 X 4 ROJO',                                 'SERVICIO ELECTRICO',  'METRO',  600, 500, 12],
            [509, 'CABLE 1 X 4 NEGRO',                                'SERVICIO ELECTRICO',  'METRO',  600, 300, 12],
            [510, 'CABLE 1 X 6 NEGRO',                                'SERVICIO ELECTRICO',  'METRO',  680, 500, 12],
            [511, 'CABLE ACOMETIDA 2X10 ALUMINIO',                    'SERVICIO ELECTRICO',  'METRO',  0,   500, 12],
            [512, 'CABLE ACOMETIDA 2X16 ALUMINIO',                    'SERVICIO ELECTRICO',  'METRO',  0,   500, 12],
            [513, 'CABLE 2 X 16 ALUMINIO',                            'SERVICIO ELECTRICO',  'METRO',  300, 0,   12],
            [514, 'CABLE ACOMETIDA 2x4 COBRE',                        'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [515, 'CABLE ACOMETIDA 2X6 ALUMINIO',                     'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [516, 'CABLE ACOMETIDA 2X6 COBRE',                        'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [517, 'CABLE ACOMETIDA 4 X 10 COBRE',                     'SERVICIO ELECTRICO',  'METRO',  0,   2,   12],
            [518, 'CABLE ACOMETIDA 4X16 COBRE',                       'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [519, 'CABLE PREENSAMBLADO 2X 6 (COBRE) 1 ROLLO 1000 MTS','SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [520, 'ROLLO DE CABLE 1X2,5 CELESTE',                     'SERVICIO ELECTRICO',  'METRO',  300, 100, 12],
            [521, 'CABLE PUESTO A TIERRA 1 X 2.5MM',                  'SERVICIO ELECTRICO',  'METRO',  400, 100, 12],
            [522, 'CABLE PUESTO A TIERRA 1 X 16MM',                   'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [523, 'CABLE PUESTO A TIERRA 1 X 4MM',                    'SERVICIO ELECTRICO',  'METRO',  600, 300, 12],
            [524, 'CABLE SUBTERRANEO 1 X 120 ROLLO DE 120 MSTRO',     'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [525, 'CABLE SUBTERRANEO 2 X 4MM',                        'SERVICIO ELECTRICO',  'METRO',  2200,800, 12],
            [526, 'CABLE SUBTERRANEO 2 X 6MM',                        'SERVICIO ELECTRICO',  'METRO',  250, 100, 12],
            [527, 'CABLE SUBTERRANEO DE 5 X 2,5',                     'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [528, 'CABLE SUBTERRANEO 4 X 10',                         'SERVICIO ELECTRICO',  'METRO',  2000,500, 12],
            [529, 'CABLE SUBTERRANEO 4 X 2,5',                        'SERVICIO ELECTRICO',  'METRO',  0,   0,   12],
            [530, 'CAJA DE PASE 165X165X80 BLANCA',                   'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [531, 'CAJA CHAPA 10X10 CON TAPA DE CHAPA',               'SERVICIO ELECTRICO',  'UNIDAD', 28,  10,  12],
            [532, 'CAJA CHAPA MIÑON CON TAPA DE CHAPA',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [533, 'CAJA TERMINA 8 BOCAS CON TAPA',                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [534, 'CAJA PVC EXTERIOR 2 MODULOS',                      'SERVICIO ELECTRICO',  'UNIDAD', 0,   50,  12],
            [535, 'CAJA RECTAGULAR/OCTOGONAL LIVIANA',                'SERVICIO ELECTRICO',  'UNIDAD', 0,   50,  12],
            [536, 'CAÑO REDONDO 60 MM / 2"',                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [537, 'CAJAS EXTERIOR P/ TABLERO RIEL Y TAPA',            'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [538, 'CAÑO REDONDO DE 50MM',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [539, 'CAÑO REDONDO 90 MM /3"',                           'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [540, 'CONECTOR TUBO PVC 25MM',                           'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [541, 'CAÑO REDONDE 115 MM / 4"',                         'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [542, 'CAÑO REDONDO 75 MM / 2 1/2"',                      'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [543, 'CINTA ADHESIVA PVC NEGRAS',                        'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [544, 'CAÑO REDONDO DE 100 MM',                           'SERVICIO ELECTRICO',  'UNIDAD', 0,   200, 12],
            [545, 'CONTACTOR 50AMP 220W',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [546, 'CONTACTOR 20AMP 220W',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   200, 12],
            [547, 'CONTACTOR 401',                                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [548, 'DEMALEC REFLECTORES',                              'SERVICIO ELECTRICO',  'UNIDAD', 0,   3,   12],
            [549, 'CONTACTOR P/16A BOBINA 380',                       'SERVICIO ELECTRICO',  'UNIDAD', 0,   3,   12],
            [550, 'CONTACTOR X 40',                                   'SERVICIO ELECTRICO',  'UNIDAD', 2,   1,   12],
            [551, 'CONTACTOR X 63',                                   'SERVICIO ELECTRICO',  'UNIDAD', 1,   0,   12],
            [552, 'DIYUNTOR 63',                                      'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [553, 'DISYUNTOR 2X25(A)',                                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   300, 12],
            [554, 'DISYUNTOR C 40',                                   'SERVICIO ELECTRICO',  'UNIDAD', 74,  200, 12],
            [555, 'FAROLA DE COLGAR',                                 'SERVICIO ELECTRICO',  'UNIDAD', 840, 300, 12],
            [556, 'FAROLAS COLONIAL',                                 'SERVICIO ELECTRICO',  'UNIDAD', 60,  3,   12],
            [557, 'FAROLA PESCANTE',                                  'SERVICIO ELECTRICO',  'UNIDAD', 650, 300, 12],
            [558, 'GABINETE ESTANCO METAL 300X450X210',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   3,   12],
            [559, 'REFLECTOR 10W',                                    'SERVICIO ELECTRICO',  'UNIDAD', 94,  50,  12],
            [560, 'PRESINTO',                                         'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [561, 'FLUORECENTES 18 W',                                'SERVICIO ELECTRICO',  'UNIDAD', 36,  8,   12],
            [562, 'FUSIBLE 10AMP',                                    'SERVICIO ELECTRICO',  'UNIDAD', 500, 5,   12],
            [563, 'FOTOCONTROL',                                      'SERVICIO ELECTRICO',  'UNIDAD', 240, 50,  12],
            [564, 'GABINETE ESTANCO METAL 300X450X225',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [565, 'GABINETE 300X450X150',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [566, 'GABINETE ESTANCO METAL 320X420X200',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [567, 'GABINETE 500X400X210',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [568, 'GABINETE ESTANCO METAL 450X450X120',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   100, 12],
            [569, 'GABINETE ESTANCO METAL 450X450X225',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [570, 'IT 2X25',                                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   100, 12],
            [571, 'PORTA LAMPARA C/CHICOTE',                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [572, 'MACROLED LAMPARA LED 90 W',                        'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [573, 'MACROLED REFLECTORES LED X 200 W',                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [574, 'MACROLED REFLECTORES LED X 200 W CALIDOS',         'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [575, 'LAMPARA LED 150W',                                 'SERVICIO ELECTRICO',  'UNIDAD', 22,  20,  12],
            [576, 'LAMPARA 10WTS',                                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   50,  12],
            [577, 'GABINETE ESTANCO METAL 450X600X100',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [578, 'GABINETE METALICO 30X30X30',                       'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [579, 'GABINETE ESTANCO METAL 600X400X210',               'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [580, 'LAMPARA LED 50 W',                                 'SERVICIO ELECTRICO',  'UNIDAD', 305, 200, 12],
            [581, 'GABINETE METALICO 50X40X16',                       'SERVICIO ELECTRICO',  'UNIDAD', 0,   200, 12],
            [582, 'GRANPAS P/PESCANTE C/TORNILLO',                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   5,   12],
            [583, 'LAMPARAS LED 100W CALIDA',                         'SERVICIO ELECTRICO',  'UNIDAD', 26,  10,  12],
            [584, 'HEBILLA DE ACERO 3/4',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [585, 'ID 2X40',                                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [586, 'MACROLED LAMPARA LED 38 W',                        'SERVICIO ELECTRICO',  'UNIDAD', 338, 2,   12],
            [587, 'LLAVES DE PUNTO',                                  'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [588, 'PORTA LAMPARA COMUN GUIRNALDAS',                   'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [589, 'INTERRUPTOR CM 25',                                'SERVICIO ELECTRICO',  'UNIDAD', 0,   200, 12],
            [590, 'HIERRO PESCANTES',                                 'SERVICIO ELECTRICO',  'UNIDAD', 240, 100, 12],
            [591, 'I.LED LAMPARA LED X 160',                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [592, 'PRENSA CABLE',                                     'SERVICIO ELECTRICO',  'METRO',  0,   2,   12],
            [593, 'ROLLO CABLE 1X25',                                 'SERVICIO ELECTRICO',  'METRO',  0,   2,   12],
            [594, 'CABLE 1 X 6 CELESTE',                              'SERVICIO ELECTRICO',  'METRO',  780, 500, 12],
            [595, 'OJO DE BUEY AZUL',                                 'SERVICIO ELECTRICO',  'UNIDAD', 8,   5,   12],
            [596, 'ROLLO DE CABLE 1X1,5 MARRON',                      'SERVICIO ELECTRICO',  'METRO',  400, 2,   12],
            [597, 'PK',                                               'SERVICIO ELECTRICO',  'UNIDAD', 0,   2,   12],
            [598, 'PLAFON LED 40 W CUADRADO',                         'SERVICIO ELECTRICO',  'UNIDAD', 4,   2,   12],
            [599, 'PANEL LED 18 W',                                   'SERVICIO ELECTRICO',  'UNIDAD', 33,  15,  12],
            [600, 'PANEL LED 24 W',                                   'SERVICIO ELECTRICO',  'UNIDAD', 34,  2,   12],
            [601, 'REFLECTORES PHILLIPS  150W P/ ACCESO SUR',         'SERVICIO ELECTRICO',  'UNIDAD', 90,  20,  12],
            [602, 'OJO DE BUEY ROJO',                                 'SERVICIO ELECTRICO',  'UNIDAD', 38,  20,  12],
            [603, 'LAMPARA LED 100 W',                                'SERVICIO ELECTRICO',  'UNIDAD', 310, 100, 12],
            [604, 'ROLLO DE CABLE 1X1.5 BLANCO',                      'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [605, 'ROLLO DE CABLE 1X1.5 ROJO',                        'SERVICIO ELECTRICO',  'METRO',  300, 100, 12],
            [606, 'ROLLO DE CABLE 1X1.5 CELESTE',                     'SERVICIO ELECTRICO',  'METRO',  800, 300, 12],
            [607, 'ROLLO DE CABLE 1X1,5 NEGRO',                       'SERVICIO ELECTRICO',  'METRO',  900, 200, 12],
            [608, 'PK FUSIBLE',                                       'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [609, 'ROLLO DE CABLE 1X1,5 VERDE/AMARILLO',              'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [610, 'FAROLES 100W',                                     'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [611, 'REFLECTORES LED X 240 W',                          'SERVICIO ELECTRICO',  'UNIDAD', 39,  20,  12],
            [612, 'ROLLO DE CABLE 1X2,5 NEGRO',                       'SERVICIO ELECTRICO',  'METRO',  100, 20,  12],
            [613, 'ROLLO DE CABLE 1X2,5 VERDE/AMARILLO',              'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [614, 'ROLLO DE CABLE 1X2.5 MARRON',                      'SERVICIO ELECTRICO',  'METRO',  400, 20,  12],
            [615, 'ROLLO DE CABLE 1X2.5 ROJO',                        'SERVICIO ELECTRICO',  'METRO',  400, 20,  12],
            [616, 'ROLLO DE CABLE 2X1,5',                             'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [617, 'ROLLO DE CABLE 2X1,5 TPR',                         'SERVICIO ELECTRICO',  'METRO',  1320,800, 12],
            [618, 'ROLLO DE CABLE 2X16(ALUMINIO)',                    'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [619, 'ROLLO DE CABLE 2X2,5 TPR',                         'SERVICIO ELECTRICO',  'METRO',  200, 100, 12],
            [620, 'ROLLO DE CABLE 4X1,5',                             'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [621, 'ROLLO DE CABLE 4X2,5 TPR',                         'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [622, 'ROLLO DE CABLE 5 x 2,5',                           'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [623, 'ROLLO DE CABLE CONCENTRICO',                       'SERVICIO ELECTRICO',  'METRO',  0,   20,  12],
            [624, 'ROLLO DE CINTA AUTOSOLDABLE',                      'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [625, 'ROLLO DE CINTA NEGRA 3M',                          'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [626, 'TABLERO EXTERIOR DE 4 BOCAS',                      'SERVICIO ELECTRICO',  'UNIDAD', 0,   200, 12],
            [627, 'TABLERO MONOFASICO',                               'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [628, 'TAPA RECTANGULAR',                                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   0,   12],
            [629, 'TERMICA 1 X10 A',                                  'SERVICIO ELECTRICO',  'UNIDAD', 180, 100, 12],
            [630, 'TERMICA C 10 A',                                   'SERVICIO ELECTRICO',  'UNIDAD', 78,  40,  12],
            [631, 'TERMICA 2 X 16',                                   'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [632, 'TERMICA 2 X 25',                                   'SERVICIO ELECTRICO',  'UNIDAD', 20,  10,  12],
            [633, 'TERMICA 4X16',                                     'SERVICIO ELECTRICO',  'UNIDAD', 0,   30,  12],
            [634, 'TERMICA C40 X 4 BOCA',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   30,  12],
            [635, 'TERMICAS 1 X 6',                                   'SERVICIO ELECTRICO',  'UNIDAD', 0,   30,  12],
            [636, 'TERMICAS 2 X 10',                                  'SERVICIO ELECTRICO',  'UNIDAD', 0,   30,  12],
            [637, 'TERMICAS 4 X 10',                                  'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [638, 'TERMICAS 4X63',                                    'SERVICIO ELECTRICO',  'UNIDAD', 12,  5,   12],
            [639, 'TERMICAS DE 40 A',                                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   20,  12],
            [640, 'TETRAPOLAR 4X 40',                                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [641, 'TOMA EXTERIOR',                                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [642, 'TOMA HEMBRA 4X16 EXT',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [643, 'TOMA HEMBRA 4X32 EXT',                             'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [644, 'TORTUGA 12 W',                                     'SERVICIO ELECTRICO',  'UNIDAD', 7,   1,   12],
            [645, 'JABALINA 1 MT',                                    'SERVICIO ELECTRICO',  'UNIDAD', 76,  30,  12],
            [646, 'JABALINA 1.5 MT',                                  'SERVICIO ELECTRICO',  'UNIDAD', 30,  30,  12],
            [647, 'CAJA ENCAPSULADO EXT',                             'SERVICIO ELECTRICO',  'UNIDAD', 50,  12,  12],
            [648, 'TOMAS DOBLES EXULT COMPLETOS',                     'SERVICIO ELECTRICO',  'UNIDAD', 0,   12,  12],
            [649, 'TRIFASICO BAW 63AMP',                              'SERVICIO ELECTRICO',  'UNIDAD', 0,   10,  12],
            [650, 'TUBOS LED DE 18W',                                 'SERVICIO ELECTRICO',  'UNIDAD', 0,   1,   12],
            [651, 'ZOCALOS',                                          'SERVICIO ELECTRICO',  'UNIDAD', 228, 50,  12],
            [652, 'ZUNCHOS ACERO',                                    'SERVICIO ELECTRICO',  'UNIDAD', 0,   1,   12],
            [653, 'ARENA',                                            'MATERIAL GRUESO',     'METRO',  0,   1,   19],
            [654, 'PIEDRA 10/30',                                     'MATERIAL GRUESO',     'METRO',  0,   10,  19],
            [655, 'TOSCA',                                            'MATERIAL GRUESO',     'METRO',  0,   2,   19],
            [656, 'CEMENTO X 25',                                     'MATERIAL GRUESO',     'BOLSA',  31,  15,  19],
            [657, 'CEMENTO X 50',                                     'MATERIAL GRUESO',     'BOLSA',  0,   8,   19],
            [658, 'CAL X 25',                                         'MATERIAL GRUESO',     'BOLSA',  13,  10,  19],
            [659, 'MALLAS',                                           'MATERIAL GRUESO',     'UNIDAD', 0,   8,   19],
            [660, 'VARILLA DEL 6',                                    'MATERIAL GRUESO',     'UNIDAD', 0,   5,   19],
            [661, 'VARILLA DEL 8',                                    'MATERIAL GRUESO',     'UNIDAD', 0,   3,   19],
            [662, 'VARILLA DEL 10',                                   'MATERIAL GRUESO',     'UNIDAD', 0,   20,  19],
            [663, 'CAÑO HORMIGON 40',                                 'MATERIAL GRUESO',     'UNIDAD', 0,   20,  19],
            [664, 'CAÑO HORMIGON 50',                                 'MATERIAL GRUESO',     'UNIDAD', 16,  10,  19],
            [665, 'CAÑO HORMIGON 60',                                 'MATERIAL GRUESO',     'UNIDAD', 205, 10,  19],
            [666, 'CAÑO HORMIGON 80',                                 'MATERIAL GRUESO',     'UNIDAD', 0,   20,  19],
            [667, 'CAÑO HORMIGON 100',                                'MATERIAL GRUESO',     'UNIDAD', 28,  2,   19],
            [668, 'ANGULO',                                           'HIERROS',             'UNIDAD', 0,   0,   11],
            [669, '1/2 X 1/8',                                        'HIERROS',             'UNIDAD', 57,  50,  11],
            [670, '3/4 X 1/8',                                        'HIERROS',             'UNIDAD', 43,  10,  11],
            [671, '7/8 X 1/8',                                        'HIERROS',             'UNIDAD', 50,  10,  11],
            [672, '1 X 3/16',                                         'HIERROS',             'UNIDAD', 23,  30,  11],
            [673, '1 1/2 X 3/16',                                     'HIERROS',             'UNIDAD', 92,  30,  11],
            [674, 'UPN',                                              'HIERROS',             'UNIDAD', 0,   0,   11],
            [675, '0.40',                                             'HIERROS',             'UNIDAD', 0,   30,  11],
            [676, '0.60',                                             'HIERROS',             'UNIDAD', 5,   10,  11],
            [677, '0.80',                                             'HIERROS',             'UNIDAD', 5,   50,  11],
            [678, 'CHAPAS',                                           'HIERROS',             'UNIDAD', 0,   0,   11],
            [679, '3/8 DE 1 X 2',                                     'HIERROS',             'UNIDAD', 1,   1,   11],
            [680, '18 DE 1,22 X 2,44',                                'HIERROS',             'UNIDAD', 137, 30,  11],
            [681, 'ESTRUCTURAL',                                      'HIERROS',             'UNIDAD', 0,   0,   11],
            [682, '100-100 X 3MM ESP',                                'HIERROS',             'UNIDAD', 21,  10,  11],
            [683, '30-30 2MM',                                        'HIERROS',             'UNIDAD', 60,  5,   11],
            [684, '40-40 2MM',                                        'HIERROS',             'UNIDAD', 67,  5,   11],
            [685, '20-40 2MM',                                        'HIERROS',             'UNIDAD', 68,  100, 11],
            [686, '35-35 2MM',                                        'HIERROS',             'UNIDAD', 0,   5,   11],
            [687, 'METAL DESPLEGADO',                                 'HIERROS',             'UNIDAD', 0,   5,   11],
            [688, '500-30-30',                                        'HIERROS',             'UNIDAD', 25,  10,  11],
            [689, 'CAÑO REDONDO',                                     'HIERROS',             'UNIDAD', 0,   0,   11],
            [690, '1"',                                               'HIERROS',             'UNIDAD', 30,  10,  11],
            [691, '1 1/2"',                                           'HIERROS',             'UNIDAD', 29,  20,  11],
            [692, 'PLANCHUELA',                                       'HIERROS',             'UNIDAD', 0,   0,   11],
            [693, '1 1/2 X 1/8',                                      'HIERROS',             'UNIDAD', 6,   10,  11],
            [694, '1 X 3/16',                                         'HIERROS',             'UNIDAD', 62,  10,  11],
            [695, 'REDONDO LISO (VARILLA)',                            'HIERROS',             'UNIDAD', 0,   0,   11],
            [696, '6 MM',                                             'HIERROS',             'UNIDAD', 120, 30,  11],
            [697, '8 MM',                                             'HIERROS',             'UNIDAD', 117, 30,  11],
            [698, '10 MM',                                            'HIERROS',             'UNIDAD', 54,  2,   11],
            [699, 'HIERRO T',                                         'HIERROS',             'UNIDAD', 0,   0,   11],
            [700, '3/4',                                              'HIERROS',             'UNIDAD', 27,  5,   11],
            [701, '1"',                                               'HIERROS',             'UNIDAD', 0,   0,   11],
            [702, '1 1/2',                                            'HIERROS',             'UNIDAD', 0,   0,   11],
            [703, 'CAÑO',                                             'HIERROS',             'UNIDAD', 0,   0,   11],
            [704, '63 X 2MM',                                         'HIERROS',             'UNIDAD', 55,  1,   11],
            [705, '4" X 2MM',                                         'HIERROS',             'UNIDAD', 14,  1,   11],
            [706, '3" X 2MM',                                         'HIERROS',             'UNIDAD', 0,   5,   11],
            [707, '3" X 4MM',                                         'HIERROS',             'UNIDAD', 62,  2,   11],
            [708, '88 X 4MM',                                         'HIERROS',             'UNIDAD', 255, 2,   11],
            [709, '49 X 3MM',                                         'HIERROS',             'UNIDAD', 6,   0,   11],
            [710, '113 X 3.5 MM',                                     'HIERROS',             'UNIDAD', 137, 5,   11],
            [711, 'Motoguadaña Echo 4605',                            'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [712, 'Tanza 3mm cuadrada marca Grilon',                  'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [713, 'Cabezal',                                          'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [714, 'Anillos para carreteles',                          'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [715, 'Filtro de aire',                                   'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [716, 'Cable de acelador',                                'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [717, 'Sistema de arranque completo',                     'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [718, 'Resorte retractil',                                'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [719, 'Carretel retractil',                               'Motoguadaña Echo 4605','UNIDAD', 0,  1,   16],
            [720, 'Soga arranque (m)',                                 'Motoguadaña Echo 4605','UNIDAD', 0,  0,   16],
            [721, 'juego completo de manguera nafta',                 'Motoguadaña Echo 4605','UNIDAD', 0,  0,   16],
            [722, 'Manguera de nafta',                                'Motoguadaña Echo 4605','UNIDAD', 0,  1,   16],
            [723, 'Junta de carburador',                              'Motoguadaña Echo 4605','UNIDAD', 0,  4,   16],
            [724, 'Carburador',                                       'Motoguadaña Echo 4605','UNIDAD', 0,  10,  16],
            [725, 'Cilindro',                                         'Motoguadaña Echo 4605','UNIDAD', 0,  1,   16],
            [726, 'Protectores facial con rejilla',                   'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [727, 'Bujias',                                           'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [728, 'Filtro de nafta',                                  'Motoguadaña Echo 4605','UNIDAD', 0,  0,   16],
            [729, 'Junta base de cilindro',                           'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [730, 'Junta de escape deflactor',                        'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [731, 'Campana de embrague',                              'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [732, 'Resorte de embrague',                              'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [733, 'Zapata de embrage',                                'Motoguadaña Echo 4605','UNIDAD', 0,  1,   16],
            [734, 'Empuñadura',                                       'Motoguadaña Echo 4605','UNIDAD', 0,  1,   16],
            [735, 'Bobina de encendido',                              'Motoguadaña Echo 4605','UNIDAD', 0,  0,   16],
            [736, 'Grasa',                                            'Motoguadaña Echo 4605','UNIDAD', 0,  5,   16],
            [737, 'Cuchilla',                                         'Motoguadaña Echo 4605','UNIDAD', 0,  2,   16],
            [738, 'Motosierras',                                      'Motosierras',          'UNIDAD', 0,  2,   16],
            [739, 'rollo de cadena (echo 303 y sthil 194)',           'Motosierras',          'UNIDAD', 0,  2,   16],
            [740, 'rollo de cadena (echo 420)',                       'Motosierras',          'UNIDAD', 0,  2,   16],
            [741, 'rollo de cadena (echo 620)',                       'Motosierras',          'UNIDAD', 0,  1,   16],
            [742, '14"(35cm) .050/1,3mm 3/8 50coraz 9T',             'Motosierras',          'UNIDAD', 0,  1,   16],
            [743, 'Espadas',                                          'Motosierras',          'UNIDAD', 0,  2,   16],
            [744, '12"(30cm) .050/1,3mm 3/8 45coraz 9T',             'Motosierras',          'UNIDAD', 0,  2,   16],
            [745, 'Filtro de aire Echo 303 ( planos retang)',         'Motosierras',          'UNIDAD', 0,  4,   16],
            [746, 'Filtro de aire Echo 600 ( caja blanca)',           'Motosierras',          'UNIDAD', 0,  0,   16],
            [747, '14"(35cm) .050/1,3mm 3/8 52coraz 9T',             'Motosierras',          'UNIDAD', 0,  2,   16],
            [748, 'Filtro de aire Echo 420 (cilindro rojo)',          'Motosierras',          'UNIDAD', 0,  2,   16],
            [749, '16"(40cm) .058/1,5mm 325 66coraz 12T',            'Motosierras',          'UNIDAD', 0,  2,   16],
            [750, '18"(45cm) .058/1,5mm 325 72coraz 12T',            'Motosierras',          'UNIDAD', 0,  1,   16],
            [751, '18"(45cm) .058/1,5mm 325  10T',                   'Motosierras',          'UNIDAD', 0,  3,   16],
            [752, '18"(45cm) .063/1,6mm 325 74coraz 12T',            'Motosierras',          'UNIDAD', 0,  3,   16],
            [753, '20"(50cm) .050/1,3mm 3/8 70coraz 11T',            'Motosierras',          'UNIDAD', 0,  2,   16],
            [754, '20"(50cm) .058/1,5mm 3/8 72coraz',               'Motosierras',          'UNIDAD', 0,  2,   16],
            [755, '36" (90cm). 063/ 1,6mm 3/8 114 coraz',            'Motosierras',          'UNIDAD', 0,  1,   16],
            [756, "20' marca Logbelts",                               'Motosierras',          'UNIDAD', 0,  5,   16],
            [757, "18' marca Logbelts",                               'Motosierras',          'UNIDAD', 0,  6,   16],
            [758, 'Tubo principal naranja',                           'Motosierras',          'UNIDAD', 0,  0,   16],
            [759, 'Sopladora pb252',                                  'Motosierras',          'UNIDAD', 0,  10,  16],
            [760, 'Filtro de acite',                                  'Motosierras',          'UNIDAD', 0,  10,  16],
            [761, "Cuchillas plataforma 42'",                         'Motosierras',          'UNIDAD', 0,  10,  16],
            [762, 'Bobina de encendido',                              'Motosierras',          'UNIDAD', 0,  5,   16],
            [763, 'Cilindro y piston conpleto',                       'Motosierras',          'UNIDAD', 0,  0,   16],
            [764, 'Bujias',                                           'Motosierras',          'UNIDAD', 0,  0,   16],
            [765, 'Filtro de nafta',                                  'Motosierras',          'UNIDAD', 0,  0,   16],
            [766, 'Tractor Toro 4200',                                'Motosierras',          'UNIDAD', 0,  0,   16],
            [767, 'Filtro de aire de motor',                          'Motosierras',          'UNIDAD', 0,  0,   16],
            [768, 'Tractores Troy Bilt (TB 547/42 )',                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [769, 'Tensores de correa de plataforma',                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [770, 'Filtro de aire de motor',                          'Motosierras',          'UNIDAD', 0,  0,   16],
            [771, 'Filtro de acite',                                  'Motosierras',          'UNIDAD', 0,  0,   16],
            [772, 'Sistema de arranque completro (retractil)',         'Motosierras',          'UNIDAD', 0,  0,   16],
            [773, 'Torretas completas',                               'Motosierras',          'UNIDAD', 0,  0,   16],
            [774, 'Correa plataforma',                                'Motosierras',          'UNIDAD', 0,  0,   16],
            [775, 'Tensores de correa de plataforma',                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [776, 'Torretas completas',                               'Motosierras',          'UNIDAD', 0,  0,   16],
            [777, 'Bujias',                                           'Motosierras',          'UNIDAD', 0,  0,   16],
            [778, 'Filtro de nafta',                                  'Motosierras',          'UNIDAD', 0,  0,   16],
            [779, "Cuchillas plataforma 42'",                         'Motosierras',          'UNIDAD', 0,  0,   16],
            [780, 'Correa plataforma',                                'Motosierras',          'UNIDAD', 0,  0,   16],
            [781, 'Tractor Toro 5050',                                'Motosierras',          'UNIDAD', 0,  0,   16],
            [782, 'Filtro de aire de motor',                          'Motosierras',          'UNIDAD', 0,  0,   16],
            [783, 'Correa plataforma',                                'Motosierras',          'UNIDAD', 0,  0,   16],
            [784, 'tensores de correa de plataforma',                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [785, 'Filtro de nafta',                                  'Motosierras',          'UNIDAD', 0,  0,   16],
            [786, 'Deflector del cesped',                             'Motosierras',          'UNIDAD', 0,  0,   16],
            [787, 'Torretas completas',                               'Motosierras',          'UNIDAD', 0,  0,   16],
            [788, "Cuchillas plataforma de 50'",                      'Motosierras',          'UNIDAD', 0,  0,   16],
            [789, 'Filtro de aire',                                   'Motosierras',          'UNIDAD', 0,  0,   16],
            [790, 'Filtro de acite',                                  'Motosierras',          'UNIDAD', 0,  0,   16],
            [791, 'Polea tensora',                                    'Motosierras',          'UNIDAD', 0,  0,   16],
            [792, 'Bujias',                                           'Motosierras',          'UNIDAD', 0,  0,   16],
            [793, 'Correa de transmisión',                            'Motosierras',          'UNIDAD', 0,  0,   16],
            [794, 'Protectores auditivos',                            'Motosierras',          'UNIDAD', 0,  0,   16],
            [795, 'Protector ocular negros (anteojos)',               'Motosierras',          'UNIDAD', 0,  0,   16],
            [796, 'Accesorios',                                       'Motosierras',          'UNIDAD', 0,  0,   16],
            [797, 'Correa de caja',                                   'Motosierras',          'UNIDAD', 0,  0,   16],
            [798, 'Protector ocular transparente (anteojos)',         'Motosierras',          'UNIDAD', 0,  0,   16],
            [799, 'Rodamientos 6203',                                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [800, 'Rodamientos 6204',                                 'Motosierras',          'UNIDAD', 0,  0,   16],
            [801, 'Piston',                                           'Motosierras',          'UNIDAD', 0,  0,   16],
        ];

        // Insertar en lotes de 50 para no saturar la memoria
        foreach (array_chunk($rows, 50) as $chunk) {
            $insert = [];
            foreach ($chunk as [$id, $insumo, $catNombre, $unidad, $stock_actual, $stock_minimo, $id_deposito]) {
                $insert[] = [
                    'id'           => $id,
                    'insumo'       => $insumo,
                    'id_categoria' => $this->catId($catCache, $catNombre),
                    'unidad'       => $unidad,
                    'stock_actual' => $stock_actual,
                    'stock_minimo' => $stock_minimo,
                    'id_deposito'  => $id_deposito,
                    'created_at'   => $now,
                    'updated_at'   => $now,
                ];
            }
            DB::table('insumos')->insert($insert);
        }

        // Reajustar el auto_increment al valor más alto + 1
        DB::statement('ALTER TABLE insumos AUTO_INCREMENT = 802;');

        $this->command->info('✅ Tabla insumos poblada con ' . count($rows) . ' registros.');
    }
}