<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InsumosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Parte 1: Categorías 1-4 (IDs 1-190)
        $insumos_parte1 = [
            // Categoría 1 - CUBIERTAS (IDs 1-59)
            ['id' => 1, 'insumo' => '1000x16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 2, 'insumo' => '1000x20 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 3, 'insumo' => '12,16,5 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 4, 'insumo' => '12,4,24 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 5, 'insumo' => '12,4,28 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 6, 'insumo' => '1300x24 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 7, 'insumo' => '14,17,5 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 8, 'insumo' => '1400x24 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 9, 'insumo' => '16-4-28 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 10, 'insumo' => '16-70-20 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 11, 'insumo' => '16-9-30 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 12, 'insumo' => '16,9,28 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 13, 'insumo' => '17,5,25 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 14, 'insumo' => '175-70-16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 15, 'insumo' => '175.70R14 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 16, 'insumo' => 'CUBIERTA 245-70-17,5', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 17, 'insumo' => '18,4,34 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 18, 'insumo' => '215-75-17.5 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 19, 'insumo' => '19-5-24 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 20, 'insumo' => '185.60R14 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 21, 'insumo' => '215,80,r16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 22, 'insumo' => '215/65-16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 23, 'insumo' => '225-70-19.5 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 24, 'insumo' => '225-75-15 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 25, 'insumo' => '23-1-30 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 26, 'insumo' => '23-5-25 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 27, 'insumo' => '235-70-16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 28, 'insumo' => '235-75-15 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 29, 'insumo' => '235/16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 30, 'insumo' => '245/70/16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 31, 'insumo' => '255-70-16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 32, 'insumo' => '650x16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 33, 'insumo' => '295,80,22,5 lisa - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 34, 'insumo' => '295,80,22,5 c/taco - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 35, 'insumo' => '265-75-16 .- - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 36, 'insumo' => '275,80,22,5 c/taco - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 37, 'insumo' => '650x16 lisa - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 38, 'insumo' => '275,80,22,5 LISA - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 39, 'insumo' => '650x16 taco - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 40, 'insumo' => '700 X 16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 41, 'insumo' => '750 X 16 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 42, 'insumo' => '750 X 18 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 43, 'insumo' => '750 X 20 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 44, 'insumo' => '900 x 20 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 45, 'insumo' => '900/20 c/taco - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 46, 'insumo' => 'CUBIERTA 205-65-15', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 47, 'insumo' => 'CUBIERTA 650 X 10', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 48, 'insumo' => 'CUBIERTA 12.5-80-18', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 49, 'insumo' => 'cubierta 1100 x 20', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 50, 'insumo' => 'CUBIERTA 14-9-24', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 51, 'insumo' => 'CUBIERTA 750 X 20', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 52, 'insumo' => 'CUBIERTA 205/ 65 -16.-', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 53, 'insumo' => 'CUBIERTAS 175-65-14', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 54, 'insumo' => 'cubiertas 185-65-15', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 55, 'insumo' => 'CUBIERTA 225-70-17', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 56, 'insumo' => 'CUBIERTA 195-70-15', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 57, 'insumo' => 'cubierta 4.10/3.50 k358', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 58, 'insumo' => 'CUBIERTA 215-70-17,5', 'id_categoria' => 1, 'unidad' => 'unidad'],
            ['id' => 59, 'insumo' => '18-4-38 - CUBIERTAS', 'id_categoria' => 1, 'unidad' => 'unidad'],

            // Categoría 2 - PINTURAS (IDs 60-167)
            ['id' => 60, 'insumo' => 'AEROSOLES BLANCO', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 61, 'insumo' => 'AEROSOLES NEGRO', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 62, 'insumo' => 'AGUARRAS X 200 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 63, 'insumo' => 'ANTIOXIDO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 64, 'insumo' => 'PINTURA ASFALTICA x 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 65, 'insumo' => 'PINTURA ASFALTICA x 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 66, 'insumo' => 'PINTURA ASFALTICA X10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 67, 'insumo' => 'BANDEJA PARA RODILLOS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 68, 'insumo' => 'CETOL X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 69, 'insumo' => 'CETOL X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 70, 'insumo' => 'ENDUIDO 30 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 71, 'insumo' => 'ENDUIDO X 10 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 72, 'insumo' => 'ENDUIDO X 4 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 73, 'insumo' => 'ENDUIDO X 1 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 74, 'insumo' => 'ESMALTE CONVERTIDOR (HIERRO ANTIGUO) X 4LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 75, 'insumo' => 'LIJAS X 120', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 76, 'insumo' => 'ESPATULAS DE CHAPA', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 77, 'insumo' => 'LATEX AMARILLO X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 78, 'insumo' => 'FONDO BLANCO PARA MADERA X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 79, 'insumo' => 'LATEX AMARILLO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 80, 'insumo' => 'LATEX AZUL TRAFUL x 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 81, 'insumo' => 'LATEX AMARILLO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 82, 'insumo' => 'LATEX AZUL TRAFUL x 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 83, 'insumo' => 'LATEX AZUL x 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 84, 'insumo' => 'LATEX AZUL TRAFUL x 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 85, 'insumo' => 'LATEX AZUL x 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 86, 'insumo' => 'LATEX BLANCO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 87, 'insumo' => 'LATEX AZUL x 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 88, 'insumo' => 'LATEX BLANCO X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 89, 'insumo' => 'LATEX GRIS CEMENTO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 90, 'insumo' => 'LATEX BLANCO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 91, 'insumo' => 'LATEX MARRON X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 92, 'insumo' => 'LATEX MARRON X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 93, 'insumo' => 'LATEX NEGRO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 94, 'insumo' => 'LATEX GRIS CEMENTO X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 95, 'insumo' => 'LATEX GRIS CEMENTO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 96, 'insumo' => 'LATEX NEGRO X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 97, 'insumo' => 'LATEX MARRON X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 98, 'insumo' => 'LATEX ROJO BERMELLON X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 99, 'insumo' => 'LATEX NEGRO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 100, 'insumo' => 'LATEX ROJO BERMELLON X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 101, 'insumo' => 'LATEX VERDE FORESTA X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 102, 'insumo' => 'LATEX ROJO BERMELLON X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 103, 'insumo' => 'LATEX VERDE FORESTA X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 104, 'insumo' => 'LATEX VERDE SAFARI X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 105, 'insumo' => 'LATEX VERDE FORESTA X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 106, 'insumo' => 'LATEX VERDE SAFARI X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 107, 'insumo' => 'LATEX VERDE SAFARI X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 108, 'insumo' => 'LATEX VIOLETA X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 109, 'insumo' => 'LATEX VIOLETA X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 110, 'insumo' => 'RODILLO 8 CM', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 111, 'insumo' => 'SINTETICO AZUL TRAFUL X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 112, 'insumo' => 'PINCEL N 30', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 113, 'insumo' => 'PINCEL N 25', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 114, 'insumo' => 'SINTETICO AMARILLO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 115, 'insumo' => 'SINTETICO AMARILLO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 116, 'insumo' => 'SINTETICO AZUL TRAFUL X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 117, 'insumo' => 'SINTETICO AZUL X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 118, 'insumo' => 'SINTETICO BEIGE X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 119, 'insumo' => 'SINTETICO AZUL X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 120, 'insumo' => 'SINTETICO BEIGE X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 121, 'insumo' => 'SINTETICO BERMELLON X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 122, 'insumo' => 'SINTETICO VIOLETA X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 123, 'insumo' => 'PINCEL N 10', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 124, 'insumo' => 'SINTETICO NEGRO SATINADO X 20 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 125, 'insumo' => 'SINTETICO NEGRO SATINADO X 10 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 126, 'insumo' => 'SINTETICO NEGRO SATINADO X 4 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 127, 'insumo' => 'SINTETICO MARRON X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 128, 'insumo' => 'SINTETICO NEGRO BRILLANTE X  10 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 129, 'insumo' => 'SINTETICO VIOLETA X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 130, 'insumo' => 'SINTETICO BERMELLON X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 131, 'insumo' => 'SINTETICO BLANCO BRILLANTE X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 132, 'insumo' => 'SINTETICO BLANCO BRILLANTE X 20 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 133, 'insumo' => 'SINTETICO GRIS CEMENTO X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 134, 'insumo' => 'SINTETICO GRIS ESPECIAL X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 135, 'insumo' => 'SINTETICO BLANCO BRILLANTE X 4LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 136, 'insumo' => 'SINTETICO CELESTE X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 137, 'insumo' => 'SINTETICO MARRON X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 138, 'insumo' => 'SINTETICO CELESTE X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 139, 'insumo' => 'SINTETICO GRIS CEMENTO X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 140, 'insumo' => 'SINTETICO NARANJA X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 141, 'insumo' => 'SINTETICO NARANJA X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 142, 'insumo' => 'PINCEL N 15', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 143, 'insumo' => 'SINTETICO GRIS ESPECIAL X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 144, 'insumo' => 'SINTETICO GRIS X 10 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 145, 'insumo' => 'SINTETICO GRIS X 4LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 146, 'insumo' => 'PINCEL N 20', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 147, 'insumo' => 'RODILLO 10 CM', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 148, 'insumo' => 'RODILLO 17 CM', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 149, 'insumo' => 'PINTURA PISO GRIS DE 10 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 150, 'insumo' => 'RODILLO 22 CM', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 151, 'insumo' => 'PINTURA PISO VERDE DE 25KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 152, 'insumo' => 'PINTURA PISO VERDE DE 10 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 153, 'insumo' => 'PAN DE BREA X 20 KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 154, 'insumo' => 'PINCEL N 40', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 155, 'insumo' => 'RODILLO 5 CM', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 156, 'insumo' => 'PINTURA PISO GRIS DE 25KG', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 157, 'insumo' => 'SINTETICO NEGRO BRILLANTE X 4 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 158, 'insumo' => 'LIJAS X 60', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 159, 'insumo' => 'LIJAS X 100', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 160, 'insumo' => 'LIJAS X 80', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 161, 'insumo' => 'MEMBRANA EN PASTA X 20 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 162, 'insumo' => 'LIJAS X 50', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 163, 'insumo' => 'LATEX VIOLETA X 4 LTS', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 164, 'insumo' => 'SINTETICO NEGRO BRILLANTE X 20 LT', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 165, 'insumo' => 'LIJAS X 150', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 166, 'insumo' => 'LIJAS X 180', 'id_categoria' => 2, 'unidad' => 'unidad'],
            ['id' => 167, 'insumo' => 'BOLSA DE ESTOPA', 'id_categoria' => 2, 'unidad' => 'unidad'],

            // Categoría 3 - ACEITES (IDs 168-182)
            ['id' => 168, 'insumo' => 'ACEITE 5W- 40', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 169, 'insumo' => 'ACEITE 5W -30 AC 3', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 170, 'insumo' => 'ACEITE 10W-40', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 171, 'insumo' => 'ACEITE 15 W 40', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 172, 'insumo' => 'ACEITE 15W 40 DE 1000 LT', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 173, 'insumo' => 'ACEITE 20 W 50', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 174, 'insumo' => 'ACEITE 80 W 90', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 175, 'insumo' => 'ACEITE ATF', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 176, 'insumo' => 'ACEITE ATF 295', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 177, 'insumo' => 'ACEITE H 68', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 178, 'insumo' => 'ACEITE H 32', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 179, 'insumo' => 'ACEITE H 46', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 180, 'insumo' => 'GRASA DE LITIO', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 181, 'insumo' => 'UREA X 1000 LTS', 'id_categoria' => 3, 'unidad' => 'unidad'],
            ['id' => 182, 'insumo' => 'ACEITE 2T PARA ECHO', 'id_categoria' => 3, 'unidad' => 'unidad'],

            // Categoría 4 - BATERÍAS (IDs 183-190)
            ['id' => 183, 'insumo' => 'BATERIA 12 X 45', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 184, 'insumo' => 'BATERIA 12 X 65', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 185, 'insumo' => 'BATERIA 12 X 50', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 186, 'insumo' => 'BATERIA 12 X 75', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 187, 'insumo' => 'BATERIA 12 X 90', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 188, 'insumo' => 'BATERIA 12 X 110', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 189, 'insumo' => 'BATERIA 12 X 180', 'id_categoria' => 4, 'unidad' => 'unidad'],
            ['id' => 190, 'insumo' => 'BATERIA 12 X 200', 'id_categoria' => 4, 'unidad' => 'unidad'],
        ];

        // Parte 2: Categorías 5-13 (IDs 191-709)
        $insumos_parte2 = [
            // Categoría 5 - ABRAZADERAS Y ACCESORIOS (IDs 191-351)
            ['id' => 191, 'insumo' => 'ABRAZADERA DN 100 CLASE 3 - DE 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 192, 'insumo' => 'ABRAZADERAS DE 100x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 193, 'insumo' => 'ABRAZADERAS DE 200x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 194, 'insumo' => 'ABRAZADERAS DE 250x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 195, 'insumo' => 'ABRAZADERAS DE 300x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 196, 'insumo' => 'ABRAZADERAS DE 350', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 197, 'insumo' => 'ABRAZADERAS DE 60x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 198, 'insumo' => 'ABRAZADERAS DE 75x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 199, 'insumo' => 'ABRAZADERAS DE150x1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 200, 'insumo' => 'ABRAZADERAS PVC DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 201, 'insumo' => 'ABRAZADERA DE PVC 160 C/REDUCCION A 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 202, 'insumo' => 'ABRAZADERA C/BULONES 0,75 x 1"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 203, 'insumo' => 'ABRAZADERA C/BULONES 0,75 x 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 204, 'insumo' => 'ABRAZADERA C/BULONES 0,75 x 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 205, 'insumo' => 'ABRAZADERA C/BULONES 110 x 1"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 206, 'insumo' => 'JUNTAMAS AC-C5-7-75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 207, 'insumo' => 'ABRAZADERA C/BULONES 110 x 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 208, 'insumo' => 'ABRAZADERA DE HIERRO X 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 209, 'insumo' => 'ABRAZADERA C/BULONES 110 x 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 210, 'insumo' => 'ABRAZADERA DE HIERRO X 100', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 211, 'insumo' => 'ABRAZADERAS DN 75 CLASE 3 - DE 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 212, 'insumo' => 'ABRAZADERA DN 100 CLASE 3 - DE 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 213, 'insumo' => 'ABRAZADERA DN 100 CLASE 3 - DE 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 214, 'insumo' => 'ABRAZADERA ESTRIBO 150 X 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 215, 'insumo' => 'ABRAZADERA ESTRIBO 150 X 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 216, 'insumo' => 'ABRAZADERA DN 75 CLASE 3 - DE 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 217, 'insumo' => 'CAÑO 75  X 2.2 JUNTA ELASTICA CLASE 6', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 218, 'insumo' => 'ACCESORIO HEMBRA ROSCA ESPIGA 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 219, 'insumo' => 'ACCESORIO MACHO ROSCA ESPIGA 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 220, 'insumo' => 'CAÑO 75  X 3.6 JUNTA ELASTICA CLASE 10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 221, 'insumo' => 'CAÑO 110 X 2.2 JUNTA ELASTICA CLASE 6', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 222, 'insumo' => 'CAÑO POLIETILENO 3/4"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 223, 'insumo' => 'CAÑO 160 X 3.6 JUNTA ELASTICA CLASE 10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 224, 'insumo' => 'CAÑO POLIETILENO 1 1/2"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 225, 'insumo' => 'CAÑO 160 X 2.2 JUNTA ELASTICA CLASE 6', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 226, 'insumo' => 'CAÑO 110 X 3.6 JUNTA ELASTICA CLASE 10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 227, 'insumo' => 'CAÑO POLIETILENO 1"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 228, 'insumo' => 'CAÑO POLIETILENO 1/2"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 229, 'insumo' => 'CONECTOR BLANCO NYLON CONO ESPIGA 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 230, 'insumo' => 'CAÑO POLIETILENO 2"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 231, 'insumo' => 'CAÑO VERDES P/POZO X 6MTRS', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 232, 'insumo' => 'CRUZ PVC DE 75X75 CL10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 233, 'insumo' => 'CONECTOR NEGRO ESPIGA C/CONO 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 234, 'insumo' => 'CONECTOR NEGRO ESPIGA C/CONO 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 235, 'insumo' => 'CURVA A 90 JTA .ELASTICA 090', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 236, 'insumo' => 'CURVA A 45 JTA .ELASTICA 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 237, 'insumo' => 'CURVA A 90 JTA .ELASTICA 075', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 238, 'insumo' => 'CURVA A 90 JTA .ELASTICA 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 239, 'insumo' => 'ESPIGA R/MACHO BRONCE 1/2"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 240, 'insumo' => 'ESPIGA R/MACHO BRONCE 1"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 241, 'insumo' => 'JUNTAMAS 500 A/C', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 242, 'insumo' => 'FERULAS DE 19 (3/4)', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 243, 'insumo' => 'JUNTAMAS SM C/5-7 100 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 244, 'insumo' => 'JUNTAMAS SM C/5-7 075 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 245, 'insumo' => 'ESPIEGA CON ROSCA MACHO 1" PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 246, 'insumo' => 'ESPIGA CON ROSCA HERMBRA 3/4 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 247, 'insumo' => 'JUNTAMAS C/5 075 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 248, 'insumo' => 'ESPIGA CON ROSCA MACHO 3/4 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 249, 'insumo' => 'JUNTAMAS C/5 100 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 250, 'insumo' => 'FERULAS DE 13 (1/2)', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 251, 'insumo' => 'JUNTAMAS C/5 125 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 252, 'insumo' => 'JUNTAMAS C/5 150 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 253, 'insumo' => 'JUNTAMAS DE PLASTICO DN-100 CLASE 5-7', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 254, 'insumo' => 'JUNTAMAS PLASTICA AC 175 3-5', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 255, 'insumo' => 'JUNTAMAS DE 3/4 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 256, 'insumo' => 'JUNTAMAS DE 1" PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 257, 'insumo' => 'JUANTAMAS PVC de 63', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 258, 'insumo' => 'JUNTAMAS PLASTICA DN 100 CLASE 7-10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 259, 'insumo' => 'JUNTAMAS DE PVC DE 90', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 260, 'insumo' => 'JUNTAMAS DE PLASTICO DN-75 CLASE 5-7', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 261, 'insumo' => 'JUNTAMAS C/5 200 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 262, 'insumo' => 'JUNTAMAS C/5 300 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 263, 'insumo' => 'JUNTAMAS C/5 250 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 264, 'insumo' => 'JUNTAMAS C/5-7 300 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 265, 'insumo' => 'JUNTAMAS C/5-7 350 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 266, 'insumo' => 'JUNTAMAS C/5 350 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 267, 'insumo' => 'JUNTAMAS C/5-7 150 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 268, 'insumo' => 'JUNTAMAS PLASTICA DN-150 CLASE 7-10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 269, 'insumo' => 'JUNTAMAS C/5-7 060 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 270, 'insumo' => 'JUNTAMAS C/5-7 250 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 271, 'insumo' => 'JUNTAMAS DE 1/2 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 272, 'insumo' => 'JUNTAMAS C/5 300 x PVC 075', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 273, 'insumo' => 'JUNTAMAS PVC EXTRA LARGA DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 274, 'insumo' => 'JUNTAMAS DE PLASTICO DN-100 CLASE 3', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 275, 'insumo' => 'JUNTAMAS C/5-7 125 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 276, 'insumo' => 'JUNTAMAS C/5-7 200 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 277, 'insumo' => 'JUNTAMAS SM C/5-7 060 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 278, 'insumo' => 'JUNTAMAS AC-C5-75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 279, 'insumo' => 'JUNTAMAS AC-C5-100', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 280, 'insumo' => 'JUNTAMAS P/PVC 160', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 281, 'insumo' => 'JUNTAMAS AC-C5-125', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 282, 'insumo' => 'JUNTAMAS PVC DE 200', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 283, 'insumo' => 'JUNTAMAS PLASTICA 250', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 284, 'insumo' => 'JUNTAMAS DE PVC 350 EXTRA LARGA', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 285, 'insumo' => 'JUNTAMAS SM C/5-7 150 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 286, 'insumo' => 'JUNTAMAS SM C/5-7 250 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 287, 'insumo' => 'JUNTAMAS PLASTICA P/PVC 140', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 288, 'insumo' => 'JUNTAMAS DE PVC 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 289, 'insumo' => 'JUNTAMAS AC-C5-200', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 290, 'insumo' => 'JUNTAMAS AC-C5-300', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 291, 'insumo' => 'JUNTAMAS AC-C5-250', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 292, 'insumo' => 'JUNTAMAS PLASTICA DE 315 EXTRA LARGA', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 293, 'insumo' => 'JUNTAMAS AC-C5-150', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 294, 'insumo' => 'ESPIGA R/MACHO BRONCE 3/4"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 295, 'insumo' => 'JUANTAMAS PLASTICA DE 75 P/PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 296, 'insumo' => 'JUNTAMAS AC-C5-350', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 297, 'insumo' => 'JUNTAMAS AC-C5-7-100', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 298, 'insumo' => 'JUNTAMAS AC-C5-7-125', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 299, 'insumo' => 'JUNTAMAS AC-C5-7-150', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 300, 'insumo' => 'JUNTAMAS AC-C5-7-200', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 301, 'insumo' => 'JUNTAMAS AC-C5-7-250', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 302, 'insumo' => 'JUNTAMAS AC-C5-7-300', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 303, 'insumo' => 'JUNTAMAS AC-C5-7-350', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 304, 'insumo' => 'JUNTAMAS AC-C5-7-450', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 305, 'insumo' => 'JUATAMAS MR 1/2 LARGO', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 306, 'insumo' => 'JUNTAMAS MR 3/4 LARGO', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 307, 'insumo' => 'JUNTAMAS -AC-C5-7-300 C/SALIDA', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 308, 'insumo' => 'JUNTAMAS H F 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 309, 'insumo' => 'LLAVE ESFERICA DE 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 310, 'insumo' => 'LLAVE ESFERICA DE 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 311, 'insumo' => 'LLAVE C/ROSCA 3"', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 312, 'insumo' => 'LLAVE MAESTRA DE BRONCE DE (1/2)', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 313, 'insumo' => 'LLAVE MAESTRA DE BRONCE DE (3/4)', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 314, 'insumo' => 'RAMAL TEE DIAMANTADO 140 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 315, 'insumo' => 'RAMAL TEE DIAMANTADO 160 PVC', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 316, 'insumo' => 'REDUCCION JTA.ELASTICA 160x110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 317, 'insumo' => 'REDUCCION PVC DE 110X75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 318, 'insumo' => 'REDUCCION PVC DE 110X75 CL10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 319, 'insumo' => 'REDUCCION PVC DE 90x75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 320, 'insumo' => 'REDUCCIONES 140 x 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 321, 'insumo' => 'REDUCCIONES 160 x 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 322, 'insumo' => 'TAPA HEMBRA DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 323, 'insumo' => 'TAPA HEMBRA DE 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 324, 'insumo' => 'TAPA HEMBRA DE 160', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 325, 'insumo' => 'TAPON DE 1/2', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 326, 'insumo' => 'TAPON DE 3/4', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 327, 'insumo' => 'TAPONES PVC DE 75 CL10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 328, 'insumo' => 'TEE HF DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 329, 'insumo' => 'TEE INYECTADA PVC DE 160x160', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 330, 'insumo' => 'TEE INYECTADA PVC DE 160x75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 331, 'insumo' => 'TEE PVC DE 75X75 CL10', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 332, 'insumo' => 'TRANSICION PVC DE 110 x 110', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 333, 'insumo' => 'TRANSICION PVC DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 334, 'insumo' => 'TUBO DE PVC DE 75 x 6 MTS', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 335, 'insumo' => 'VALVULA ESCLUSA PVC DE 160', 'id_categoria' => 5, 'unidad' => 'unidad'],
            ['id' => 336, 'insumo' => 'VALVULA ESCLUSA PVC DE 75', 'id_categoria' => 5, 'unidad' => 'unidad'],

            // Categoría 6 - CAÑOS BLANCOS Y ACCESORIOS (IDs 337-351)
            ['id' => 337, 'insumo' => 'CAÑO BLANCO 110 X 2MM X4M', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 338, 'insumo' => 'CAÑO BLANCO 110 X 3.2MM X6M', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 339, 'insumo' => 'CAÑO BLANCO DE 160', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 340, 'insumo' => 'CAÑO BLANCO DE 200', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 341, 'insumo' => 'ACOPLE RAPIDO DE ALUMINIO 3"', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 342, 'insumo' => 'ACOPLE RAPIDO DE PVC DE 3"', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 343, 'insumo' => 'ACOPLE RAPIDO DE PVC DE 4" C/SALIDA ESPIGA DE 3"', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 344, 'insumo' => 'CUPLA DE REDUCCION 140 X110', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 345, 'insumo' => 'CUPLA DE REDUCCION 160 X110', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 346, 'insumo' => 'CUPLAS 110', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 347, 'insumo' => 'CURVA DE 160 X 160', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 348, 'insumo' => 'CURVA DE 75', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 349, 'insumo' => 'CURVA DE 90', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 350, 'insumo' => 'CURVAS 45 X 110', 'id_categoria' => 6, 'unidad' => 'unidad'],
            ['id' => 351, 'insumo' => 'REDUCCION 160-110', 'id_categoria' => 6, 'unidad' => 'unidad'],

            // Categoría 7 - HERRAMIENTAS Y VARIOS (IDs 352-466)
            ['id' => 352, 'insumo' => 'ALAMBRE DE FARDO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 353, 'insumo' => 'ALAMBRE GALVANIZADO NUMERO 13', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 354, 'insumo' => 'ARRANCA MOTORES', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 355, 'insumo' => 'BALDES DE ALBAÑIL', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 356, 'insumo' => 'BOLSA DE ESTOPA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 357, 'insumo' => 'Candado Nª 30', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 358, 'insumo' => 'Candado Nª 40', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 359, 'insumo' => 'Candado Nª 50', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 360, 'insumo' => 'CARRETILLA DUROLL 70', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 361, 'insumo' => 'CANILLA PLASTICA DE 1/2', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 362, 'insumo' => 'CANILLA PLASTICA DE 3/4', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 363, 'insumo' => 'CHOCLAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 364, 'insumo' => 'CIANO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 365, 'insumo' => 'CINTA AISLADORA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 366, 'insumo' => 'CINTA METRICA X 5MTS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 367, 'insumo' => 'CINTA PAPEL 24mm', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 368, 'insumo' => 'CINTA PAPEL 48mm', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 369, 'insumo' => 'CLAVOS DE GANCHO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 370, 'insumo' => 'COLA ADHESIVA X 4KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 371, 'insumo' => 'COLA ADHESIVO X 1KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 372, 'insumo' => 'COLA ADHESIVO X 6KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 373, 'insumo' => 'CORTA FIERROS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 374, 'insumo' => 'CUCHARAS DE ALBAÑIL', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 375, 'insumo' => 'CUTTER', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 376, 'insumo' => 'DESENGRASANTE X 5 LT', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 377, 'insumo' => 'ESCALERA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 378, 'insumo' => 'ESCUADRA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 379, 'insumo' => 'FAJA LUMBAR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 380, 'insumo' => 'FASTIX ALTA TEMPERATURA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 381, 'insumo' => 'FASTIX COMUN', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 382, 'insumo' => 'FILTRO DE ALBAÑIL', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 383, 'insumo' => 'FRATACHO DE MADERA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 384, 'insumo' => 'GRINFA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 385, 'insumo' => 'GUANTES ACEITERA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 386, 'insumo' => 'GUANTES DESCARNE', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 387, 'insumo' => 'GUANTES DIELECTRICOS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 388, 'insumo' => 'GUANTES MOTEADOS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 389, 'insumo' => 'GUANTES NITRILOTELA ( S.E )', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 390, 'insumo' => 'GUANTES OBRAS SANITARIAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 391, 'insumo' => 'GUANTES VAQUETA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 392, 'insumo' => 'HOJAS SIERRA 18D', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 393, 'insumo' => 'HORQUILLAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 394, 'insumo' => 'LAPIZ CARPINTERO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 395, 'insumo' => 'LINTERNAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 396, 'insumo' => 'LIQUIDO DE FRENO X 1L', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 397, 'insumo' => 'LIQUIDO DE FRENO X 200CM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 398, 'insumo' => 'LLANAS DE PLASTICO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 399, 'insumo' => 'LLAVE DE CAÑO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 400, 'insumo' => 'LOCTITE', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 401, 'insumo' => 'LUBRIGOM X 20 LT', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 402, 'insumo' => 'LUBRIGOM X 4LT', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 403, 'insumo' => 'MACHETES', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 404, 'insumo' => 'MANDRILES', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 405, 'insumo' => 'MANGUERA DE 1', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 406, 'insumo' => 'MANGUERA DE 1 1/2', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 407, 'insumo' => 'MANGUERA DE 1/2', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 408, 'insumo' => 'MANGUERA DE 3/4', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 409, 'insumo' => 'MARTILLO BOLITA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 410, 'insumo' => 'MARTILLO SACA CLAVOS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 411, 'insumo' => 'MASILLA DE 10 KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 412, 'insumo' => 'MAZA DE 1 KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 413, 'insumo' => 'MAZA DE 1/2 KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 414, 'insumo' => 'MAZA DE 10 KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 415, 'insumo' => 'MAZA DE 2 KG', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 416, 'insumo' => 'MECHAS 10 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 417, 'insumo' => 'MECHAS 10 MM W', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 418, 'insumo' => 'MECHAS 10.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 419, 'insumo' => 'MECHAS 11 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 420, 'insumo' => 'MECHAS 11.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 421, 'insumo' => 'MECHAS 12 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 422, 'insumo' => 'MECHAS 12 MM W', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 423, 'insumo' => 'MECHAS 12.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 424, 'insumo' => 'MECHAS 3 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 425, 'insumo' => 'MECHAS 3.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 426, 'insumo' => 'MECHAS 4 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 427, 'insumo' => 'MECHAS 4.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 428, 'insumo' => 'MECHAS 5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 429, 'insumo' => 'MECHAS 5.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 430, 'insumo' => 'MECHAS 6 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 431, 'insumo' => 'MECHAS 6 MM W', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 432, 'insumo' => 'MECHAS 6.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 433, 'insumo' => 'MECHAS 7 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 434, 'insumo' => 'MECHAS 7.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 435, 'insumo' => 'MECHAS 8 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 436, 'insumo' => 'MECHAS 8 MM W', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 437, 'insumo' => 'MECHAS 8.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 438, 'insumo' => 'MECHAS 9 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 439, 'insumo' => 'MECHAS 9.5 MM AR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 440, 'insumo' => 'Metro madera', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 441, 'insumo' => 'NIVEL DE MANO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 442, 'insumo' => 'PALA ANCHA ESTAMPADA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 443, 'insumo' => 'PALA ANCHA FORJADA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 444, 'insumo' => 'PALA PUNTA ESTAMPADA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 445, 'insumo' => 'PALA PUNTA FORJADA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 446, 'insumo' => 'PALA PUNTA FORJADA MANGO HIERRO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 447, 'insumo' => 'PICO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 448, 'insumo' => 'PINZAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 449, 'insumo' => 'PIOLIN', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 450, 'insumo' => 'PLOMADAS x 400 gr', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 451, 'insumo' => 'POXILINA', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 452, 'insumo' => 'PRECINTO 150 MM X 3.6 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 453, 'insumo' => 'PRECINTO 300 MM X 4.8 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 454, 'insumo' => 'PRECINTO 350 MM X 7.6 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 455, 'insumo' => 'PRECINTO 400 MM X 7.5 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 456, 'insumo' => 'PRECINTO 400 MM X 7.6 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 457, 'insumo' => 'PRECINTO 350 MM X 9.5 MM', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 458, 'insumo' => 'ROLLO CINTA DE PELIGRO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 459, 'insumo' => 'ROLLO DE NYLON DE 1MTS  X 50 MTS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 460, 'insumo' => 'ROLLO DE NYLON DE 2MTS X 50 MTS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 461, 'insumo' => 'SELLA JUNTAS', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 462, 'insumo' => 'SILICONA EN CARTUCHO', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 463, 'insumo' => 'SILICONA TRANSPARENTE POR 25 GR', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 464, 'insumo' => 'TANZA DE ALBAÑIL', 'id_categoria' => 7, 'unidad' => 'unidad'],
            ['id' => 465, 'insumo' => 'TIJERA CORTA PERNO', 'id_categoria' => 7, 'unidad' => 'unidad'],

            // Categoría 8 - CUCHILLAS Y PERNOS (IDs 466-471)
            ['id' => 466, 'insumo' => 'CUCHILLAS X 7 AGUJEROS', 'id_categoria' => 8, 'unidad' => 'unidad'],
            ['id' => 467, 'insumo' => 'CUCHILLAS X 8 AGUJEROS', 'id_categoria' => 8, 'unidad' => 'unidad'],
            ['id' => 468, 'insumo' => 'CUCHILLAS X 11 AGUJEROS', 'id_categoria' => 8, 'unidad' => 'unidad'],
            ['id' => 469, 'insumo' => 'CUCHILLAS X 13 AGUJEROS', 'id_categoria' => 8, 'unidad' => 'unidad'],
            ['id' => 470, 'insumo' => 'CUCHILLAS X 15 AGUJEROS', 'id_categoria' => 8, 'unidad' => 'unidad'],
            ['id' => 471, 'insumo' => 'PERNOS P/UÑAS', 'id_categoria' => 8, 'unidad' => 'unidad'],

            // Categoría 9 - ELECTRICIDAD (IDs 472-617)
            ['id' => 472, 'insumo' => 'ADAPTADORES PARA LAMPARA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 473, 'insumo' => 'BAEL LAMPARA LED X 150 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 474, 'insumo' => 'BASTIDOR RECTANCULAR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 475, 'insumo' => 'BICHAS HEMBRAS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 476, 'insumo' => 'BOLTIAMPERIMETRO TRIFASICO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 477, 'insumo' => 'CABLE 1 X 4 CELESTE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 478, 'insumo' => 'CABLE 1 X 4 MARRON', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 479, 'insumo' => 'CABLE ACOMETIDA 2X10 ALUMINIO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 480, 'insumo' => 'CABLE ACOMETIDA 2X16 ALUMINIO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 481, 'insumo' => 'CABLE ACOMETIDA 2x4 COBRE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 482, 'insumo' => 'CABLE ACOMETIDA 2X6 ALUMINIO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 483, 'insumo' => 'CABLE ACOMETIDA 2X6 COBRE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 484, 'insumo' => 'CABLE ACOMETIDA 4 X 10 COBRE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 485, 'insumo' => 'CABLE ACOMETIDA 4X16 COBRE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 486, 'insumo' => 'CABLE PREENSAMBLADO 2X 6 (COBRE) 1 ROLLO 1000 MSTRO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 487, 'insumo' => 'ROLLO DE CABLE 1X2,5 CELESTE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 488, 'insumo' => 'CABLE PUESTO A TIERRA 1 X 16MM ROLLO 2X100 MTROS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 489, 'insumo' => 'CABLE SUBTERRANEO 1 X 120 ROLLO DE 120 MSTRO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 490, 'insumo' => 'CABLE ROJO 6MM', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 491, 'insumo' => 'CABLE SUBTERRANEO 2 X 4MM ROLLO 2 DE 700 MSTR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 492, 'insumo' => 'CABLE SUBTERRANEO DE 5 X 2,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 493, 'insumo' => 'CABLE SUBTERRANEO 4 X 10', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 494, 'insumo' => 'CABLE SUBTERRANEO 4 X 2,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 495, 'insumo' => 'CAJA DE PASE 165X165X80 BLANCA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 496, 'insumo' => 'CAJA CHAPA 10X10 CON TAPA DE CHAPA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 497, 'insumo' => 'CAJA CHAPA MIÑON CON TAPA DE CHAPA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 498, 'insumo' => 'CAJA TERMINA 8 BOCAS CON TAPA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 499, 'insumo' => 'CAJA PVC EXTERIOR 2 MODULOS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 500, 'insumo' => 'CAJA RECTAGULAR/OCTOGONAL LIVIANA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 501, 'insumo' => 'CAÑO REDONDO 60 MM / 2"', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 502, 'insumo' => 'CAJAS EXTERIOR P/ TABLERO RIEL Y TAPA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 503, 'insumo' => 'CAÑO REDONDO DE 50MM', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 504, 'insumo' => 'CAÑO REDONDO 90 MM /3"', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 505, 'insumo' => 'CONECTOR TUBO PVC 25MM', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 506, 'insumo' => 'CAÑO REDONDE 115 MM / 4"', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 507, 'insumo' => 'CAÑO REDONDO 75 MM / 2 1/2"', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 508, 'insumo' => 'CINTA ADHESIVA PVC NEGRAS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 509, 'insumo' => 'CAÑO REDONDO DE 100 MM', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 510, 'insumo' => 'CONTACTOR 50AMP 220W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 511, 'insumo' => 'CONTACTOR 20AMP 220W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 512, 'insumo' => 'CONTACTOR 401', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 513, 'insumo' => 'DEMALEC REFLECTORES', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 514, 'insumo' => 'CONTACTOR P/16A BOBINA 380', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 515, 'insumo' => 'CONTACTOR TRIPOLAR 40 X 220W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 516, 'insumo' => 'DIYUNTOR 63', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 517, 'insumo' => 'DISYUNTOR 2X25(A)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 518, 'insumo' => 'DISYUNTOR 2X40(A)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 519, 'insumo' => 'FAROLA DE COLGAR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 520, 'insumo' => 'FAROLAS COLONIAL', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 521, 'insumo' => 'FAROLA PESCANTE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 522, 'insumo' => 'ROLLO CABLE 1 X 6 NEGRO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 523, 'insumo' => 'GABINETE ESTANCO METAL 300X450X210', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 524, 'insumo' => 'REFLECTOR LED 10W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 525, 'insumo' => 'PRESINTO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 526, 'insumo' => 'FUSIBLE 10AMP', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 527, 'insumo' => 'FOTOCONTROL', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 528, 'insumo' => 'GABINETE ESTANCO METAL 300X450X225', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 529, 'insumo' => 'GABINETE 300X450X150', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 530, 'insumo' => 'GABINETE ESTANCO METAL 320X420X200', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 531, 'insumo' => 'GABINETE 500X400X210', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 532, 'insumo' => 'GABINETE ESTANCO METAL 450X450X120', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 533, 'insumo' => 'GABINETE ESTANCO METAL 450X450X225', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 534, 'insumo' => 'IT 2X25', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 535, 'insumo' => 'PORTA LAMPARA C/CHICOTE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 536, 'insumo' => 'MACROLED LAMPARA LED 90 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 537, 'insumo' => 'MACROLED REFLECTORES LED X 200 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 538, 'insumo' => 'MACROLED REFLECTORES LED X 200 W CALIDOS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 539, 'insumo' => 'LAMPARA STRAMP LED 150W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 540, 'insumo' => 'NEAELEC LAMPARA LED 150 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 541, 'insumo' => 'LAMPARA 10WTS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 542, 'insumo' => 'GABINETE ESTANCO METAL 450X600X100', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 543, 'insumo' => 'GABINETE METALICO 30X30X30', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 544, 'insumo' => 'GABINETE ESTANCO METAL 600X400X210', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 545, 'insumo' => 'INGERMAR LAMPARA LED X 150 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 546, 'insumo' => 'INTERELEC LAMPARA LED 50 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 547, 'insumo' => 'GABINETE METALICO 50X40X16', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 548, 'insumo' => 'GRANPAS P/PESCANTE C/TORNILLO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 549, 'insumo' => 'LAMPARAS LED 100W CALIDA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 550, 'insumo' => 'HEBILLA DE ACERO 3/4', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 551, 'insumo' => 'ID 2X40', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 552, 'insumo' => 'MACROLED LAMPARA LED 38 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 553, 'insumo' => 'LLAVES DE PUNTO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 554, 'insumo' => 'PORTA LAMPARA COMUN GUIRNALDAS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 555, 'insumo' => 'INTERRUPTOR CM 25', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 556, 'insumo' => 'HIERRO PESCANTES', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 557, 'insumo' => 'I.LED LAMPARA LED X 160', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 558, 'insumo' => 'PRENSA CABLE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 559, 'insumo' => 'ROLLO CABLE 1X25', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 560, 'insumo' => 'ROLLO DE CABLE 1 X 6 (CELESTE)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 561, 'insumo' => 'OJO DE BUEY LED VERDE 20', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 562, 'insumo' => 'ROLLO DE CABLE 1X1,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 563, 'insumo' => 'PHILIPS LAMPARA LED X 150 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 564, 'insumo' => 'PK', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 565, 'insumo' => 'PLAFON LED 24W CUADRADO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 566, 'insumo' => 'REFLECTORES LED 100W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 567, 'insumo' => 'ROLLO CABLE 1 X 6 (MARRON)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 568, 'insumo' => 'OJO DE BUEY LED ROJO 20', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 569, 'insumo' => 'NRV LAMPARA LED 100 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 570, 'insumo' => 'ROLLO DE CABLE 1X1.5 BLANCO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 571, 'insumo' => 'ROLLO DE CABLE 1X1.5 ROJO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 572, 'insumo' => 'ROLLO DE CABLE 1X1.5 CELESTE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 573, 'insumo' => 'PK FUSIBLE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 574, 'insumo' => 'ROLLO DE CABLE 1X1,5 VERDE/AMARILLO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 575, 'insumo' => 'FAROLES 100W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 576, 'insumo' => 'MACROLED REFLECTORES LED X 240 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 577, 'insumo' => 'ROLLO DE CABLE 1X2,5 NEGRO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 578, 'insumo' => 'ROLLO DE CABLE 1X2,5 VERDE/AMARILLO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 579, 'insumo' => 'ROLLO DE CABLE 1X2.5 MARRON', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 580, 'insumo' => 'ROLLO DE CABLE 1X2.5 NEGRO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 581, 'insumo' => 'ROLLO DE CABLE 1X2.5 ROJO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 582, 'insumo' => 'ROLLO DE CABLE 2X1,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 583, 'insumo' => 'ROLLO DE CABLE 2X1,5 TPR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 584, 'insumo' => 'ROLLO DE CABLE 2X16(ALUMINIO)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 585, 'insumo' => 'ROLLO DE CABLE 2X2,5 TPR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 586, 'insumo' => 'ROLLO DE CABLE 4X1,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 587, 'insumo' => 'ROLLO DE CABLE 4X2,5 TPR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 588, 'insumo' => 'ROLLO DE CABLE 5 x 2,5', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 589, 'insumo' => 'ROLLO DE CABLE CONCENTRICO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 590, 'insumo' => 'ROLLO DE CINTA AUTOSOLDABLE', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 591, 'insumo' => 'ROLLO DE CINTA NEGRA 3M', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 592, 'insumo' => 'SILVER LIGHT LAMPARA LED 100 W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 593, 'insumo' => 'TABLERO EXTERIOR DE 4 BOCAS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 594, 'insumo' => 'TABLERO MONOFASICO', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 595, 'insumo' => 'TAPA RECTANGULAR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 596, 'insumo' => 'TERMICA 10 A', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 597, 'insumo' => 'TERMICA 10 A', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 598, 'insumo' => 'TERMICA 2 X 16', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 599, 'insumo' => 'TERMICA 2 X 25', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 600, 'insumo' => 'TERMICA 2 x 25( A)', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 601, 'insumo' => 'TERMICA 4X16', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 602, 'insumo' => 'TERMICA C40 X 4 BOCA', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 603, 'insumo' => 'TERMICAS 1 X 6', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 604, 'insumo' => 'TERMICAS 2 X 10', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 605, 'insumo' => 'TERMICAS 4 X 10', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 606, 'insumo' => 'TERMICAS 4X63', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 607, 'insumo' => 'TERMICAS DE 40 A', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 608, 'insumo' => 'TETRAPOLAR 4X 40', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 609, 'insumo' => 'TOMA EXTERIOR', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 610, 'insumo' => 'TOMA HEMBRA 4X16 EXT', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 611, 'insumo' => 'TOMA HEMBRA 4X32 EXT', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 612, 'insumo' => 'TOMACORRIENTE ENCAPSULADO EXT', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 613, 'insumo' => 'TOMAS DOBLES EXULT COMPLETOS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 614, 'insumo' => 'TRIFASICO BAW 63AMP', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 615, 'insumo' => 'TUBOS LED DE 18W', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 616, 'insumo' => 'ZOCALOS', 'id_categoria' => 9, 'unidad' => 'unidad'],
            ['id' => 617, 'insumo' => 'ZUNCHOS ACERO', 'id_categoria' => 9, 'unidad' => 'unidad'],

            // Categoría 10 - MATERIALES DE CONSTRUCCIÓN (IDs 618-632)
            ['id' => 618, 'insumo' => 'ARENA', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 619, 'insumo' => 'PIEDRA 10/30', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 620, 'insumo' => 'TOSCA', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 621, 'insumo' => 'CEMENTO X 25', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 622, 'insumo' => 'CEMENTO X 50', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 623, 'insumo' => 'CAL', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 624, 'insumo' => 'MALLAS', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 625, 'insumo' => 'VARILLA DEL 6', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 626, 'insumo' => 'VARILLA DEL 8', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 627, 'insumo' => 'VARILLA DEL 10', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 628, 'insumo' => 'CAÑO HORMIGON 40', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 629, 'insumo' => 'CAÑO HORMIGON 50', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 630, 'insumo' => 'CAÑO HORMIGON 60', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 631, 'insumo' => 'CAÑO HORMIGON 80', 'id_categoria' => 10, 'unidad' => 'unidad'],
            ['id' => 632, 'insumo' => 'CAÑO HORMIGON 100', 'id_categoria' => 10, 'unidad' => 'unidad'],

            // Categoría 11 - HIERROS Y METALES (IDs 633-676)
            ['id' => 633, 'insumo' => 'ANGULO', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 634, 'insumo' => '1/2 X 1/8', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 635, 'insumo' => '3/4 X 1/8', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 636, 'insumo' => '7/8 X 1/8', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 637, 'insumo' => '1 X 3/16', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 638, 'insumo' => '1 1/2 X 3/16', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 639, 'insumo' => 'UPN', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 640, 'insumo' => '0.40', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 641, 'insumo' => '0.60', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 642, 'insumo' => '0.80', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 643, 'insumo' => 'CHAPAS', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 644, 'insumo' => '3/8 DE 1 X 2', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 645, 'insumo' => '18 DE 1,22 X 2,44', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 646, 'insumo' => 'ESTRUCTURAL', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 647, 'insumo' => '100-100 X 3MM ESP', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 648, 'insumo' => '30-30 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 649, 'insumo' => '40-40 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 650, 'insumo' => '20-40 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 651, 'insumo' => '35-35 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 652, 'insumo' => 'METAL DESPLEGADO', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 653, 'insumo' => '500-30-30', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 654, 'insumo' => 'CAÑO REDONDO', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 655, 'insumo' => '45750', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 656, 'insumo' => '1', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 657, 'insumo' => '1 1/2"', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 658, 'insumo' => 'PLANCHUELA', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 659, 'insumo' => '1 1/2 X 1/8', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 660, 'insumo' => '1 X 3/16', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 661, 'insumo' => 'REDONDO LISO (VARILLA)', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 662, 'insumo' => '6 MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 663, 'insumo' => '8 MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 664, 'insumo' => '10 MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 665, 'insumo' => 'HIERRO T', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 666, 'insumo' => '45750', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 667, 'insumo' => '1"', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 668, 'insumo' => '1 1/2', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 669, 'insumo' => 'CAÑO', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 670, 'insumo' => '63 X 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 671, 'insumo' => '4" X 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 672, 'insumo' => '3" X 2MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 673, 'insumo' => '3" X 4MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 674, 'insumo' => '88 X 4MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 675, 'insumo' => '49 X 3MM', 'id_categoria' => 11, 'unidad' => 'unidad'],
            ['id' => 676, 'insumo' => '113 X 3.5 MM', 'id_categoria' => 11, 'unidad' => 'unidad'],

            // Categoría 12 - REPUESTOS MOTOGUADAÑA (IDs 677-704)
            ['id' => 677, 'insumo' => 'Motoguadaña Echo 4605', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 678, 'insumo' => 'Tanza 3mm cuadrada marca Grilon', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 679, 'insumo' => 'Cabezal', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 680, 'insumo' => 'Anillos para carreteles', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 681, 'insumo' => 'Filtro de aire', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 682, 'insumo' => 'Cable de acelador', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 683, 'insumo' => 'Sistema de arranque completo', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 684, 'insumo' => 'Resorte retractil', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 685, 'insumo' => 'Carretel retractil', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 686, 'insumo' => 'Soga arranque (m)', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 687, 'insumo' => 'juego completo de manguera nafta', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 688, 'insumo' => 'Manguera de nafta', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 689, 'insumo' => 'Junta de carburador', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 690, 'insumo' => 'Carburador', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 691, 'insumo' => 'Cilindro', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 692, 'insumo' => 'Protectores facial con rejilla', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 693, 'insumo' => 'Bujias', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 694, 'insumo' => 'Filtro de nafta', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 695, 'insumo' => 'Junta base de cilindro', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 696, 'insumo' => 'Junta de escape deflactor', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 697, 'insumo' => 'Campana de embrague', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 698, 'insumo' => 'Resorte de embrague', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 699, 'insumo' => 'Zapata de embrage', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 700, 'insumo' => 'Empuñadura', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 701, 'insumo' => 'Bobina de encendido', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 702, 'insumo' => 'Grasa', 'id_categoria' => 12, 'unidad' => 'unidad'],
            ['id' => 703, 'insumo' => 'Cuchilla', 'id_categoria' => 12, 'unidad' => 'unidad'],

            // Categoría 13 - REPUESTOS MOTOSIERRA (IDs 705-709) - Nota: ID 704 no existe en tu lista original
            ['id' => 704, 'insumo' => 'rollo de cadena (echo 303 y sthil 194', 'id_categoria' => 13, 'unidad' => 'unidad'],
            ['id' => 705, 'insumo' => 'rollo de cadena (echo 420)', 'id_categoria' => 13, 'unidad' => 'unidad'],
            ['id' => 706, 'insumo' => 'rollo de cadena (echo 620)', 'id_categoria' => 13, 'unidad' => 'unidad'],
            ['id' => 707, 'insumo' => '14"(35cm) .050/1,3mm 3/8 50coraz 9T', 'id_categoria' => 13, 'unidad' => 'unidad'],
            ['id' => 708, 'insumo' => 'Espadas', 'id_categoria' => 13, 'unidad' => 'unidad'],
        ];

        foreach (array_merge($insumos_parte1, $insumos_parte2) as $insumo) {
            DB::table('insumos')->insert([
                'id' => $insumo['id'],
                'insumo' => $insumo['insumo'],
                'id_categoria' => $insumo['id_categoria'],
                'unidad' => $insumo['unidad'],
                'stock_actual' => 0,
                'stock_minimo' => 0,
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}