<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehiculosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('vehiculos')->insert([
            // Vehículos Diesel
            [
                'nro_movil' => 'M-001',
                'vehiculo' => 'Ford F-100',
                'marca' => 'Ford',
                'nro_motor' => 'FD2024XY123456',
                'nro_chasis' => '8AFDT13W1JJ123456',
                'modelo' => 2020,
                'patente' => 'AB123CD',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-001',
                'vencimiento_poliza' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'id_secretaria' => 1,
                'estado' => 'disponible',
                'id_deposito' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-002',
                'vehiculo' => 'Mercedes Benz 1720',
                'marca' => 'Mercedes Benz',
                'nro_motor' => 'MB2023AB789012',
                'nro_chasis' => '9BM6826128R789012',
                'modelo' => 2019,
                'patente' => 'EF456GH',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-002',
                'vencimiento_poliza' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'id_secretaria' => 1,
                'estado' => 'en uso',
                'id_deposito' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-003',
                'vehiculo' => 'Volkswagen Amarok',
                'marca' => 'Volkswagen',
                'nro_motor' => 'VW2022CD345678',
                'nro_chasis' => 'WV1ZZZ2HZJX345678',
                'modelo' => 2021,
                'patente' => 'IJ789KL',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-003',
                'vencimiento_poliza' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addYear()->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-004',
                'vehiculo' => 'Iveco Daily 70C16',
                'marca' => 'Iveco',
                'nro_motor' => 'IV2021EF901234',
                'nro_chasis' => 'ZCFC45A00GS901234',
                'modelo' => 2018,
                'patente' => 'MN012OP',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-004',
                'vencimiento_poliza' => Carbon::now()->addMonths(2)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'id_secretaria' => 1,
                'estado' => 'en reparacion',
                'id_deposito' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vehículos Nafta
            [
                'nro_movil' => 'M-005',
                'vehiculo' => 'Chevrolet S10',
                'marca' => 'Chevrolet',
                'nro_motor' => 'CH2023GH567890',
                'nro_chasis' => '8LBETF3E8KF567890',
                'modelo' => 2022,
                'patente' => 'QR345ST',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-005',
                'vencimiento_poliza' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(9)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-006',
                'vehiculo' => 'Toyota Hilux',
                'marca' => 'Toyota',
                'nro_motor' => 'TY2020IJ234567',
                'nro_chasis' => 'MR0FD22G1K0234567',
                'modelo' => 2020,
                'patente' => 'UV678WX',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-006',
                'vencimiento_poliza' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'en uso',
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-007',
                'vehiculo' => 'Fiat Ducato',
                'marca' => 'Fiat',
                'nro_motor' => 'FT2019KL890123',
                'nro_chasis' => 'ZFA25000005890123',
                'modelo' => 2019,
                'patente' => 'YZ901AB',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-007',
                'vencimiento_poliza' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'id_secretaria' => 3,
                'estado' => 'disponible',
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-008',
                'vehiculo' => 'Renault Kangoo',
                'marca' => 'Renault',
                'nro_motor' => 'RN2021MN456789',
                'nro_chasis' => '8A1FC5H00LL456789',
                'modelo' => 2021,
                'patente' => 'CD234EF',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-008',
                'vencimiento_poliza' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vehículos GNC (Gas)
            [
                'nro_movil' => 'M-009',
                'vehiculo' => 'Fiat Palio Weekend',
                'marca' => 'Fiat',
                'nro_motor' => 'FT2018OP123456',
                'nro_chasis' => '9BD178186J1123456',
                'modelo' => 2018,
                'patente' => 'GH567IJ',
                'tipo_combustible' => 'gas',
                'vencimiento_oblea' => Carbon::now()->addMonths(11)->format('Y-m-d'),
                'nro_poliza' => 'POL-2024-009',
                'vencimiento_poliza' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-010',
                'vehiculo' => 'Volkswagen Gol Trend',
                'marca' => 'Volkswagen',
                'nro_motor' => 'VW2019QR789012',
                'nro_chasis' => '9BWAB45U8KT789012',
                'modelo' => 2019,
                'patente' => 'KL890MN',
                'tipo_combustible' => 'gas',
                'vencimiento_oblea' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'nro_poliza' => 'POL-2024-010',
                'vencimiento_poliza' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'en uso',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-011',
                'vehiculo' => 'Peugeot Partner',
                'marca' => 'Peugeot',
                'nro_motor' => 'PE2020ST345678',
                'nro_chasis' => '8AD5FZH00KS345678',
                'modelo' => 2020,
                'patente' => 'OP123QR',
                'tipo_combustible' => 'gas',
                'vencimiento_oblea' => Carbon::now()->addMonths(14)->format('Y-m-d'),
                'nro_poliza' => 'POL-2024-011',
                'vencimiento_poliza' => Carbon::now()->addMonths(9)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'id_secretaria' => 3,
                'estado' => 'disponible',
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-012',
                'vehiculo' => 'Chevrolet Corsa Classic',
                'marca' => 'Chevrolet',
                'nro_motor' => 'CH2017UV901234',
                'nro_chasis' => '9BGJC75V07B901234',
                'modelo' => 2017,
                'patente' => 'ST456UV',
                'tipo_combustible' => 'gas',
                'vencimiento_oblea' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'nro_poliza' => 'POL-2024-012',
                'vencimiento_poliza' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(5)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // Vehículos adicionales variados
            [
                'nro_movil' => 'M-013',
                'vehiculo' => 'Ford Ranger',
                'marca' => 'Ford',
                'nro_motor' => 'FD2023WX567890',
                'nro_chasis' => '8AFER13W6RJ567890',
                'modelo' => 2023,
                'patente' => 'WX789YZ',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-013',
                'vencimiento_poliza' => Carbon::now()->addYear()->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addYear()->format('Y-m-d'),
                'id_secretaria' => 1,
                'estado' => 'disponible',
                'id_deposito' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-014',
                'vehiculo' => 'Nissan Frontier',
                'marca' => 'Nissan',
                'nro_motor' => 'NS2022YZ234567',
                'nro_chasis' => '3N6PD23Y4ZK234567',
                'modelo' => 2022,
                'patente' => 'AB012CD',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-014',
                'vencimiento_poliza' => Carbon::now()->addMonths(11)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addYear()->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'en uso',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-015',
                'vehiculo' => 'Mercedes Benz Sprinter',
                'marca' => 'Mercedes Benz',
                'nro_motor' => 'MB2021AB890123',
                'nro_chasis' => 'WDB9066121R890123',
                'modelo' => 2021,
                'patente' => 'EF345GH',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-015',
                'vencimiento_poliza' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(9)->format('Y-m-d'),
                'id_secretaria' => 3,
                'estado' => 'disponible',
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-016',
                'vehiculo' => 'Citroen Berlingo',
                'marca' => 'Citroen',
                'nro_motor' => 'CT2020CD456789',
                'nro_chasis' => 'VF7MF9HZE8S456789',
                'modelo' => 2020,
                'patente' => 'IJ678KL',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-016',
                'vencimiento_poliza' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-017',
                'vehiculo' => 'Ford Transit',
                'marca' => 'Ford',
                'nro_motor' => 'FD2019EF123456',
                'nro_chasis' => 'WF0TXXGBTKF123456',
                'modelo' => 2019,
                'patente' => 'MN901OP',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-017',
                'vencimiento_poliza' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(6)->format('Y-m-d'),
                'id_secretaria' => 1,
                'estado' => 'disponible',
                'id_deposito' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-018',
                'vehiculo' => 'Chevrolet Spin',
                'marca' => 'Chevrolet',
                'nro_motor' => 'CH2021GH789012',
                'nro_chasis' => '8LBKS75R0MC789012',
                'modelo' => 2021,
                'patente' => 'QR234ST',
                'tipo_combustible' => 'gas',
                'vencimiento_oblea' => Carbon::now()->addMonths(13)->format('Y-m-d'),
                'nro_poliza' => 'POL-2024-018',
                'vencimiento_poliza' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(10)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'disponible',
                'id_deposito' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-019',
                'vehiculo' => 'Volkswagen Saveiro',
                'marca' => 'Volkswagen',
                'nro_motor' => 'VW2020IJ345678',
                'nro_chasis' => '9BWKB05W8MT345678',
                'modelo' => 2020,
                'patente' => 'UV567WX',
                'tipo_combustible' => 'nafta',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-019',
                'vencimiento_poliza' => Carbon::now()->addMonths(7)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(8)->format('Y-m-d'),
                'id_secretaria' => 2,
                'estado' => 'en uso',
                'id_deposito' => 5,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nro_movil' => 'M-020',
                'vehiculo' => 'Peugeot Boxer',
                'marca' => 'Peugeot',
                'nro_motor' => 'PE2018KL901234',
                'nro_chasis' => 'VF3YEYHZG8V901234',
                'modelo' => 2018,
                'patente' => 'YZ890AB',
                'tipo_combustible' => 'diesel',
                'vencimiento_oblea' => null,
                'nro_poliza' => 'POL-2024-020',
                'vencimiento_poliza' => Carbon::now()->addMonths(3)->format('Y-m-d'),
                'vencimiento_vtv' => Carbon::now()->addMonths(4)->format('Y-m-d'),
                'id_secretaria' => 3,
                'estado' => 'en reparacion',
                'id_deposito' => 8,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}