<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class VehiculosSeeder extends Seeder
{
    /**
     * Secretarías mapeadas:
     *   "Subsecretaría Servicio Publicos"       -> 1 (Servicios Públicos)
     *   "Secretaria de Seguridad"               -> 2 (Seguridad)
     *   "Secretaria Desarrollo de la Comunidad" -> 4 (Desarrollo de la Comunidad)
     *   "Secretaria de Gobierno"                -> 5 (Gobierno)
     *   "Secretaria Educación"                  -> 6 (Educación)
     *
     * Estados: EN USO, BAJA, MANTENIMIENTO
     */
    public function run(): void
    {
        $now = Carbon::now();

        // Vaciar tablas relacionadas y vehiculos
        DB::table('documentos_vehiculos')->delete();
        DB::table('choferes_vehiculos')->delete();
        DB::table('vehiculos')->delete();
        DB::table('tipos_vehiculos')->delete();
        DB::statement('ALTER TABLE vehiculos AUTO_INCREMENT = 1');
        DB::statement('ALTER TABLE tipos_vehiculos AUTO_INCREMENT = 1');

        // Insertar tipos de vehículos
        $tipos = [
            ['id' => 1,  'descripcion' => 'Automóvil'],
            ['id' => 2,  'descripcion' => 'Camioneta'],
            ['id' => 3,  'descripcion' => 'Camión'],
            ['id' => 4,  'descripcion' => 'Motocicleta'],
            ['id' => 5,  'descripcion' => 'Motoniveladora'],
            ['id' => 6,  'descripcion' => 'Tractor'],
            ['id' => 7,  'descripcion' => 'Furgon'],
            ['id' => 8,  'descripcion' => 'Topador'],
            ['id' => 9,  'descripcion' => 'Retroexcavador'],
            ['id' => 10, 'descripcion' => 'Aplanadora'],
            ['id' => 11, 'descripcion' => 'Accesorios'],
            ['id' => 12, 'descripcion' => 'Acoplado'],
            ['id' => 13, 'descripcion' => 'Tanque'],
            ['id' => 14, 'descripcion' => 'Cisterna'],
            ['id' => 15, 'descripcion' => 'Carretón'],
            ['id' => 16, 'descripcion' => 'Casilla'],
            ['id' => 17, 'descripcion' => 'Utilitarios'],
            ['id' => 18, 'descripcion' => 'Ambulancia'],
            ['id' => 19, 'descripcion' => 'Omnibus'],
            ['id' => 20, 'descripcion' => 'Grupo generador'],
            ['id' => 21, 'descripcion' => 'Excavadora'],
            ['id' => 22, 'descripcion' => 'Autoelevador'],
        ];

        foreach ($tipos as $tipo) {
            DB::table('tipos_vehiculos')->insert(array_merge($tipo, [
                'created_at' => $now,
                'updated_at' => $now,
            ]));
        }

        // Constantes de secretaría
        $SP = 1; // Servicios Públicos
        $SE = 2; // Seguridad
        $DC = 4; // Desarrollo de la Comunidad
        $GO = 5; // Gobierno
        $ED = 6; // Educación

        // Constantes de tipo vehículo
        $AUTO = 1; $CETA = 2; $CAMI = 3; $MOTO = 4; $MNIV = 5; $TRAC = 6;
        $FURG = 7; $TOPA = 8; $RETRO = 9; $APLA = 10; $ACCE = 11; $ACOP = 12;
        $TANQ = 13; $CIST = 14; $CARR = 15; $CASI = 16; $UTIL = 17; $AMBU = 18;
        $OMNI = 19; $GENE = 20; $EXCA = 21; $AELV = 22;

        // nro_patrimonio, id_tipo_vehiculo, vehiculo, marca_modelo, nro_motor, nro_chasis, anio, patente, id_secretaria, area, estado
        $vehiculos = [
            ['1',   $AUTO, 'Automóvil',                    'Peugeot 306',                              '10DXBA0003019',             '8AD7BWJZTYP12316',         '2000', 'DOD711',    $SP, 'DESARROLLO SOCIAL',         'EN USO'],
            ['2',   $AUTO, 'Automóvil',                    'Peugeot 504',                              '666475',                    '5342657',                  '1994', 'SME446',    $GO, 'MONITOREO',                 'EN USO'],
            ['4',   $CETA, 'Pick Up',                      'Toyota Hilux',                             '2KD-5369584',               '8AJER32G3B4037724',        '2011', 'KDX524',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['5',   $AUTO, 'Automóvil',                    'Peugeot 306',                              '10CUZ105788',               '8AD7BD9B2T52.72498',       '1997', 'BBW473',    $SE, 'CONTROL URBANO',            'EN USO'],
            ['6',   $CETA, 'Camioneta',                    'Ford Ranger',                              'A57916',                    '1FTCR10A9TTA57 916',       '1997', 'BAT586',    $SP, null,                        'BAJA'],
            ['7',   $CETA, 'Camioneta',                    'Ford F-100',                               '30627914',                  '9BFFF25G6YD036053',        '2000', 'DOD716',    $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['8',   $AUTO, 'Automóvil',                    'Renault Scenic',                           'F4RC746C029116',            '93YJA2A358J958080',        '2008', 'GXP476',    $SP, 'CORRALON',                  'EN USO'],
            ['10',  $CAMI, 'Camion Grua',                  'Ford 6000',                                'PA6478091',                 'KA4LYS95556',              '1980', 'SQN424',    $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['11',  $CETA, 'Camioneta',                    'Ford Courrier',                            'DKKB1915850',               '9BFTSZPPA1B915850',        '2001', 'DTB129',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['12',  $CETA, 'Camioneta',                    'Ford Courrier',                            'RTJWR56045',                'WF03XXBAJWBR56045',        '2001', 'CQQ202',    $SP, null,                        'BAJA'],
            ['13',  $MOTO, 'Motocicleta',                  'Honda',                                    'JC30E88503930',             '9C2JD20108R503930',        '2008', 'EER416',    $SE, 'TRANSITO',                  'EN USO'],
            ['14',  $CETA, 'Camioneta',                    'Chevrolet Luv',                            '593452',                    '8GGTFRF10XA078157',        '1999', 'CWD836',    $SP, 'DELEGACION GOWLAND',        'BAJA'],
            ['16',  $MOTO, 'Motocicleta',                  'Honda',                                    'JC30E88507735',             '90C2JD20108R507735',       '2008', 'EER417',    $SE, 'TRANSITO',                  'EN USO'],
            ['17',  $CAMI, 'Camión Rec.',                  'Mercedes Benz 911',                        '35294510046744',            'no posee',                 '1967', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['18',  $CAMI, 'Camión Rec.',                  'Mercedes Benz 1114',                       '35291110015502',            'no posee',                 '1967', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['19',  $MNIV, 'Motonivelad.',                 'Champion',                                 '45511476',                  'X027539X',                 '1997', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['20',  $MNIV, 'Motonivelad.',                 'Siam 440',                                 '4A149865',                  '23276211',                 '1977', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['21',  $MNIV, 'Motoniveladora',               'Michigan',                                 '87109180',                  '123',                      '2013', 'CMM09',     $SP, 'EQUIPO VIAL',               'MANTENIMIENTO'],
            ['23',  $MNIV, 'Motonivelad.',                 'SEM 160H.',                                'BF6L913 Serie 703481',      '160HB.Serie 31118',        '1991', 'no posee',  $SP, 'EQUIPO VIAL',               'BAJA'],
            ['24',  $TRAC, 'Tractor',                      'Agco Allis',                               'H615237',                   'BTA06041',                 '2008', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['25',  $TRAC, 'Tractor',                      'Agco Allis',                               'H615191',                   '612247974',                '2008', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['26',  $MNIV, 'Motonivelad.',                 'Siam 444',                                 'BFGL913ESL711491',          '2921604501',               '1970', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['27',  $MNIV, 'Motonivelad.',                 'SEM 160H.',                                'BF6L913  Serie 704032',     '160HB  Serie 31124',       '1992', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['28',  $CAMI, 'Camión',                       'Ford 350',                                 'PA6233021',                 'KA9LVL00418',              '1978', 'SUW383',    $SP, 'AGUAS CORRIENTES',          'MANTENIMIENTO'],
            ['29',  $CETA, 'Camioneta',                    'Pick-up 504',                              '679891',                    '8053394',                  '1995', 'ADP288',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['31',  $CAMI, 'Camion Volcador',              'Mercedes Benz',                            '906985U0811872',            '9BM9580729B638414',        '2009', 'IGB370',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['32',  $CAMI, 'Camion Volcador',              'Mercedes Benz',                            '906985U0811832',            '9BM9580729B638365',        '2009', 'IGB369',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['34',  $CAMI, 'Camion Volcador',              'Mercedes Benz',                            '906985U0796396',            '9BM9580729B619462',        '2009', 'IGB375',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['35',  $TOPA, 'Topadora',                     'caterpillar',                              '3N93367',                   'no posee',                 '1980', 'no posee',  $SP, null,                        'BAJA'],
            ['36',  $FURG, 'Furgon1.9TD',                  'Volkswagen',                               'ABL186039',                 'WV1ZZZ70ZXH047231',        '1999', 'COS335',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['37',  $TRAC, 'Tractor',                      'Fiat 900 E.',                              '2400412',                   'no posee',                 '1977', 'no posee',  $SP, null,                        'BAJA'],
            ['38',  $TRAC, 'Tractor',                      'Murray 12',                                'no posee',                  'no posee',                 '1997', 'no posee',  $SP, 'PLANTA DEPURADORA',         'BAJA'],
            ['39',  $CAMI, 'Camión',                       'IVECO DAILY',                              '7029532',                   '93ZC38A0188401124',        '2008', 'IGI290',    $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['40',  $TRAC, 'Tractor',                      'M. Ferguson',                              '62770031',                  '59330',                    '1993', 'no posee',  $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['41',  $CAMI, 'Camión',                       'Deutz Agrale',                             'SL407668',                  'PH400294',                 '1993', 'RHM018',    $SP, 'EQUIPO HORMIGON',           'EN USO'],
            ['42',  $RETRO,'Retroexcavadora',              'FIAT780R',                                 '203816',                    'no posee',                 '1971', 'no posee',  $SP, 'ORDENANZA Nº7511/14',       'BAJA'],
            ['43',  $CAMI, 'Camion Regador',               'Ford 700 D',                               'PA6486852',                 'KB6LDT27171',              '1984', 'SQN423',    $SP, 'RIEGO',                     'MANTENIMIENTO'],
            ['44',  $TRAC, 'Tractor',                      'M.Ferguson 255',                           'PA4138755',                 '1865029129',               '1980', 'no posee',  $SP, 'BREA',                      'EN USO'],
            ['45',  $TRAC, 'Tractor',                      'Stanley',                                  'amarillo',                  'no posee',                 '1995', 'no posee',  $SP, 'CEMENTERIO',                'EN USO'],
            ['46',  $MOTO, 'Motocicleta',                  'HONDA',                                    'JC30E89502733',             '9C2JD20109R502733',        null,   'EQG805',    $SE, null,                        'EN USO'],
            ['47',  $MOTO, 'Motocicleta',                  'HONDA',                                    'JC30E89502692',             '9C2JD20109R502692',        null,   'EQG806',    $SE, 'TRANSITO',                  'EN USO'],
            ['48',  $TRAC, 'Tractor',                      'Massey 165',                               'PA4136389',                 '1865-029128',              '1977', 'no posee',  $SP, 'DELEGACION GOWLAND',        'BAJA'],
            ['49',  $APLA, 'Aplanadora',                   'no posee',                                 'Villa 22 hp',               'no posee',                 '1996', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['50',  $ACCE, 'PALA',                         'KLIACA150',                                '34190000005544 8',          '6369/30',                  '1983', 'no posee',  $SP, 'ORDENANZA Nº7511/14',       'BAJA'],
            ['51',  $ACCE, 'MINICARGADOR',                 'BOBCAT',                                   'V2403-950124',              'A34L535986',               '2010', 'BKQ56',     $SP, 'EQUIPO VIAL',               'MANTENIMIENTO'],
            ['52',  $RETRO,'Retro-Pala',                   'Mancini PRM250',                           '105578',                    '305213',                   '1993', 'no posee',  $SP, 'PLANTA DEPURADORA',         'MANTENIMIENTO'],
            ['53',  $CETA, 'Camioneta',                    'Ford F 100',                               'PA 4521880',                'KA15YS -95804',            '1981', 'SVA742',    $SP, 'CORRALON',                  'BAJA'],
            ['54',  $CETA, 'Camioneta',                    'Ford F 100',                               'JPA101417T',                'KB8LCP53454',              '1984', 'SUW388',    $SP, 'ESPACIOS VERDES',           'BAJA'],
            ['55',  $CAMI, 'Camion Volcador',              'Ford 14000',                               '229061 39358',              '9BFXTNSM 5PDB23839',       '1994', 'SME448',    $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['56',  $CAMI, 'Barredora',                    'Ford 14000',                               '22906141847',               '9BFXTNSM4PDB29227',        '1994', 'SME447',    $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['57',  $CAMI, 'Camion Volcador',              'Ford 14000',                               '229061 44017',              '9BFXTNSM 3RBD42571',       '1994', 'SME443',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['58',  $CAMI, 'Barredora',                    'Ford 14000',                               '22906157761',               '9BFXTNSM3SDB65872',        '1995', 'APV817',    $SP, 'CORRALON',                  'BAJA'],
            ['59',  $CAMI, 'Camión Rec.',                  'Ford 14000',                               '6-012487',                  '9BFXTNSZ 6TDB07445',       '1996', 'AUP706',    $SP, 'CORRALON',                  'BAJA'],
            ['61',  $CAMI, 'Camión',                       'Agrale 8500',                              'E1T153413',                 '8BBC2662SAM000001',        '2009', 'IQW216',    $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['62',  $UTIL, 'Utilitarios',                  'Renault',                                  'K4MJ730Q076101',            '8A1FC1315CL848671',        '2011', 'KDX530',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['64',  $TRAC, 'Tractor',                      'Massey Ferguson 297',                      'YA31491BOO2874M',           '2972205834',               '2006', 'ABW72',     $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['65',  $TRAC, 'Tractor',                      'Massey Ferguson 297',                      'YA31491BOO2877M',           '2972205832',               '2006', 'ABW73',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['66',  $CETA, 'Camioneta',                    'Ford F 100',                               'RUAR11999',                 '8AFETNL27RJ018521',        '1994', 'SME444',    $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['67',  $CETA, 'Camioneta',                    'Fiat Fiorino',                             '8271763',                   '7343385',                  '1996', 'AUP708',    $SP, null,                        'BAJA'],
            ['68',  $CETA, 'Camioneta',                    'Fiat Fiorino',                             '8296372',                   '8359826',                  '1996', 'AUP707',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['71',  $TRAC, 'Tractor',                      'M. Ferguson 1475',                         'TWA000103532',              'Serie 00065322',           '1994', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['72',  $TRAC, 'Tractor',                      'Murray',                                   '20 HP',                     null,                       '1998', null,        $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['75',  $TRAC, 'Tractor',                      'Zanello',                                  '6022006',                   'TZAG223',                  '1991', 'no posee',  $SP, 'EQUIPO VIAL',               'BAJA'],
            ['76',  $TRAC, 'Tractor',                      'M. Ferguson',                              'PA6253118',                 '053323',                   '1987', 'no posee',  $SP, 'DELEGACION GOWLAND',        'BAJA'],
            ['77',  $TRAC, 'Tractor',                      'M. Ferguson',                              '4171364',                   '2173-045577',              '1979', 'no posee',  $SP, 'EQUIPO VIAL',               'BAJA'],
            ['78',  $TRAC, 'Tractor',                      'Massey Ferguson',                          '4171365',                   '2173-045579',              '1979', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['79',  $CETA, 'Camioneta',                    'Ford F 100',                               '22904324390',               '8AFBTNM39PJ061409',        '1994', 'RSY851',    $SP, 'AGUAS CORRIENTES',          'MANTENIMIENTO'],
            ['80',  $FURG, 'Camioneta',                    'Fiat Fiorino',                             '146B2081953926',            'ZFA146088526773',          '1997', 'BJV652',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['81',  $FURG, 'Camioneta',                    'Renault Kangoo',                           'F8QP632UB19446',            '8A1KCOJ158L042278',        '2008', 'HEH107',    $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['82',  $CAMI, 'Camion Volcador',              'Ford 6000',                                'PA6238593',                 'KA4LXM72514',              '1979', 'SXE303',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['83',  $CAMI, 'Camion Compactador',           'Ford 6000',                                'PA6246146',                 'KA4LYK48970',              '1980', 'SXE301',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['84',  $CAMI, 'Camión',                       'Ford F 7000',                              'PA6491861',                 'KB6LHR06559',              '1987', 'SQN420',    $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['85',  $CAMI, 'Camion Volcador',              'Ford F 7000',                              'PA6491970',                 'KB6LHR06549',              '1987', 'SQN419',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['86',  $CAMI, 'Camion Volcador',              'Ford F 7000',                              'PA6492259',                 'KBGLHY18547',              '1987', 'SQN421',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['87',  $CAMI, 'Camión',                       'Dodge',                                    'PA6423838',                 '398F00289F',               '1976', 'UTO865',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['88',  $CAMI, 'Camion Volcador',              'M. Benz 1620',                             '372951-10-157315',          '8AC386018SA111866',        '1995', 'AHF812',    $SP, 'CORRALON',                  'BAJA'],
            ['89',  $CAMI, 'Camión',                       'Ford F 14000',                             '22906150022',               '9BFXTNSM2RDB51911',        '1995', 'AFJ105',    $SP, 'OBRAS SANITARIAS',          'EN USO'],
            ['92',  $MOTO, 'Ciclomotor',                   'Zanella',                                  '70AB06419',                 'ZO79647',                  null,   null,        $SE, 'LICENCIA',                   'EN USO'],
            ['95',  $UTIL, 'Utilitarios',                  'Renault',                                  'K4MJ730Q072142',            '8A1FC1315CL820291',        '2011', 'KDX531',    $GO, 'PROTECCION CIVIL',          'EN USO'],
            ['99',  $MOTO, 'Motocicleta',                  'Zanella NT 200',                           '20Z3N1462',                 '2ZP01501',                 '1994', 'BML641',    $SE, 'TRANSITO',                  'EN USO'],
            ['100', $MOTO, 'Motocicleta',                  'Zanella NT 200',                           '20Z3N1496',                 '2ZP02052',                 '1994', 'BML642',    $SE, 'POLICIA',                   'EN USO'],
            ['101', $ACCE, 'Hidrojet',                     'F.M.C.',                                   'Desobstructora',            'no posee',                 '1996', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['102', $ACOP, 'Acoplado',                     'PETINARI',                                 'no posee',                  '8EPAD386290080322',        '2009', 'IGW370',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['103', $ACOP, 'Acoplado',                     'Vignatti',                                 'no posee',                  'no posee',                 '2008', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['104', $ACCE, 'Pata de Cabra',                'De arrastre',                              'no posee',                  'no posee',                 '1985', 'no posee',  $SP, 'EQUIPO VIAL',               'BAJA'],
            ['105', $CASI, 'Casilla',                      'Bromatologia',                             'no posee',                  'no posee',                 '2000', 'no posee',  $SP, null,                        'EN USO'],
            ['106', $ACCE, 'Pala Arrastre',                'no posee',                                 'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['107', $ACCE, 'Pala Arrastre',                'no posee',                                 'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['108', $ACCE, 'Pala Arrastre',                'no posee',                                 'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['112', $ACOP, 'Acoplado',                     'Berini',                                   'no posee',                  'no posee',                 '1996', 'no posee',  $SP, 'ROTA DESMANTELADA',         'BAJA'],
            ['114', $ACOP, 'Acoplado',                     null,                                       'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['116', $ACCE, 'Rabasto',                      'Albarenque',                               'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO VIAL',               'MANTENIMIENTO'],
            ['117', $ACCE, 'Rastra Disco',                 'Campra telt 150',                          'no posee',                  'no posee',                 '2004', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['118', $ACCE, 'Rastra disco',                 'Amstrong',                                 'no posee',                  'no posee',                 '1985', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['119', $ACCE, 'Rastra',                       'De arrastre',                              'no posee',                  'no posee',                 '1985', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['120', $ACOP, 'ACOPLADO 2 RUEDAS',           'excompresor Deutz 3 cilindros',            'no posee',                  'no posee',                 '2009', 'no posee',  $SP, null,                        'EN USO'],
            ['121', $ACCE, 'Terminadora',                  'Asfalto',                                  'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'BAJA'],
            ['122', $TANQ, 'Tanque',                       'Asfalto',                                  'no posee',                  'no posee',                 '1996', 'no posee',  $SP, 'CORRALON',                  'BAJA'],
            ['123', $CIST, 'Cisterna',                     'Combustible',                              'no posee',                  'no posee',                 '1996', 'no posee',  $SP, null,                        'BAJA'],
            ['124', $CIST, 'Cisterna',                     'Combustible',                              'no posee',                  'no posee',                 '1996', 'no posee',  $SP, 'PLANTA DEPURADORA',         'BAJA'],
            ['125', $CIST, 'Cisterna',                     'Combustible',                              'no posee',                  'no posee',                 null,   'no posee',  $SP, 'PLANTA DEPURADORA',         'BAJA'],
            ['126', $CARR, 'Carretón',                     'Massan',                                   'no posee',                  '863',                      '1994', 'SME445',    $SP, null,                        'EN USO'],
            ['127', $TANQ, 'Tanque',                       'Torregiani',                               'Regador',                   'no posee',                 null,   'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['128', $ACCE, 'Tanque',                       'Torregiani',                               'Regador',                   'no posee',                 null,   'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['129', $ACCE, 'Tanque',                       'Azul',                                     'Regador',                   'no posee',                 null,   'no posee',  $SP, 'ORDENANZA Nº7511/14',       'BAJA'],
            ['130', $ACOP, 'Acoplado',                     null,                                       'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'EN USO'],
            ['131', $ACOP, 'Acoplado Volcador',            'Traco Mod. 317V.',                         'Color blanco Cap. 3 Ton.',  '393437',                   '2001', 'no posee',  $SP, 'OBRAS SANITARIAS',          'EN USO'],
            ['132', $ACCE, 'Tanque regador',               'FERIOLI',                                  'Fibra de vidrio',           '3262',                     '2008', 'no posee',  $SP, null,                        'BAJA'],
            ['133', $ACCE, 'Tanque regador',               'FERIOLI',                                  'Fibra de vidrio',           'no posee',                 '2008', 'no posee',  $SP, null,                        'BAJA'],
            ['134', $ACCE, 'Tanque',                       'Torregiani',                               'Regador',                   'no posee',                 '1987', 'no posee',  $SP, 'RIEGO',                     'EN USO'],
            ['135', $ACCE, 'Tanque',                       'Torregiani',                               'Regador',                   'no posee',                 '1987', 'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['136', $ACCE, 'Tanque',                       'Torregiani',                               'Regador',                   'no posee',                 '1987', 'no posee',  $SP, 'ORDENANZA Nº7511/14',       'BAJA'],
            ['137', $ACCE, 'Trituradora',                  'Bicupiro',                                 'TJA100828',                 'no posee',                 '1992', 'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['138', $ACCE, 'Champion',                     'Arrastre',                                 'Albarenque',                'no posee',                 '2004', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['139', $ACCE, 'Tanque',                       'Regador',                                  'no posee',                  'no posee',                 '1987', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['140', $ACOP, 'Acoplado',                     null,                                       'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'EN USO'],
            ['141', $ACCE, 'Desmalezadora Rotativa',       'Anca 280',                                 'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'EN USO'],
            ['142', $ACCE, 'Rotativa',                     'Hilcor',                                   '3 Puntos',                  'no posee',                 null,   'no posee',  $SP, null,                        'BAJA'],
            ['143', $ACCE, 'Rotativa',                     'Hércules',                                 'Arrastre',                  'no posee',                 null,   'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['144', $ACCE, 'Rotativa',                     'Hércules',                                 'Arrastre',                  'no posee',                 null,   'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['145', $ACCE, 'Rodillo',                      'Liso',                                     'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'BAJA'],
            ['146', $ACOP, 'Acoplado',                     'Patronelli',                               '3 ejes',                    '198198',                   '1993', 'SME449',    $SP, 'CORRALON',                  'EN USO'],
            ['147', $ACOP, 'Acoplado',                     'Torreggiani',                              'Volcador',                  'no posee',                 null,   'no posee',  $SP, 'equipo vial',               'EN USO'],
            ['148', $ACOP, 'Acoplado',                     'Torreggiani',                              'Volcador',                  'no posee',                 '1996', 'no posee',  $SP, 'equipo vial',               'EN USO'],
            ['150', $ACCE, 'Rotativa',                     'Yomel',                                    'no posee',                  'no posee',                 null,   'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['151', $ACCE, 'Desmaleza-dora',               'Yomel',                                    'no posee',                  'Arrastre',                 '1999', 'no posee',  $SP, 'ESPACIOS VERDES',           'BAJA'],
            ['152', $ACCE, 'Desmaleza-dora',               'Yomel',                                    '3 Puntos',                  'no posee',                 null,   'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['153', $ACCE, 'Tanque',                       'Ferioli',                                  'Regador',                   '8.000Lts',                 '1998', 'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['155', $ACCE, 'Tanque',                       'Ferioli',                                  'Regador',                   'no posee',                 '1999', 'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['156', $ACCE, 'Compresor',                    'Rentaire',                                 'Jhonn Deere',               'no posee',                 '1998', 'no posee',  $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['157', $ACCE, 'Disco Rastra',                 'Albarenque',                               'no posee',                  'no posee',                 '2008', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['158', $ACCE, 'Disco',                        'De arrastre',                              'Campra',                    'no posee',                 '2008', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['160', $ACCE, 'Tanque',                       'Ferioli',                                  'Regador',                   'no posee',                 '1987', 'no posee',  $SP, 'RIEGO',                     'EN USO'],
            ['161', $ACCE, 'Rotativa',                     'Albarenque',                               'no posee',                  '2034',                     '2009', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['162', $ACCE, 'Champion de arrastre',         'Albarenque',                               'no posee',                  '5023',                     null,   'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['163', $ACCE, 'Desmalezadora Rotativa',       'Mival',                                    'no posee',                  'MV 1500',                  '2013', 'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['164', $ACCE, 'Tanque',                       'Ferioli',                                  'Regador',                   'no posee',                 '2004', 'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['165', $ACCE, 'Tanque',                       'Ferioli',                                  'Regador',                   'no posee',                 '2004', 'no posee',  $SP, 'RIEGO',                     'BAJA'],
            ['166', $ACCE, 'Hidrolabadora explocion',      'no posee',                                 'no posee',                  'no posee',                 null,   'no posee',  $SP, 'DELEGACION PARQUE',         'BAJA'],
            ['167', $ACOP, 'Acoplado 4 ruedas',           'albañiles',                                'no posee',                  'no posee',                 null,   'no posee',  $SP, 'EQUIPO HORMIGON',           'EN USO'],
            ['168', $ACOP, 'acoplado 4 ruedas',           'albañiles',                                'no posee',                  'no posee',                 null,   'no posee',  $SP, 'CORRALON',                  'EN USO'],
            ['169', $ACOP, 'acoplado largo 4 ruedas',     'electricista',                              'no posee',                  'no posee',                 null,   'no posee',  $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['171', $ACOP, 'Acoplado cisterna 100 ltrs.', 'Belen - rojo',                             'no posee',                  'no posee',                 '2009', 'no posee',  $SP, 'EQUIPO VIAL',               'BAJA'],
            ['172', $ACCE, 'Cordonera',                    'IMPEX',                                    'HONDA',                     'no posee',                 null,   'no posee',  $SP, 'CORRALON',                  'BAJA'],
            ['173', $ACCE, 'Trailer dos ruedas',           'IMPEX',                                    'no posee',                  'no posee',                 null,   'no posee',  $SP, null,                        'EN USO'],
            ['175', $ACOP, 'Acoplado',                     'Belen-Verde',                              'no posee',                  'Serie 5305',               '2010', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['176', $ACOP, 'Acoplado',                     'Belen-Verde',                              'no posee',                  'Serie 5306',               '2010', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['177', $ACOP, 'Acoplado',                     'Cametto',                                  'no posee',                  '8C901AB4L00178935',        '2013', 'LZR244',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['178', $ACCE, 'Desmalezadora Rotativa',       'Mival',                                    'no posee',                  'MV 1500',                  '2013', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['179', $ACOP, 'Acoplado',                     'PETINARI',                                 'no posee',                  '8EPAD3865D0080128',        null,   'NVR262',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['180', $ACCE, 'Chiapidora',                   'chevrolet Luv',                            'no posee',                  'ch 5653',                  '2014', 'no posee',  $SP, null,                        'EN USO'],
            ['181', $ACOP, 'ACOPLADO BATEA',               'Patronelli',                               'no posee',                  '8B9SEV215EA030149',        '2014', 'OFO359',    $SP, 'EQUIPO VIAL',               'EN USO'],
            ['182', $TRAC, 'TRACTOR',                      'HUSVARNA',                                 'no posee',                  '111014A002723',            null,   'no posee',  $SP, 'PLANTA DEPURADORA',         'EN USO'],
            ['183', $MNIV, 'Motoniveladora',               'Liugong',                                  '87985680',                  'G1400013',                 '2015', 'CLY51',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['184', $MNIV, 'Motoniveladora',               'Liugong',                                  '87985697',                  'G1300486',                 '2015', 'CLY50',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['185', $RETRO,'Pala',                         'Hanomaq',                                  'no posee',                  'no posee',                 '2015', 'no posee',  $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['186', $ACCE, 'Retro',                        'Liugong',                                  '4B15G001895',               'CLG766AX1500223',          '2015', 'CLY66',     $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['187', $ACCE, 'Rotativa',                     'Yomel',                                    '02AA',                      '44643',                    '2016', 'C6',        $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['188', $ACCE, 'Rotativa',                     'Yomel',                                    '02AA',                      '44650',                    '2016', 'C6',        $SP, 'CORRALON',                  'EN USO'],
            ['191', $ACCE, 'Lnacha 4.90',                  'Astillero Paraná',                         null,                        null,                       '2015', null,        $GO, 'PROTECCION CIVIL',          'EN USO'],
            ['201', $CAMI, 'Camion Volcador',              'F 14.000',                                 '6-025756',                  '9BFXTNSZ1VDB19490',        '1998', 'BYC089',    $SP, 'PLANTA DE TRANSFERENCIA',   'MANTENIMIENTO'],
            ['202', $TRAC, 'Tractor',                      'Massey Ferguson',                          'TWA105557C',                '68311',                    '1998', 'no posee',  $SP, 'CORRALON',                  'BAJA'],
            ['203', $TRAC, 'Tractor',                      'Massey Ferguson',                          'TWA105552C',                '68314',                    '1998', 'no posee',  $SP, 'CORRALON',                  'EN USO'],
            ['204', $TRAC, 'Tractor',                      'Massey Ferguson',                          'TWA105417C',                '68015',                    '1998', 'no posee',  $SP, 'CORRALON',                  'EN USO'],
            ['205', $TRAC, 'Tractor',                      'Massey Ferguson',                          'TWA105421C',                '68014',                    '1998', 'no posee',  $SP, 'CORRALON',                  'EN USO'],
            ['206', $CAMI, 'Barredora',                    'F 14.000',                                 '6025706',                   '9BFXTNSZ3VDB19488',        '1998', 'BYC088',    $SP, 'CORRALON',                  'BAJA'],
            ['207', $CAMI, 'Camion Compactador',           'F 14.000',                                 '6026105',                   '9BFXTNSZ7WDB20595',        '1998', 'BYC086',    $SP, 'CORRALON',                  'BAJA'],
            ['208', $CAMI, 'Camion Volcador',              'F 14.000',                                 '6026672',                   '9BFXTNSZ5WDB25102',        '1998', 'CAU707',    $SP, 'DELEGACION GOWLAND',        'BAJA'],
            ['209', $ACCE, 'Topadora',                     'Fiat Allis',                               'MWMTD229EC6',               '172346',                   '1998', 'no posee',  $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['210', $TRAC, 'Tractor',                      'Massey Ferguson',                          'TWA105196C',                '067789',                   '1998', 'no posee',  $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['211', $ACCE, 'Pala Frontal',                 'Samsung',                                  '97934129',                  'NDY0422',                  '1998', 'no posee',  $SP, null,                        'MANTENIMIENTO'],
            ['212', $CAMI, 'Camion Volcador',              'F 14.000',                                 '6031781',                   '9BFXTNSZXWDB02415',        '1998', 'CKP409',    $SP, 'FUERA DE SERVICIO',         'BAJA'],
            ['213', $CAMI, 'Camion Volcador',              'F 14.000',                                 '6031692',                   '9BFXTNSZ8WDB02039',        '1998', 'CKP408',    $SP, 'CORRALON',                  'BAJA'],
            ['214', $ACCE, 'Retroexcav.',                  'Samsung',                                  'B59-26228642',              'FCY1078',                  '1999', 'no posee',  $SP, null,                        'MANTENIMIENTO'],
            ['215', $CETA, 'Camioneta',                    'Ford Ranger',                              '179061877',                 '8AFER13D8VJ0 30647',       '1998', 'CGE452',    $SE, 'POLICIA',                   'EN USO'],
            ['216', $AMBU, 'Ambulancia Furgon',            'Mercedes Benz',                            '632.998-10-551190',         '8AC6903311A547086',        '2000', 'DOD718',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['217', $MOTO, 'Motocicleta',                  'Honda',                                    'JD17E-W102033',             '9C2JD170WWR102033',        '1999', 'BTE934',    $SE, 'POLICIA',                   'EN USO'],
            ['218', $MOTO, 'Motocicleta',                  'Honda',                                    'JD7E-W101258',              '9C2JD170WWR102033',        '1999', 'BTE935',    $SE, 'POLICIA',                   'EN USO'],
            ['219', $CAMI, 'Camión',                       'Iveco Tractor',                            'F4AE0681D6026338',          '8ATA1NFH0AX070228',        '2010', 'IQW210',    $SP, 'OBRAS SANITARIAS',          'EN USO'],
            ['220', $ACCE, 'Pala y retropala',             'Maxion 720',                               '5CBBOBB65',                 '720H171718',               '2004', 'no posee',  $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['221', $MOTO, 'Motocicleta',                  'Honda',                                    'JC30E84502052',             '9C2JD20104R502052',        '2004', 'CCL557',    $SE, 'POLICIA',                   'EN USO'],
            ['222', $MOTO, 'Motocicleta',                  'Honda',                                    'JC30E84502638',             '9C2JD20104R502638',        '2004', 'CCI556',    $SE, 'POLICIA',                   'EN USO'],
            ['223', $FURG, 'Camioneta',                    'Renault Kangoo',                           'F8QK630C572693',            '8ª1KCO2155L569320',        '2004', 'EQX380',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['224', $FURG, 'Camioneta',                    'Renault Kangoo',                           'F8QK630C573410',            '8ª1KCO2155L574984',        '2004', 'EQN069',    $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['225', $CETA, 'Camioneta',                    'Toyota Hilux 4 x 2',                      '314275990',                 'JTA33LNAGV8003957',        '1997', 'BRH713',    $SE, 'TRANSITO',                  'EN USO'],
            ['227', $FURG, 'Camioneta',                    'Vwolkswagen',                              'CFZ830950',                 '9BWKB05U1BP189353',        '2011', 'KIA900',    $SP, 'CORRALON',                  'EN USO'],
            ['228', $FURG, 'Camioneta',                    'Peugeot Partner',                          '10DXBJ0006806',             '8ª6SBWJZEGG514357',        '2006', 'FPO630',    $GO, null,                        'EN USO'],
            ['241', $TRAC, 'Tractor',                      'Mases Ferguson',                           'LI31142.TPL46534',          '9005247M91EX706',          '1999', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['243', $CETA, 'Utilitarios',                  'Wolkswagen',                               'CFZ090672',                 '9BWKB05U7CP004367',        '2011', 'KIA901',    $SP, 'Planta Depuradora',         'EN USO'],
            ['244', $CETA, 'Camioneta',                    'Chevrolet Luv',                            '549334',                    '8GGTFSF16XA076453',        '1999', 'CYO609',    $SE, 'PINTURA VIAL',              'EN USO'],
            ['245', $TRAC, 'Tractor',                      'Zanello Pauni 230 A',                      '30765885',                  'CC5046',                   '2000', 'no posee',  $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['246', $TRAC, 'Tractor c/ pala y retro',      'Maxion 720',                               'SC8B689498M',               '720H204822',               '2006', 'no posee',  $SP, 'CORRALON',                  'BAJA'],
            ['247', $ACCE, 'Retrocargador',                'HIDROMEX',                                 'U523700U',                  'HMK102BTK35155212',        '2011', 'CFM29',     $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['249', $ACCE, 'Retrocargador',                'HIDROMEX',                                 'U523688U',                  'HMK102BTT35155210',        '2011', 'CFM30',     $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['250', $CETA, 'Camioneta',                    'Chevrolet Luv',                            '294134',                    'TFS16HDL1522',             '1994', 'CAR876',    $SE, null,                        'EN USO'],
            ['251', $CETA, 'Sprinter',                     'Mercedes Benz',                            '6119817 0073176',           '8AC9046638A982452',        '2007', 'GSX380',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['252', $TRAC, 'Tractor',                      null,                                       'Cortar Pasto',              'no posee',                 '2007', 'no posee',  $SP, 'Planta Depuradora',         'BAJA'],
            ['253', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ081071',                 '9BWDB05U9BT173952',        '2011', 'JYV207',    $SE, 'POLICIA',                   'EN USO'],
            ['254', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ080407',                 '9BWDB05U5BT173608',        '2011', 'JYV208',    $SE, 'POLICIA',                   'EN USO'],
            ['255', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ080843',                 '9BWDB05UXBT173877',        '2011', 'JYV209',    $SE, 'POLICIA',                   'EN USO'],
            ['256', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ077056',                 '9BWDB05UXBT156948',        '2011', 'JYV210',    $SE, 'POLICIA',                   'EN USO'],
            ['257', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ080837',                 '9BWDB05U6BT173889',        '2011', 'JYV211',    $SE, 'POLICIA',                   'EN USO'],
            ['258', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZ080852',                 '9BWDB05U1BT173833',        '2011', 'JYV212',    $SE, 'POLICIA',                   'EN USO'],
            ['259', $CETA, 'Pick Up',                      'Ford',                                     'BJ412232',                  '8AFDR12A7BJ412232',        '2011', 'KCP116',    $SE, 'POLICIA',                   'EN USO'],
            ['260', $CETA, 'Pick Up',                      'Ford',                                     'CJ427766',                  '8AFDR12A7CJ427766',        '2011', 'KCP148',    $SE, 'POLICIA',                   'EN USO'],
            ['261', $CETA, 'Pick Up',                      'Ford',                                     'CJ427769',                  '8AFDR12A2CJ427769',        '2011', 'KCP149',    $SE, 'POLICIA',                   'EN USO'],
            ['262', $CETA, 'Pick Up',                      'Ford',                                     'CJ458839',                  '8AFDR12A9CJ458839',        '2012', 'KYR793',    $SE, null,                        'EN USO'],
            ['263', $CETA, 'Camioneta',                    'Ford - Ranger',                            'CJ457602',                  '8AFDR12A6CJ457602',        '2012', 'KYR794',    $SE, 'BARRIDO',                   'EN USO'],
            ['264', $CETA, 'Pick Up',                      'Ford',                                     'CJ458805',                  '8AFDR12A3CJ458805',        '2012', 'KYR795',    $SE, 'POLICIA',                   'EN USO'],
            ['265', $CETA, 'Pick Up',                      'Ford',                                     'CJ457627',                  '8AFDR12A0CJ457627',        '2012', 'KYR796',    $SE, 'POLICIA',                   'EN USO'],
            ['266', $CETA, 'Pick Up',                      'Ford',                                     'CJ458814',                  '8AFDR12A4CJ458814',        '2012', 'KYR797',    $SE, null,                        'EN USO'],
            ['267', $CETA, 'Pick Up',                      'Ford',                                     'CJ457635',                  '8AFDR12AXCJ457635',        '2012', 'KYR798',    $SE, 'POLICIA',                   'EN USO'],
            ['268', $CETA, 'Pick Up',                      'Ford',                                     'CJ457632',                  '8AFDR12A4CJ457632',        '2012', 'KYR799',    $SE, 'POLICIA',                   'EN USO'],
            ['269', $CETA, 'Pick Up',                      'Ford',                                     'CJ458812',                  '8AFDR12A0CJ458812',        '2012', 'KYR800',    $SE, 'POLICIA',                   'EN USO'],
            ['270', $CETA, 'Pick Up',                      'Ford',                                     'CJ458826',                  '8AFDR12A0CJ458826',        '2012', 'KYR801',    $SE, 'POLICIA',                   'EN USO'],
            ['271', $CETA, 'Pick Up',                      'Ford',                                     'CJ458831',                  '8AFDR12A4CJ458831',        '2012', 'KYR802',    $SE, 'POLICIA',                   'EN USO'],
            ['272', $CETA, 'Pick Up',                      'Ford',                                     'CJ458832',                  '8AFDR12A6CJ458832',        '2012', 'KYR803',    $SE, 'POLICIA',                   'EN USO'],
            ['273', $CETA, 'Pick Up',                      'Ford',                                     'CJ458833',                  '8AFDR12A8CJ458833',        '2012', 'KYR804',    $SE, 'POLICIA',                   'EN USO'],
            ['274', $CETA, 'Pick Up',                      'Ford',                                     'CJ458834',                  '8AFDR12AXCJ458834',        '2012', 'KYR805',    $SP, 'SERVICIO ELECTRICO',        'MANTENIMIENTO'],
            ['275', $CETA, 'Pick Up',                      'Ford',                                     'CJ457567',                  '8AFDR12A8CJ457567',        '2012', 'KYR806',    $SE, 'POLICIA',                   'EN USO'],
            ['276', $CETA, 'Pick Up',                      'Ford',                                     'CJ457601',                  '8AFDR12A4CJ457601',        '2012', 'KYR807',    $SE, 'POLICIA',                   'EN USO'],
            ['278', $FURG, 'Furgon',                       'Renault',                                  'K4MJ730Q092523',            '8A1FC1315CL253807',        '2012', 'LLU405',    $ED, 'DIRECCION DE DEPORTE',      'EN USO'],
            ['279', $FURG, 'Furgon',                       'Renault',                                  'K4MJ730Q089191',            '8A1FC1315CL243607',        '2012', 'LLU406',    $GO, null,                        'EN USO'],
            ['280', $ACCE, 'Pala Frontal',                 'Lonking',                                  'X1220997',                  '51281453',                 '2012', 'CLY03',     $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['281', $FURG, 'Furgon',                       'Renault',                                  'K4MJ730Q108539',            '8A1FC1315DL568504',        '2012', 'LYB072',    $GO, 'MODERNIZACION',             'EN USO'],
            ['282', $FURG, 'Furgon',                       'Renault',                                  'K4MJ730Q108598',            '8A1FC1315DL570136',        '2012', 'LYB073',    $SE, 'GOBIERNO',                  'EN USO'],
            ['283', $CETA, 'Pick Up',                      'Volkswagen',                               'CFZ966641',                 '9BWKB05UDP138138',         '2012', 'LYB074',    $SE, 'TRANSITO',                  'EN USO'],
            ['284', $CETA, 'Camioneta',                    'Volkswagen-SAVEIRO',                       'CFZ142853',                 '9BWKB05U5DP152275',        '2013', 'MAG099',    $SP, 'CORRALON',                  'EN USO'],
            ['285', $CAMI, 'Camion Compactador',           'Iveco',                                    'F4AE0681D6085098',          '8ATA1NFH0DX082585',        '2013', 'LZR243',    $SP, 'RECOLECCION',               'EN USO'],
            ['286', $CAMI, 'Camion Compactador',           'Iveco',                                    'F4AE0681D6079098',          '8ATA1NFH0DX083080',        '2013', 'LZR242',    $SP, 'RECOLECCION',               'MANTENIMIENTO'],
            ['287', $TRAC, 'Tractor',                      'Mahindra',                                 'M13H55A147M',               'PRPX1964',                 '2012', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['288', $TRAC, 'Tractor',                      'Mahindra',                                 'M13H55A140M',               'PRPX1963',                 '2012', 'no posee',  $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['289', $CAMI, 'Camión',                       'Agrale',                                   'D1A070138',                 '8BBC31Y2FDM000016',        '2013', 'MKK066',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['292', $CETA, 'Camioneta',                    'Toyota Hilux',                             '5L5430916',                 '8AJ33LNL049112503',        '2004', 'ELD723',    $SE, 'POLICIA',                   'EN USO'],
            ['293', $AUTO, 'Automóvil',                    'Toyota Corolla',                           '2ZRM186482',                '9BRBU48E9E4783302',        '2013', 'NIH731',    $GO, 'PRIVADA',                   'EN USO'],
            ['294', $MOTO, 'Motocicleta',                  'Honda',                                    'MD34E-E862671',             '8CHMD3400FL000307',        '2014', 'KRX078',    $GO, null,                        'EN USO'],
            ['296', $CETA, 'Camioneta',                    'Toyota Hilux',                             '2KD-A420987',               '8AJFR22G5E4571326',        '2014', 'NXK252',    $SE, 'TRANSITO',                  'EN USO'],
            ['297', $CAMI, 'Camión',                       'Volkswagen',                               '36433106',                  '9533782TXDR338744',        '2014', 'OHQ100',    $SP, 'CEAMSE',                    'EN USO'],
            ['298', $CAMI, 'Camion Compactador',           'Volkswagen',                               '30780581',                  '9BWCK82TX4R417291',        '2004', 'IFC857',    $SP, 'RECOLECCION',               'EN USO'],
            ['299', $CAMI, 'Camion Compactador',           'Volkswagen',                               '30780582',                  '9BWCK82TX04R417333',       '2004', 'IFC862',    $SP, 'RECOLECCION',               'BAJA'],
            ['301', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZN41485',                 '9BWAB45U5FP05539',         '2014', 'OLH685',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['302', $CETA, 'Camioneta',                    'Volkswagen',                               'CNF041274',                 '8AWDD42H0FA007252',        '2014', 'OLH686',    $SP, 'EVENTOS',                   'EN USO'],
            ['303', $CETA, 'Camioneta',                    'Volkswagen',                               'CNF042777',                 '8AWDD42H9FA013762',        '2014', 'OLH687',    $SP, 'CORRALON',                  'EN USO'],
            ['304', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZN59293',                 '9BWAB45U5FP093394',        '2014', 'OLH688',    $GO, 'PRIVADA',                   'EN USO'],
            ['305', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZN36282',                 '9BWAB45UXFP514428',        '2014', 'OLH689',    $SE, 'POLICIA',                   'EN USO'],
            ['306', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZN39061',                 '9BWAB45U0FP517936',        '2014', 'OLH692',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['307', $AUTO, 'Automóvil',                    'Volkswagen',                               'CFZN50754',                 '9BWAB45U7FP071140',        '2014', 'OLH693',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['308', $CAMI, 'Camion Compactador',           'Iveco',                                    'F4AE0681D*8013751*',        '8ATA1NFH0FX095014',        '2015', 'PMI812',    $SP, 'RECOLECCION',               'EN USO'],
            ['312', $TRAC, 'Tractor 575,4 SR',            'Agrale',                                   'BCN000118',                 'AGR13AA23G0000080',        '2016', 'CLY71',     $SP, 'CORRALON',                  'EN USO'],
            ['313', $TRAC, 'Tractor 4230 FBO',            'Agrale',                                   'GF0043',                    'A1G03AB1AF00004514',       '2016', 'CLY73',     $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['314', $TRAC, 'Tractor 575,4 SR',            'Agrale',                                   'BCN000075',                 'AGR13AA2AG0000049',        '2016', 'CLY72',     $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['315', $TRAC, 'Tractor BX 6110',             'Agrale',                                   'BCS00032',                  'AGR09AA2XG0000045',        '2016', 'CLY70',     $SP, 'CORRALON',                  'EN USO'],
            ['316', $CAMI, 'Camion doble cabina',          'Agrale 8500',                              '*E1T195987*',               '9BYC2663SGC000517',        '2016', 'AA642OE',   $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['317', $CAMI, 'Camion Volcador',              'Agrale 14000',                             '*U1A008707*',               '9BYC78A2AHC000439',        '2016', 'AA642NV',   $SP, 'RIEGO',                     'EN USO'],
            ['318', $CAMI, 'Camion doble cabina',          'Agrale 8500',                              '*E1T193759*',               '9BYC2663SGC000507',        '2016', 'AA642OD',   $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['319', $CAMI, 'Camion Volcador',              'Agrale 14000',                             '*U1A008729*',               '9BYC78A2AHC000440',        '2016', 'AA642NW',   $SP, 'RIEGO',                     'EN USO'],
            ['320', $ACCE, 'Barredora de arrastre',        'Urvig XAC 900 F',                          'NO POSEE',                  '161012',                   '2016', 'no posee',  $SP, 'CORRALON',                  'BAJA'],
            ['321', $CAMI, 'Camion Bivuelco',              'Agrale 14000 S',                           '*U1A008962*',               '9BYC78A2AHC000445',        '2016', 'AA728MY',   $SP, 'RIEGO',                     'EN USO'],
            ['322', $CAMI, 'Camion Sidecar',               'Agrale 9500',                              'E1T167690',                 '8BBC2662FCM000159',        '2014', 'OBR257',    $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['323', $CETA, 'Camioneta con Hidroelevador',  'DODGE RAM 5,5',                            '111982',                    '3CJWDNBLGCG111982',        '2012', 'MM001MB',   $SP, 'SERVICIO ELECTRICO',        'MANTENIMIENTO'],
            ['324', $CAMI, 'Camion doble cabina',          'Agrale 8500',                              'E1T193760',                 '9BYC2663SGC000508',        '2017', 'AA879CX',   $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['325', $CAMI, 'Camion doble cabina',          'Agrale 8500',                              'E1T194302',                 '9BYC2663SGC000511',        '2017', 'AA879CY',   $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['326', $CAMI, 'Camion Barredora',             'Agrale 14000',                             'U1A009011',                 '9BYC78A2AHC000452',        '2017', 'AA879CW',   $SP, 'CORRALON',                  'EN USO'],
            ['327', $TRAC, 'Tractor 4230,4',              'Agrale Cargo Argento',                     'GF0151',                    'A1G04AB2AF0004552',        '2017', 'CLY83',     $SP, 'CEMENTERIO',                'EN USO'],
            ['328', $TRAC, 'Tractor 575,4 SR',            'Agrale Compacto',                          'BCN000137',                 'AGR13AA2KG000093',         '2017', 'CLY84',     $SP, 'CORRALON',                  'EN USO'],
            ['329', $ACCE, 'Minicargadora',                'New Holland L218',                         '122413',                    'JAF0L218CGM415587',        '2017', 'CLY87',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['330', $ACCE, 'Minicargadora',                'New Holland L218',                         '122402',                    'JAFOL218VGM415588',        '2017', 'CLY88',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['331', $RETRO,'Cargadora con Retro Pala',     'New Holland B90B 4X4',                     '001373552',                 'FNH0B90BNFHH02506',        '2017', 'CLY85',     $SP, 'DELEGACION GOWLAND',        'MANTENIMIENTO'],
            ['332', $RETRO,'Cargadora con Retro Pala',     'New Holland B90B 4X4',                     '001368753',                 'FNH0B90BNFHH02450',        '2017', 'CLY86',     $SP, 'CORRALON',                  'EN USO'],
            ['333', $ACCE, 'Barredora de arrastre',        'Urvig XAC 900 F',                          'no posee',                  '161220',                   '2017', null,        $SP, null,                        'BAJA'],
            ['334', $AUTO, 'Automóvil',                    'Volkswgen Gol',                            'CFZR46555',                 '9BWAB45U4HP503315',        '2017', 'AA728ME',   $SE, 'CONTROL URBANO',            'EN USO'],
            ['335', $AUTO, 'Automóvil',                    'Volkswgen Gol',                            'CFZR34108',                 '9BWAB45UXHP035302',        '2017', 'AA728MF',   $SE, 'CONTROL URBANO',            'EN USO'],
            ['336', $FURG, 'Berlingo Furgon',              'Citroen',                                  '10DBSW0040202',             '8BCGCKFSCHG521342',        '2017', 'AA984NN',   $SE, null,                        'EN USO'],
            ['337', $FURG, 'Berlingo Furgon',              'Citroen',                                  '10DBSW0039085',             '8BCGCKFSCHG514976',        '2017', 'AA984NM',   $SE, 'INSPECION',                 'EN USO'],
            ['338', $MOTO, 'Motocicleta',                  'Suzuki ax100',                             '1E50FMGA1D58510',           '8AHMS1100AR006423',        '2012', 'M066MMB',   $SE, null,                        'EN USO'],
            ['339', $MOTO, 'Motocicleta',                  'YAMAHA YBR',                               'E387E006238',               'LBPKE095070091245',        '2011', 'M099MMB',   $SE, null,                        'EN USO'],
            ['340', $MOTO, 'Motocicleta',                  'YAMAHA YBR',                               'E387E0082016',              'LBPKE095170112720',        '2013', 'M101MMB',   $SE, null,                        'EN USO'],
            ['341', $MOTO, 'Motocicleta',                  'HONDA STORM',                              'SDH157FMIC63022902',        'LALPCCJF8E6E261111',       '2014', 'M121MMB',   $SE, null,                        'EN USO'],
            ['342', $MOTO, 'Motocicleta',                  'YAMAHA YBR',                               'E3D5E037733',               '8C6KE1279A0023528',        '2011', 'M141MMB',   $SE, null,                        'EN USO'],
            ['344', $MOTO, 'Motocicleta',                  'SUZUKI SV650S',                            'T715119611',                'JS1GT77S472109826',        null,   null,        $SE, null,                        'EN USO'],
            ['345', $MOTO, 'Motocicleta',                  'SCOOTER FY125 T4',                         'JY162QMJ0512001',           'LJYTCKPX405120001',        null,   null,        $SP, null,                        'BAJA'],
            ['346', $TANQ, 'TANQUE AGUA POTABLE',          'Torreggiani',                              'no posee',                  null,                       '2017', null,        $SP, 'RIEGO',                     'EN USO'],
            ['347', $ACCE, 'TANQUE REGADOR',               'Torreggiani',                              'no posee',                  null,                       '2017', null,        $SP, 'RIEGO',                     'EN USO'],
            ['348', $ACCE, 'TANQUE REGADOR',               'Torreggiani',                              'no posee',                  null,                       '2017', null,        $SP, 'RIEGO',                     'EN USO'],
            ['349', $ACCE, 'Compactadora de Arrastre',     'GROSSPAL C.V 140',                         'no posee',                  '8716.39.00',               '2017', null,        $SP, null,                        'BAJA'],
            ['350', $ACCE, 'Compactadora de Arrastre',     'GROSSPAL C.V 140',                         'no posee',                  '8716.39.01',               '2017', null,        $SP, null,                        'BAJA'],
            ['351', $ACCE, 'Compactadora de Arrastre',     'GROSSPAL C.V 140',                         'no posee',                  '8716.39.02',               '2017', null,        $SP, null,                        'BAJA'],
            ['352', $ACCE, 'Desmalezadora y cor. Cesped',  'AGRALE - LAVRALE ATD 8300 X 3.Mtrs',      'no posee',                  null,                       '2017', null,        $SP, 'CORRALON',                  'EN USO'],
            ['353', $ACCE, 'Retroexcavadora con Balde',    'AGRALE - LAVRALE - RE (Adicional)',        'no posee',                  null,                       '2017', null,        $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['354', $ACCE, 'Cargadora frontal para Agrale 575,4', 'AGRALE - LAVRALE - PADU (Adicional)', 'no posee',               null,                       '2017', null,        $SP, null,                        'EN USO'],
            ['355', $ACCE, 'hoyadora perforadora de suelo','AGRALE - LAVRALE - PS-TM (Adicional)',     'no posee',                  null,                       '2017', null,        $SP, null,                        'EN USO'],
            ['356', $ACCE, 'Hidroelevador Bert-Lift 15 LC','HIDRO-GRUBERT (Adicional)',                'no posee',                  null,                       '2017', null,        $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['357', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH05 135',         null,                       null,   null,        $SP, 'BOMBEROS',                  'MANTENIMIENTO'],
            ['358', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 138',        null,                       null,   null,        $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['359', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 717',        null,                       null,   null,        $SP, 'San Martin',                'MANTENIMIENTO'],
            ['360', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 720',        null,                       null,   null,        $SP, 'CAMARAS',                   'MANTENIMIENTO'],
            ['361', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 721',        null,                       null,   null,        $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['362', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 723',        null,                       null,   null,        $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['363', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 724',        null,                       null,   null,        $SP, 'CORRALON',                  'MANTENIMIENTO'],
            ['364', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 140',        null,                       null,   null,        $SP, 'MARTIN RODRIGUEZ',          'MANTENIMIENTO'],
            ['365', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X 4 CH 05 725',       null,                       null,   null,        $SP, 'DELEGACION PARQUE',         'EN USO'],
            ['366', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X 4 CH 05 716',       null,                       null,   null,        $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['367', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 142',        null,                       null,   null,        $SP, 'CONTROL URBANO',            'EN USO'],
            ['368', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 715',        null,                       null,   null,        $SP, 'MARTIN RODRIGUEZ',          'EN USO'],
            ['369', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X 4 CH 05 722',       null,                       null,   null,        $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['370', $GENE, 'Generador Electrico',          'HIMOINSA - APOLO 4006',                    'SERIE X4 CH 05 722',        null,                       null,   null,        $SP, null,                        'EN USO'],
            ['371', $MNIV, 'Motoniveladora',               'LIUGONG CLG 4180',                         '78363872',                  'LIUGONG GP1600599',        '2017', 'DLY06',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['372', $MNIV, 'Motoniveladora',               'LIUGONG CLG 4180',                         '78402740',                  'CLG4180GP01700005',        '2017', 'DLY11',     $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['373', $ACCE, 'Retropala',                    'NEW HOLLAND B90B',                         '001374538',                 'FNH0B90BNFHH02504',        '2017', 'DLY10',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['374', $CAMI, 'Camión',                       'IVECO VERTIS 130V19 PASO 4815',            '8036850',                   '93ZA1FD00H874045',         '2017', 'AC472JK',   $SP, 'RECOLECCION',               'EN USO'],
            ['375', $CAMI, 'Camión',                       'IVECO',                                    '8037947',                   '93ZA1FD00J8563695',        '2017', 'AC581YN',   $SP, 'RECOLECCION',               'MANTENIMIENTO'],
            ['376', $CAMI, 'Camión',                       'IVECO',                                    '8037946',                   '93ZA1FD00J8563693',        '2017', 'AC372US',   $SP, 'RECOLECCION',               'EN USO'],
            ['377', $OMNI, 'MINI BUS',                     'AGRALE',                                   '89214136',                  '8BBC52A1AHM000054',        '2017', 'AC017YV',   $GO, null,                        'EN USO'],
            ['378', $OMNI, 'MINI BUS',                     'AGRALE',                                   '36549033',                  '8BBC52A1AHM000055',        '2017', 'AC017YU',   $GO, null,                        'EN USO'],
            ['379', $CAMI, 'Camión',                       'AGRALE 8700',                              '36575848',                  '8BBC93A2AJM000069',        '2018', 'AC762BB',   $SP, 'EVENTOS',                   'EN USO'],
            ['380', $CAMI, 'Camión',                       'AGRALE 8700',                              '36575385',                  '8BBC93A2AJM000067',        '2018', 'AC762BA',   $SP, 'CARTELERIA',                'EN USO'],
            ['382', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 125',                           'E3S4E020561',               '8C6KE202XG0013340',        '2017', 'AO43JEG',   $SE, 'POLICIA',                   'EN USO'],
            ['383', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 126',                           'E354ED21971',               '8C6KE2027H0015032',        '2017', 'AO43JEB',   $SE, 'POLICIA',                   'EN USO'],
            ['384', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 127',                           'E3S4E022262',               '8C6KE2020H0015762',        '2017', 'AO41FYX',   $SE, 'POLICIA',                   'EN USO'],
            ['385', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 128',                           'E3S4E021786',               '8C6KE2021H0014944',        '2017', 'AO43JED',   $SE, 'POLICIA',                   'EN USO'],
            ['386', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 129',                           'E3S4E021999',               '8C6KE2023H0015061',        '2017', 'AO41FYZ',   $SE, 'POLICIA',                   'EN USO'],
            ['387', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 130',                           'E3S4E021936',               '8C6KE2021H0015012',        '2017', 'AO43JEA',   $SE, 'POLICIA',                   'EN USO'],
            ['388', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 131',                           'E3S4E020573',               '8C6KE2020G0013380',        '2017', 'AO43JEF',   $SE, 'POLICIA',                   'EN USO'],
            ['389', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 132',                           'E3S4E021603',               '8C6KE2028H0014763',        '2017', 'AO41FYY',   $SE, 'POLICIA',                   'EN USO'],
            ['390', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 133',                           'E3S4E021917',               '8C6KE2026H0015006',        '2017', 'AO43JEE',   $SE, 'POLICIA',                   'EN USO'],
            ['391', $MOTO, 'Motocicleta',                  'YAMAHA XTZ 134',                           'E3S4E021993',               '8C6KE2017H0015080',        '2017', 'AO43JEC',   $SE, 'POLICIA',                   'EN USO'],
            ['392', $ACCE, 'Obrador Movil',                'Tipo Oficina',                             null,                        null,                       '2017', null,        $SE, 'POLICIA',                   'EN USO'],
            ['393', $ACCE, 'Obrador Movil',                'Tipo Oficina',                             null,                        null,                       '2017', null,        $SE, 'POLICIA',                   'EN USO'],
            ['396', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '36235244',                  '9BYC37X15BC001075',        '2011', 'JOI379',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['397', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '36235243',                  '9byc37x15BC001076',        '2011', 'JOI380',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['398', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '36235211',                  '9BYC37X15BC001074',        '2011', 'JOI382',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['399', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '36235245',                  '9BYC37X15BC001077',        '2011', 'JOI386',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['400', $CAMI, 'Camión',                       'AGRALE 14000',                             'U1A000397',                 '9BYC78A2AJC000513',        '2019', 'AD487HX',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['401', $CAMI, 'Camión',                       'AGRALE',                                   'U1A009125',                 '9BYC78A2AJC000514',        '2019', 'AD487HW',   $SP, 'EQUIPO HORMIGON',           'EN USO'],
            ['402', $CETA, 'Camioneta',                    'FORD RANGER',                              'QJ2RJJ051991',              '8AFAR22K9JJ051991',        '2017', 'AC207WW',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['404', $CAMI, 'Camión',                       'IVECO',                                    '6187395',                   '93ZA01LFOL8936052',        '2019', 'AD858BD',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['405', $CAMI, 'Camión',                       'IVECO',                                    '6187395',                   '93ZA01LFOL8935978',        '2019', 'AD858BE',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['406', $CAMI, 'Camión',                       'IVECO',                                    '6181054',                   '93ZA01LFOK8935315',        '2019', 'AD858BF',   $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['407', $CAMI, 'Camión',                       'IVECO',                                    '6185536',                   '93ZA01LFOL8935757',        '2019', 'AD858BG',   $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['408', $CETA, 'Camioneta',                    'TOYOTA',                                   '2GD-G078239',               '8AJCB8DDXK4004599',        '2019', 'AD903MP',   $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['409', $CETA, 'Camioneta',                    'TOYOTA',                                   '2GD-C452973',               '8AJCB8DDXK4005591',        '2019', 'AD903MO',   $GO, 'CULTURA',                   'EN USO'],
            ['410', $CETA, 'Camioneta',                    'TOYOTA',                                   '2GD-C452892',               '8AJCB8DD5K4005594',        '2019', 'AD903MN',   $GO, 'PRODUCCION',                'EN USO'],
            ['411', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '36066406',                  '8BBC37X15CM000828',        '2012', 'LKF659',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['412', $OMNI, 'OMNIBUS',                      'AGRALE',                                   '3637383',                   '8BBC37X15CM000835',        '2012', 'LLZ069',    $SE, 'TRASPORTE PUBLICO',         'EN USO'],
            ['413', $FURG, 'FURGON',                       'PEUGEOT EXPERT',                           '10JCAP0024060',             '9V8VBBHXGJA001442',        '2018', 'AD952BR',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['414', $CAMI, 'IVECO',                        'IVECO',                                    'F4HE3681B*8053425',         '8ATE12NMXKX109920',        '2019', 'AE075XF',   $SP, 'OBRAS SANITARIAS',          'EN USO'],
            ['415', $AUTO, 'AUTOMOVIL CARROZADO',          'PEUGEOT',                                  '383267',                    '2006042',                  '1982', 'SIC222',    $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['425', $CETA, 'Camioneta',                    'FORD',                                     'YCAA38978',                 'A27YC33224',               '1980', 'XFU807',    $SE, null,                        'EN USO'],
            ['427', $CAMI, 'CAMION TRACTOR',               'IVECO',                                    'F4HE3681E*8058496',         '8ATM11PMZKX110720',        '2020', 'AE389AG',   $SP, 'CEAMSE',                    'EN USO'],
            ['428', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E8073191',          '8ATA1RMHOMX112362',        '2020', 'AE516SA',   $SP, 'RECOLECCION',               'EN USO'],
            ['429', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E8073195',          '8ATAA1RMHOMX112350',       '2020', 'AE516SC',   $SP, 'SERVICIO ELECTRICO',        'EN USO'],
            ['430', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E8073233',          '8ATA1RMHOMX112372',        '2020', 'AE486LY',   $SP, 'RECOLECCION',               'EN USO'],
            ['431', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E80173192',         '8ATA1RMHOMX112356',        '2020', 'AE516SB',   $SP, 'RECOLECCION',               'EN USO'],
            ['432', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E8073231',          '8ATA1RMHOMX112379',        '2020', 'AE516SG',   $SP, 'RECOLECCION',               'EN USO'],
            ['433', $CARR, 'Carretón',                     'COMETTO',                                  'no posee',                  '8C9AB2131K2178036',        '2020', 'AE648ZE',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['434', $ACCE, 'CARGADORA',                    'ENSIGN',                                   '82258967',                  '567006LDCLE250190',        '2020', 'EEN57',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['435', $AELV, 'AUTOELEVADORA',                'DOOSAN',                                   '201010G644',                'OBA02-00062',              '2020', 'EEN58',     $SP, 'CORRALON',                  'EN USO'],
            ['436', $EXCA, 'EXCAVADORA',                   'SANY',                                     '4M50-E41745',               'SY021NCA67658',            '2020', 'EEN59',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['437', $CAMI, 'Camión',                       'IVECO',                                    '6221883',                   '93ZA01LF0M8940851',        '2021', 'AE648ZR',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['438', $CAMI, 'Camión',                       'IVECO',                                    '6221885',                   '93ZA01LF0M8940834',        '2021', 'AE648ZQ',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['439', $CAMI, 'Camión',                       'IVECO',                                    '6218728',                   '93ZAO1LFOM8939728',        '2020', 'AE571PU',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['440', $ACCE, 'MINI PALA',                    'NEW HOLLAND L 318',                        '721392F',                   'JAFOL318CMM494625',        '2021', 'EGZ67',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['441', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E*8080853',         '8ATA1RMH0NX114335',        '2021', 'AF006AS',   $SP, 'RECOLECCION',               'EN USO'],
            ['442', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E*8081809',         '8ATA1RMH0NX114337',        '2021', 'AF006AR',   $SP, 'RECOLECCION',               'EN USO'],
            ['443', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681*8081808',          '8ATA1RMH0NX114384',        '2021', 'AF006AT',   $SP, 'RECOLECCION',               'EN USO'],
            ['444', $MNIV, 'MOTONIVELADORA',               'LUI GONG MODELO 422',                     '78072191',                  'G1400376',                 '2021', 'EKA60',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['445', $MNIV, 'MOTONIVELADORA',               'LUI GONG',                                 '78072200',                  'G1400436',                 '2021', 'EGZ79',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['446', $CAMI, 'Camión',                       'IVECO',                                    '8074115',                   '8ATE12NMZX112787',         '2021', 'AF014GW',   $SP, 'EQUIPO HORMIGON',           'EN USO'],
            ['447', $CETA, 'Camioneta',                    'RENAULT ALASKAN',                          'YS23B266C059977',           '8A1D23009NL229469',        '2022', 'AF312OG',   $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['448', $CETA, 'Camioneta',                    'RENAULT ALASKAN',                          'YS23B266C058223',           '8A1D23003NL135474',        '2022', 'AF312OH',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['449', $ACCE, 'RETROEXCAVADORA con Balde',    'NEW HOLLAND B95B',                         '6245677',                   'HBZNB95BVMAH26927',        '2021', 'ELN51',     $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['450', $ACCE, 'RETROEXCAVADORA con Balde',    'NEW HOLLAND B95B',                         '6245204',                   'HBZNB95BKMAH26924',        '2021', 'ELN52',     $SP, 'EQUIPO VIAL',               'EN USO'],
            ['451', $FURG, 'Camioneta',                    'PEUGEOT PARTNER',                          '10YA0500000101',            '8AEGC9HPAPG501965',        '2022', 'AF361QG',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['452', $FURG, 'Camioneta',                    'PEUGEOT PARTNER',                          '10YA0500000197',            '8AEGC9HPAPG502129',        '2022', 'AF361QB',   $GO, 'GOBIERNO',                  'EN USO'],
            ['453', $FURG, 'Camioneta',                    'PEUGEOT PARTNER',                          '10YA050000156',             '8AEGC9HPAPG503508',        '2022', 'AF361QE',   $GO, 'ECONOMIA',                  'EN USO'],
            ['455', $FURG, 'Camioneta',                    'PEUGEOT PARTNER',                          '10YA0500000198',            '8AEGC9HPAPG502124',        '2022', 'AF361QC',   $SE, null,                        'EN USO'],
            ['457', $CETA, 'Camioneta',                    'RENAULT ALASKAN',                          'YS23B266C060145',           '8A1D23001NL228963',        '2022', 'AF428JA',   $ED, 'DIRECCION DE DEPORTE',      'EN USO'],
            ['458', $CETA, 'Camioneta',                    'RENAULT ALASKAN',                          'YS23B266C060890',           '8A1D2300XPL241715',        '2022', 'AF428JB',   $GO, 'PRENSA',                    'EN USO'],
            ['459', $CETA, 'Pick Up',                      'KYC MAMUT',                                'DK15-1020141522',           'LSCABN3E7NE232310',        '2022', 'AF428JF',   $GO, 'PRODUCCION',                'EN USO'],
            ['460', $EXCA, 'EXCAVADORA',                   'BOBCAT',                                   'D1703-7ML5576',             'B4S511602',                '2022', 'ENP11',     $SP, 'AGUAS CORRIENTES',          'EN USO'],
            ['461', $CAMI, 'Camión',                       'IVECO',                                    'F4AE3681E*8095846',         '8ATA1RMHOPX118355',        '2022', 'AF428JV',   $SP, 'EQUIPO VIAL',               'EN USO'],
            ['462', $OMNI, 'OMNIBUS',                      'AGRALE',                                   'YCA000137',                 '8BBC59B1AFM001750',        '2015', 'OPB452',    $SE, 'TRANSPORTE PUBLICO',        'EN USO'],
            ['463', $OMNI, 'OMNIBUS',                      'AGRALE',                                   'YCA000174',                 '8BBC59B1AFM001749',        '2015', 'OPB428',    $SE, 'TRANSPORTE PUBLICO',        'EN USO'],
            ['464', $CAMI, 'CAMION GRUA',                  'AGRALE',                                   '36751565',                  '8BBC93A2APM000397',        '2022', 'AF570UN',   $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['464', $ACCE, 'hidroelevador',                'hidrogrubert',                             '--------',                  'no posee',                 '2022', 'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['465', $TRAC, 'TRACTOR',                      'PAUNY',                                    'H1S000921',                 'CC23093',                  '2022', 'EOQ64',     $GO, 'PRODUCCION',                'EN USO'],
            ['466', $FURG, 'Camioneta',                    'RENAULT KANGOO',                           'H4MJ759Q178070',            '8A18SRYD4PL375354',        '2022', 'AF689SW',   $GO, 'ECONOMIA',                  'EN USO'],
            ['467', $FURG, 'Camioneta',                    'RENAULT KANGOO',                           'H4MJ759Q177928',            '8A18SRYD4PL375214',        '2022', 'AF689SX',   $DC, 'DESARROLLO SOCIAL',         'EN USO'],
            ['468', $ACCE, 'CHIPIADORA',                   'DEISA',                                    'SERIE 1000 7',              'no posee',                 null,   'no posee',  $SP, 'ESPACIOS VERDES',           'EN USO'],
            ['471', $CIST, 'CISTERNA COMBUSTIBLE 1500 LITROS', 'MAURO',                                'no posee',                  'no posee',                 '2019', 'no posee',  $SP, 'EQUIPO VIAL',               'EN USO'],
            ['472', $CETA, 'Camioneta',                    'RENAULT ALASKAN',                          'YS23B266C069148',           '8A1D23003RL682685',        '2023', 'AG102QX',   $SP, 'PLANTA HORMIGON',           'EN USO'],
            ['473', $CAMI, 'Camión',                       'IVECO TECTOR ATTACK',                      'F4HE3481A8109568',          '8SYS01LF0PX121184',        '2023', 'AG178YJ',   $SP, 'DELEGACION GOWLAND',        'EN USO'],
            ['474', $EXCA, 'EXCAVADORA SOBRE ORUGA',       'LIANGONG MODELOR323',                      '93109192',                  'SCC0024',                  '2023', 'ESD56',     $SP, 'PLANTA HORMIGON',           'EN USO'],
        ];

        foreach ($vehiculos as $v) {
            DB::table('vehiculos')->insert([
                'id_tipo_vehiculo'  => $v[1],
                'nro_patrimonio'    => $v[0],
                'vehiculo'          => $v[2],
                'marca_modelo'      => $v[3],
                'nro_motor'         => $v[4],
                'nro_chasis'        => $v[5],
                'anio'              => $v[6],
                'patente'           => $v[7],
                'id_secretaria'     => $v[8],
                'area'              => $v[9],
                'estado'            => $v[10],
                'id_deposito'       => null,
                'created_at'        => $now,
                'updated_at'        => $now,
            ]);
        }
    }
}
